### PR TITLE
Update city_of_waterloo.json

### PR DESCRIPTION
**Pull request by KHobbs3**
Updated data links and added license information.

### CODE REVIEW

**Comment by iandees** [comment]
Hi! Please don't use the "download" link from hub.arcgis.com as a data source. Please use the original data source.

**Comment by KHobbs3** [comment]
> Hi! Please don't use the "download" link from hub.arcgis.com as a data source. Please use the original data source.

Should be updated now! Thanks.

**Comment by iandees** [comment]
Same on this one. `website` was ok. `data` needed the fix.

**Comment by KHobbs3** [comment]
> Same on this one. `website` was ok. `data` needed the fix.

Try 3... let me know if the last PR is what you had in mind

**Comment by iandees** [comment]
Looks great, thank you!

**Pull request merged**
