### PR TITLE
Update to Olmsted

### PR DESCRIPTION
**Pull request by mmdolbow**
Also, cache seems old - should have about another 1,300 records

### CODE REVIEW

**Comment by mmdolbow** [comment]
Not sure what happened here...I tested the REST query as detailed in the log and I can't get it to fail similarly.

**Comment by trescube** [comment]
Try updating the `data` url from http to https.  I noticed that when i put the http URL into the browser, it redirects to https.

**Comment by mmdolbow** [comment]
good call! Trying now.

**Comment by mmdolbow** [comment]
any chance this can get merged soon?

**Pull request merged**
