### PR TITLE
Add AZ Statewide

### PR DESCRIPTION
**Pull request by ingalls**
Closes: https://github.com/openaddresses/openaddresses/issues/4402

### CODE REVIEW

**Comment by iandees** [comment]
I'm curious how much of this data has useful addresses. That's a lot of (big) parcels...

**Comment by ingalls** [comment]
@iandees Yeah I'm seeing some strange addresses in the list, I have it processing right now to give us a sense of how much useful data is in this.

**Comment by ingalls** [comment]
```
us-az-statewide-1547488438671.geojson.gz
ok - 1769278/3197527 (55.3%) valid addresses
ok - 7 outside of boundary (dropped)
ok - 1428188 have an unsupported number format
ok - 0 are missing street names
ok - 0 could not be parsed
ok - 54 suffered misc failures
```

**Comment by justinelliotmeyers** [comment]
Thanks @ingalls and @iandees !!!!!!!!!!!!!!!!

**Comment by migurski** [comment]
We recently changed the tags for OA sources and it might affect this PR. [Moving forward, "type" tags are now either "protocol" or "format"](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#core-tags). If this PR is still active it might need to be updated.

**Pull request merged**
