### PR TITLE
WIP: added SEMCOG counties

### LINKED ISSUE #1995: Add addresses in suburbs of Detroit, MI
Status:
- [x] **Research sources** and propose best source (and it's data license)
  - [x] Wayne county
  - [x] Oakland county
  - [ ] Macomb county
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

### PR DESCRIPTION
**Pull request by trescube**
Fixes #1995

### CODE REVIEW

**Comment by iandees** [comment]
@trescube you know you can just write a comment "Re-run this please" and it will trigger machine again. You don't have to make fake commits 😄

**Comment by trescube** [comment]
I did not know that, but thanks! I'll do that from now on.

**Comment by migurski** [comment]
I will add a note about this undocumented behavior someplace visible.

**Comment by trescube** [comment]
This should make @justinelliotmeyers 's 2016 complete.

**Comment by justinelliotmeyers** [comment]
¡Feliz Año Nuevo!

**Comment by nvkelso** [comment]
Rocking!

**Comment by nvkelso** [comment]
General question: Is there a sandbox for trying out different regex on sample data from a build?

**Comment by migurski** [comment]
Not entirely; I guess the Python REPL would be the closest thing but it is not satisfying. We do create limited [sample data like this](https://s3.amazonaws.com/data.openaddresses.io/runs/141563/sample.json).

**Pull request merged**
