### PR TITLE
added unit types/ids and address num suffixes

### PR DESCRIPTION
**Pull request by trescube**

### CODE REVIEW

**Comment by slibby** [comment]
City of Fayetteville is outputting 0 records to CSV, we'll need to look into why before merging.

**Comment by slibby** [comment]
Looks like it needs to be changed to `"type": "shapefile"` in the conform and `lat`/`lon` removed.

**Comment by trescube** [comment]
Updated per your suggestion, @slibby.  Any ideas on what's wrong?

**Comment by slibby** [comment]
`SUFDIR` -> `SUF_DIR` is what's causing the error.

also would do add the PRE_TYPE attribute for a few `HWY 110` Addresses
```
"street": [
            "PREDIR",
            "NAME",
            "TYPE",
            "SUFDIR"
        ]
```
to
```
"street": [
            "PREDIR",
            "PRE_TYPE",
            "NAME",
            "TYPE",
            "SUFDIR"
        ]
```

**Comment by trescube** [comment]
GRR!!!! they changed fields on us!

**Pull request merged**
