### PR TITLE
Create montpellier.json

### PR DESCRIPTION
**Pull request by slibby**

### CODE REVIEW

**Comment by iandees** [comment]
Looks like geojson to me... wonder where that tripped up.

**Comment by slibby** [comment]
Working on a fix to conform.py for this

**Comment by iandees** [comment]
:heart: Thank you!

**Comment by slibby** [comment]
This should be fixed by https://github.com/openaddresses/machine/pull/196 -- we'll see once it propagates to the ci workers.

**Comment by slibby** [comment]
Something interesting here where hooked-ci fails with a trailing whitespace in attribution, but succeeds once it's removed. Anyways, this should work now, the previous machine PR took care of the .geojson file extension.

**Comment by migurski** [comment]
That is weird, and I’m having difficulty seeing this change would make the difference.

The [last failing log](http://data.openaddresses.io.s3.amazonaws.com/runs/17454/output.txt) shows what looks like a failed download from the data source, while [the successful one](http://data.openaddresses.io.s3.amazonaws.com/runs/17456/output.txt) seems to find it just fine. I wonder if there is an intermittent problem at `opendata.montpelliernumerique.fr`?

**Comment by migurski** [comment]
Weeeeeeird.

**Pull request merged**
