### PR TITLE
Add City of Winnipeg, Manitoba

### PR DESCRIPTION
**Pull request by iandees**
Fixes https://github.com/openaddresses/openaddresses/issues/2411

Currently stuck because the lat/lon is specified as a single column named `Geometry` what the format `(lat, lon)` and I'm not sure what the best way to split those apart is.

### CODE REVIEW

**Comment by migurski** [comment]
In theory, a regexp should work here?

**Comment by migurski** [comment]
Hm, maybe that doesn’t work. It would be nice if it worked. I might see if there's an easy way to fix Machine for this.

**Comment by nvkelso** [comment]
Bump

**Comment by nvkelso** [comment]
@migurski bump

**Comment by migurski** [comment]
Thanks for the bump, I'll look at this today or tomorrow.

**Comment by iandees** [comment]
Closing this because @ingalls' stopgap is fine.

**Pull request closed without merging**
