### PR TITLE
Contributing to: ua-ua-12-dnipropetrovsk.json

### PR DESCRIPTION
**Pull request by Andygol**
Adding/Updating ua-ua-12-dnipropetrovsk.json

### CODE REVIEW

**Comment by slibby** [comment]
@Andygol Thanks for the contribution! The page used to contribute data is in sore need of an update, so this contribution would need a few more things changed in your branch before it can pass the continuous integration tests:

1. Can you rename the file to /sources/ua/12/city_of_dnipropetrovsk.json?
2. The project expects a "conform" object now as part of the Source json. This would mean the full JSON would be something like this: 
```
{
    "coverage": {
        "country": "UA",
        "state": "UA-12",
        "city": "Dnipropetrovsk"
    },
    "data": "https://www.dropbox.com/s/vercjotzvhluglb/dnipro_addr_bld.shp.zip?dl=0",
    "website": "https://opendata.riga.lv/visas-datu-kopas.html",
    "license": "https://opendata.riga.lv/licence.html",
    "type": "http",
    "compression": "zip",
    "conform": {
        "type": "shapefile",
        "number": "Number",
        "street": "AddressUA"
    }
}
```

If you'd like to try to update your pull request with these changes, go for it, or if you'd like me to assist, I can open a new branch with the info.

Thanks again!

**Comment by Andygol** [comment]
@slibby somethig went wrong with downloading data from dropbox

**Comment by slibby** [comment]
@Andygol try `dl=1` at the end of your data link instead of `dl=0`

**Comment by slibby** [comment]
I'm not sure why that still failed, the .prj file looks fine to me. Perhaps the "__MACOSX" folder in the zip is messing it up. You could try removing that folder from the zip (if you own that source Dropbox location), or adding one of the following to the `conform`:
`"srs" : "EPSG:4326"`
or
`"file": "dnipro_addr_bld.shp"`

Otherwise I'll wait for other project contributors to comment.

**Comment by Andygol** [comment]
@slibby After https://github.com/openaddresses/openaddresses/commit/3713aed24e5b1eea1ae404c124e8786219243957
>Exception: ('Bad SRS. Can only handle EPSG, the SRS tag is %s', None)
2015-11-03 19:52:19,904  WARNING: Nothing processed

Do I need specify SRS? But in .zip *.prj file exist

**Comment by Andygol** [comment]
@slibby Thx :+1: - done

**Comment by iandees** [comment]
@Andygol thanks for working on this and submitting! Can you give some more detail about where this data came from and what sort of processing you did before posting it to your Dropbox?

**Comment by Andygol** [comment]
@iandees these data shared by **M@ster_dp** - http://forum.openstreetmap.org/viewtopic.php?pid=558717#p558717. As I know he is representative of a software company which is now developing soft for municipality authorities based on OSM. So it happened that the company for a long time were collected and accumulated addresses in Dnipropetrovsk. I was assured that the data collected through their own efforts. Now they have appealed to community to help to import the data to the OSM and they are willing to [share data under the terms of ODbl](http://forum.openstreetmap.org/viewtopic.php?pid=558964#p558964)

I made re-projection (EPSG 3857 -> EPSG:4326) and changed encoding cp1251 -> utf-8

For now these data can't be directly imported because we have an interferences with data contributed by OSM-community. There is discussion about process of import in the Ukrainian branch of OSM-forum. 

Import data to openaddresses is a first step for opening data.

**Pull request merged**
