### PR TITLE
Update at-tirol

### PR DESCRIPTION
**Pull request by slibby**
adding coverage ISO

### CODE REVIEW

**Comment by slibby** [comment]
not sure why this is decompressing to "1" file?

**Comment by ingalls** [comment]
cc/ @migurski

**Comment by slibby** [comment]
Changed file to a "skip" since the error is still unresolved. Not sure how to address the "conflicts" this has.

**Comment by geobrando** [comment]
@slibby...

It looks like @migurski changed the data url in https://github.com/openaddresses/openaddresses/commit/c95565d6f964a808085e3a00bbe5a73beb9d32db in the share-alike process (https://github.com/openaddresses/openaddresses/pull/1408), but it's still failing with similar but slightly different errors. http://data.openaddresses.io.s3.amazonaws.com/runs/33927/output.txt

I would just close this and open up a PR against the current version if you want to skip.  Or just leave it as a failure.

**Pull request closed without merging**
