### PR TITLE
Updates us/nh/statewide source

### PR DESCRIPTION
**Pull request by MiniCodeMonkey**
Previous URL is no longer available

### CODE REVIEW

**Comment by MiniCodeMonkey** [comment]
Any thoughts on what the conform error is caused by?

```
2020-01-09 03:43:10,363  WARNING: Error doing conform; skipping
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/openaddr/__init__.py", line 173, in conform
    csv_path, addr_count = task4.convert(data_source, decompressed_paths, workdir)
  File "/usr/local/lib/python3.5/dist-packages/openaddr/conform.py", line 606, in convert
    rc = conform_cli(source_definition, source_path, dest_path)
  File "/usr/local/lib/python3.5/dist-packages/openaddr/conform.py", line 1328, in conform_cli
    transform_to_out_csv(source_definition, extract_path, dest_path)
  File "/usr/local/lib/python3.5/dist-packages/openaddr/conform.py", line 1305, in transform_to_out_csv
    out_row = row_transform_and_convert(source_definition, extract_row)
  File "/usr/local/lib/python3.5/dist-packages/openaddr/conform.py", line 995, in row_transform_and_convert
    row = row_function(sd, row, k, v)
  File "/usr/local/lib/python3.5/dist-packages/openaddr/conform.py", line 955, in row_function
    row = row_fxn_regexp(sd, row, key, fxn)
  File "/usr/local/lib/python3.5/dist-packages/openaddr/conform.py", line 1069, in row_fxn_regexp
    pattern = re.compile(fxn.get("pattern", False))
  File "/usr/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.5/sre_parse.py", line 834, in parse
    raise source.error("unbalanced parenthesis")
sre_constants.error: unbalanced parenthesis at position 20
2020-01-09 03:43:10,485  WARNING: Nothing processed
```

**Comment by iandees** [comment]
Looks like the regex in `street` is broken.

**Comment by MiniCodeMonkey** [comment]
Ah great! Thanks for catching that.

**Comment by MiniCodeMonkey** [comment]
Beautiful! 😍 

Just checked the data output. Looks good.

**Pull request merged**
