### PR TITLE
added Pierce County, WA

### LINKED ISSUE #2174: Pierce County, WA Parcel Data
pierce_co_wa

TERMS OF USE here: http://yakima.co.pierce.wa.us/GeoDataExpress/PierceCountyGISDataTermsofUse.pdf

@nvkelso can you look over the terms above to make sure the data is okay to use?  I believe it is, just want another set of eyes to check it out before a PR is created.  Thanks!

the address field is: Site_Address; physical location address of the property. Site address may be different than the mailing address. When a site address contains "XXX" it means the house number is unverified.

ArcGIS open data portal site: http://gisdata.piercecowa.opendata.arcgis.com/datasets/0bddcec060764ce8a6b6c07a60af170c_0

Rest: https://services2.arcgis.com/1UvBaQ5y1ubjUPmd/arcgis/rest/services/Tax_Parcels/FeatureServer/0

### PR DESCRIPTION
**Pull request by trescube**
Fixes #2174

### CODE REVIEW

**Comment by nvkelso** [comment]
We're nearing complete urban core of Washington State coverage :)

**Comment by trescube** [comment]
Should've put WIP in there, I haven't verified that the regexes worked yet.

**Comment by trescube** [comment]
Regexes don't work, I'll start a new PR.

**Comment by iandees** [comment]
Sorry about that!

**Comment by trescube** [comment]
No problem, the first run timed out and I had gone to lunch by the time the second finished.

**Pull request merged**
