### PR TITLE
added Orange County, NY

### LINKED ISSUE #2285: Orange County, NY
http://ocgis.orangecountygov.com/ArcGIS/rest/services/Dynamic/LandBase/MapServer/0

(For https://twitter.com/mrejfox/status/811945914067718144)

### PR DESCRIPTION
**Pull request by trescube**
Fixes #2285

### CODE REVIEW

**Comment by trescube** [comment]
Re-run this please

**Comment by trescube** [comment]
It looks like the failing logic is here:  https://github.com/openaddresses/machine/blob/master/openaddr/cache.py#L391-L401

From what I can tell, no error is being thrown from `shp.centroid` (which calculates the centroid, I assume), but the returned centroid has no `x` field.  Could another type of error besides a `RuntimeError` be thrown by `shp.centroid`?

**Comment by trescube** [comment]
I ran this source thru [pyesridump](https://github.com/openaddresses/pyesridump) and for the problem lines, `NaN` is output for the coordinates:

```
{"geometry": {"type": "Point", "coordinates": [NaN, NaN]}, "type": "Feature", "properties": {"OBJECTID": 147905, "CityStateZip": "MIDDLETOWN NY 10940", "UnitType": "", "StreetAddress": "88 DUNNING RD ", "UnitNumber": "", "SHAPE.fid": 146604}}
```

**Comment by nvkelso** [comment]
@migurski @iandees @trescube was there another recent issue that was failing when no valid geom? I can't find it to relate it to this one, but maybe you can sleuth it out :)

**Comment by iandees** [comment]
The street names don't seem to be coming through in my spot-checks via the dotmap.

**Comment by trescube** [comment]
Regexes need work, streets aren't coming out right, city/region/postcode are sometimes wrong.

**Comment by nvkelso** [comment]
YES! +1000 :)

On Fri, Mar 3, 2017 at 10:51 AM, OpenAddresses Bot <notifications@github.com

**Comment by trescube** [comment]
Hopefully.  It's still a WIP, waiting on last build to do final checks.

**Comment by thatdatabaseguy** [comment]
P.S. ran this locally using the new pyesridump with https://github.com/openaddresses/pyesridump/pull/33 and it runs in a few minutes instead of 2 hours, so turnaround should be much faster on similar sources in the future.

**Comment by thatdatabaseguy** [comment]
LGTM

**Pull request merged**
