### PR TITLE
Use national data source for Finland

### LINKED ISSUE #1662: Finnish nationwide data
Is available at https://www.avoindata.fi/data/fi/dataset/rakennusten-osoitetiedot-koko-suomi

I'll do a pull request to replace the existing data sources with this data.

### PR DESCRIPTION
**Pull request by hannesj**
Fixes #1662

### CODE REVIEW

**Comment by migurski** [comment]
Nice! I see a few failures in the list, mostly missing columns.

**Comment by hannesj** [comment]
It seems they come from a couple of errors to fetch the data (if you look at the samples, they contain 504 gateway timeouts). I'll refresh the tests by doing  a force push.

There is an issue however with how to filter out empty rows. The data is based on building centroids, and not all buildings have an official address, so there are lots of rows without a street name and number in the converted data.

**Comment by migurski** [comment]
Great! A force-push might not be sufficient to re-run the tests; you might want to add some whitespace changes to convince the CI system that it’s seeing something new.

**Comment by hannesj** [comment]
@migurski I pushed it and all tests seem to be fine this time.

**Comment by slibby** [comment]
This is fantastic -- great work, @hannesj! That's a lot of effort I'm sure.

**Comment by migurski** [comment]
🇫🇮 thank you! 🇫🇮

**Pull request merged**
