### PR TITLE
[Don’t Merge] Moved Canberra to ESRI hosting

### PR DESCRIPTION
**Pull request by migurski**
* [ ] Wait for https://github.com/openaddresses/machine/issues/272

### CODE REVIEW

**Comment by migurski** [comment]
Hm, “source has 1 rows” doesn’t sound right.

**Comment by iandees** [comment]
It looks like there this is a single bounding box on this layer and not actual points:

http://www.arcgis.com/home/webmap/viewer.html?url=https://services1.arcgis.com/E5n4f1VY84i0xSjy/ArcGIS/rest/services/Geocoded_Addressing/FeatureServer/0&source=sd

**Comment by migurski** [comment]
Boo to them.

**Comment by migurski** [comment]
Don’t think this new source will work, since it’s not got address points.

**Pull request closed without merging**
