### PR TITLE
Slovenia countrywide: preserving original ID and other improvements

### LINKED ISSUE #2983: Slovenia missing bilingual names
In #2926 official Slovenian names were imported for the whole Slovenia.

However, there are bilingual regions in the country, where they also use non-Slovenian languages:
* Italian in the western part and 
* Hungarian in the north-eastern part

In these regions the street signs contain both names, one above the other or separated by slash (eg "Tartinijeva ulica / Via Giuseppe Tartini" or "Mostje / Hidvég").

Datasource contains these alternative name in non-Slovenian language in some regions for Street (field `UL_DJ`) and City (field `NA_DJ`), but it does not specify in which language it is.

How could we import these properly?
* If alternative name exist, add it to the same csv, separated by Slash (as examples above, easiest, in the spirit of bilingualism, but makes names very long in some cases and might be difficult to search)
* Create new source for each language (it and hu) - here it is not clear:
  * What addresses should be contained in such CSVs? Just those that have some parts in the alternative language or all addresses (with fallback to official Slovenian name)?
  * How to determine which language is the alternative language? By regions or split country vertically and say that east=Hungarian and west=Italian?

Investigating the dataset...

### Street names
There are 626 bilingual streets in 4 communes:

OB_MID | OB_ID | OB_UIME (Commune) | Region | Language (via common sense)
-----------|----------|----|----|-
11027822 | 59|Lendava| Prekmurje |Hungarian
11027776 | 50|Koper|Obalno-Kraška|Italian
11026923 | 40|Izola|Obalno-Kraška|Italian
11027997 | 90 |Piran|Obalno-Kraška|Italian
24063526 | 213|Ankaran|Obalno-Kraška|Italian

But not all streets in these communes are bilingual, there are 52 streets with only Slovenian name. And there are other Communes in these 2 regions with no bilingual street names.

### City names
There are 54 bilingual city names in 9 communes:

OB_MID| OB_ID| OB_UIME (Commune)  | Region | Language (via common sense)
-----------|----------|----|----|-
11027822|59|Lendava| Prekmurje |Hungarian
11026877|33|Šalovci| Prekmurje |Hungarian
21427764|161|Hodoš| Prekmurje |Hungarian
21427713|156|Dobrovnik| Prekmurje |Hungarian
11027130|78|Moravske Toplice| Prekmurje |Hungarian
11027776 | 50|Koper|Obalno-Kraška|Italian
11026923 | 40|Izola|Obalno-Kraška|Italian
11027997 | 90 |Piran|Obalno-Kraška|Italian
24063526 | 213|Ankaran|Obalno-Kraška|Italian

But again not all city names in these communes are bilingual, there are 133 cities with only Slovenian name. And there are other Communes in these 2 regions with no bilingual city names.

### PR DESCRIPTION
**Pull request by stefanb**
* Preserving original ID (`HS_MID`) - 	a69f5ff
* Using https://github.com/mrihtar/GeoCoordinateConverter for more accurate positions - bde0bed
* Added bilingual names - f3f679b - fixes #2983 in one possible way
* some other minor cosmetic changes

### CODE REVIEW

**Comment by stefanb** [comment]
Please review and merge this, as there are no changes planned in near future and zipped CSV file is already prepared using all these changes daily, just the source JSON is not matching perfectly (added `id` and  `accuracy` to conform, and English name to attribution).

**Comment by iandees** [comment]
I'd prefer that we don't add a submodule to the repo. Can you copy the important parts from that repo into this one so the script will run?

**Comment by stefanb** [comment]
Copying "important parts" of that repository is a bit tricky, as https://github.com/mrihtar/GeoCoordinateConverter is a C project and would mean basically copying most of it.
I can:
* make it a poor-man's submodule,
  * referenced only in README.md, with build instructions (easiest) or 
  * make a script to checkout and build exact same version (which requires also a minor modification in working copy of GeoCoordinateConverter) or
* revert bde0bedc67975445165a17f814dc47f8c143e996, which would result in poorer accuracy, which i would like to avoid - results are off by a few meters when doing conversion with gdal (ogr2ogr).

**Comment by stefanb** [comment]
Removed the git submodule as desired by @iandees (in 9a179d5) and replaced it with automatic checkout of it from github when needed (if it is not existing yet) and building just the needed gk-shp (in 1b2cc0b).
This should make it easier to maintain this repository.

**Comment by migurski** [comment]
Looking good @stefanb; would you say this is ready for merging?

**Comment by stefanb** [comment]
Yep.

**Comment by migurski** [comment]
Thank you! 🇸🇮

**Pull request merged**
