### PR TITLE
Add us hi hawaii

### LINKED ISSUE #2032: Add addresses in Hawaii (outside of Honolulu)
Status:
- [ ] **Research sources** and propose best source (and it's data license)
  - [x] Kauai County https://github.com/openaddresses/openaddresses/pull/2567
  - [x] Maui County
  - [ ] Hawaii County https://github.com/openaddresses/openaddresses/pull/2565
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

### PR DESCRIPTION
**Pull request by trescube**
Fixes #2032

### CODE REVIEW

**Comment by trescube** [comment]
@migurski @iandees This source has a GDAL error:

```
2017-02-23 16:36:11,445    ERROR: GDAL gave Failure 1: IllegalArgumentException: Invalid number of points in LinearRing found 3 - must be 0 or >= 4
```

Doesn't the machine skip records that have invalid geometries?

**Comment by iandees** [comment]
@trescube I don't see any information about where this file in Dropbox came from. Do you have any history on it?

**Comment by justinelliotmeyers** [comment]
@iandees or @trescube what can I do to help get this back on track and fixed? Thanks!

**Comment by iandees** [comment]
This would be fixed with https://github.com/openaddresses/machine/issues/651.

**Comment by ingalls** [comment]
re-run please

**Comment by ingalls** [comment]
rerun please

**Comment by ingalls** [comment]
Rerun this please.

**Pull request merged**
