### PR TITLE
Slovenia: add buildings countrywide

### PR DESCRIPTION
**Pull request by stefanb**
Related:
* ~~blocked by https://github.com/openaddresses/batch-machine/issues/26~~ removed `srs` attribute as a workaround to https://github.com/openaddresses/batch-machine/pull/27

### CODE REVIEW

**Comment by ingalls** [comment]
@stefanb You can see logs for an individual job on the job's page

Clicking on the `openaddresses/data-pls` should take you to the Run page
Screenshot from 2021-09-29 18-01-03

Then click on an individual job and you should see the Job page. Click the little note icon in the upper right hand corer to see logs for the job
Screenshot from 2021-09-29 18-01-08

```
ok - updating job: 161025 with {"status":"Running","version":"1.0.1","output":{"cache":false,"output":false,"preview":false},"loglink":"batch-prod-job/default/6244b1476cc24d38846598dc345185f9"}
[{"keyword":"additionalProperties","dataPath":".layers.buildings[0].conform","schemaPath":"#/additionalProperties","params":{"additionalProperty":"encoding"},"message":"should NOT have additional properties"}]
Error: Source does not conform to V2 schema
    at Job.fetch (/usr/local/src/batch/lib/job.js:98:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async flow (/usr/local/src/batch/task.js:102:9)
ok - updating job: 161025 with {"status":"Fail"}
false
```

**Comment by stefanb** [comment]
Tnx, @ingalls, was wondering where to see at least the error message.

**Comment by stefanb** [comment]
Encoding could be useful if we want to bring some other attributes:
> 2021-09-30 04:51:38,774 WARNING: No encoding given and OGR couldn't guess. Trying ISO-8859-1, YOLO!

😁
Not strictly needed yet.

**Comment by stefanb** [comment]
@ingalls, should I do anything here about the flipped lat & lon in the CSV addresses? See #5917

**Comment by stefanb** [comment]
@ingalls , can you please check why is it treating buildings shapefile as addresses?

The log 
https://batch.openaddresses.io/job/163978/log says:

> 2021-10-05 20:34:50,010    INFO: Converted to /tmp/ok3q1sko33/process_one-qoawu7gd/conform-uwd3y3n2/converted/KS_SLO_SHP_G_TLORISI.csv with 1183816 addresses

And while treating it as addresses CSV it flips the coordinates wrongly.

**Pull request merged**
