### PR TITLE
Create us-mn-crow_wing.json

### PR DESCRIPTION
**Pull request by mmdolbow**
Discovered today. Unusual: "CITY" field appears to contain only numbers. H_NUM and STREET fields are available but seem less consistently filled than ADDRESS. (5720 records where H_NUM=0.)

### CODE REVIEW

**Comment by migurski** [comment]
Thanks @mmdolbow! Can you move the file into the `sources` directory?

**Comment by mmdolbow** [comment]
I think I just moved it...I stink at this sometimes...

**Comment by migurski** [comment]
You did! Looks like you also closed the PR; I’ll re-open and merge it.

**Comment by mmdolbow** [comment]
Whoops, thanks for covering. Hope this one's a winner. :dart:

**Pull request merged**
