### PR TITLE
Fix broken sources

### PR DESCRIPTION
**Pull request by iandees**

### CODE REVIEW

**Comment by migurski** [comment]
St. Louis, Cecil, Woodford, and Scott:

preview-st_louis

preview-cecil

preview-woodford

preview-scott

**Comment by iandees** [comment]
Looks like the FTP cacher is broken maybe?

**Comment by migurski** [comment]
Goodhue:

preview-goodhue

**Comment by migurski** [comment]
`TypeError: 'str' does not support the buffer interface` sounds like a Python 2/3 unicode issue. Could we make a test case for this in machine?

**Comment by migurski** [comment]
Also, Champaign:

preview-champaign

**Pull request merged**
