### PR TITLE
Adding Unit Types/ID's for Canada: Alberta, British Columbia

### PR DESCRIPTION
**Pull request by riordan**
Adds units + field review for places (with units) in Alberta + BC.

### CODE REVIEW

**Comment by riordan** [comment]
Any thoughts on why this is failing?

**Comment by iandees** [comment]
It looks like at least some ESRI servers fail to run a query when we specify a list of fields.

e.g. [this query with `outFields=ParentId` specified](http://tnrdmap.tnrd.ca/arcgis/rest/services/Basemap_Detail_Cache/MapServer/3/query?where=1%3D1&outFields=ParentId&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=7&outSR=4326&resultOffset=0&resultRecordCount=1000&f=json) fails, but [this query with `outFields=*`](http://tnrdmap.tnrd.ca/arcgis/rest/services/Basemap_Detail_Cache/MapServer/3/query?where=1%3D1&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=7&outSR=4326&resultOffset=0&resultRecordCount=1000&f=json) runs fine.

**Comment by slibby** [comment]
This seems to work fine: 
`http://tnrdmap.tnrd.ca/arcgis/rest/services/Basemap_Detail_Cache/MapServer/3/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=Community%2CHouseNo%2CHouseSuffix%2CStreetName%2CStreetSuffix%2CSuiteNo&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&f=json`

**Comment by iandees** [comment]
@slibby's URL doesn't include any of the paging stuff.

This works:
http://tnrdmap.tnrd.ca/arcgis/rest/services/Basemap_Detail_Cache/MapServer/3/query?where=1%3D1&outFields=Community%2CHouseNo%2CHouseSuffix%2CStreetName%2CStreetSuffix%2CSuiteNo&returnGeometry=true&geometryPrecision=7&outSR=4326&f=json&resultOffset=0&resultRecordCount=1

This doesn't (adding `resultRecordCount=100`):
http://tnrdmap.tnrd.ca/arcgis/rest/services/Basemap_Detail_Cache/MapServer/3/query?where=1%3D1&outFields=Community%2CHouseNo%2CHouseSuffix%2CStreetName%2CStreetSuffix%2CSuiteNo&returnGeometry=true&geometryPrecision=7&outSR=4326&f=json&resultRecordCount=100

This works (`outFields=*`):
http://tnrdmap.tnrd.ca/arcgis/rest/services/Basemap_Detail_Cache/MapServer/3/query?where=1%3D1&outFields=*&returnGeometry=true&geometryPrecision=7&outSR=4326&f=json&resultRecordCount=100

**Comment by slibby** [comment]
@iandees Yeah, very strange. I noticed the first link you posted actually doesn't work for me, I think any resultRecordCount is failing.

**Comment by riordan** [comment]
Just pulled it out and opened an issue on it to remember for later (#1511)

**Pull request merged**
