### PR TITLE
au/act buildings

### PR DESCRIPTION
**Pull request by andrewharvey**
@ingalls is v2 schema ready to go?

### CODE REVIEW

**Comment by andrewharvey** [comment]
"16 284.3 ERROR: Nothing processed: 'buildings' layer not currently supported"

looks like I may have been a bit too eager with this PR.

**Comment by ingalls** [comment]
@andrewharvey If we can hold off pushing v2 sources until we have completed the migration that would be great, but it's finalized. 
There is an active staging deployment here: http://staging.openaddresses.io/data The new processing code lives here: https://github.com/openaddresses/batch and the migration is being finalized here: https://github.com/openaddresses/migrate

**Comment by andrewharvey** [comment]
I'll close this for now, if buildings are supported later, I can do a new PR.

**Comment by ingalls** [comment]
Building should be supported within the next week, the support has been added to `batch-machine`, I just haven't wired up support for it in the schema & `batch` itself

**Pull request closed without merging**
