### PR TITLE
Added source us-tx-city_of_sugar_land

### LINKED ISSUE #2011: Add addresses in Sugar Land, TX

### PR DESCRIPTION
**Pull request by davidchiles**
Fixes #2011.

### CODE REVIEW

**Comment by migurski** [comment]
Just added support for this comment syntax to trigger a re-build in https://github.com/openaddresses/machine/issues/378:

Re-run this, please.

**Comment by iandees** [comment]
:clap:

**Comment by migurski** [comment]
I’m going to leave this PR open for a bit, because [I’m still chasing an error that I fixed messily](https://github.com/openaddresses/machine/issues/378#issuecomment-250567086).

**Comment by migurski** [comment]
Asking for another run to verify that the cached results will be re-used:

Rerun this, please.

**Comment by migurski** [comment]
Asking for a third run, now that [2.34.0 is released](https://github.com/openaddresses/machine/releases/tag/2.34.0):

Re-run this please.

**Comment by migurski** [comment]
screen shot 2016-09-30 at 3 11 04 pm

**Pull request merged**
