### PR TITLE
Add share-alike license tags

### LINKED ISSUE #1407: Document new share-alike tag support
Sixth task for openaddresses/openaddresses-ops#7: document new share-alike tags in license dictionaries, and add values for a few known-SA licenses.

### PR DESCRIPTION
**Pull request by migurski**
* [x] Document share-alike license tag in CONTRIBUTING.md
* [ ] Add tests for new share-alike license tag.
* Populate share-alike values in licenses with known properties. Complete list of all current licenses in OA:
    * [x] 64 `Public Domain`
    * [x] 47 `http://nlftp.mlit.go.jp/ksj/other/yakkan.html`
    * [x] 32 `http://datos.gob.mx/libreusomx/`
    * [x] 25 `CCBY`
    * [x] 18 `Indemnification`
    * [x] 16 `Polish Law on Geodesy and Cartography of 17 May 1989 - see https://github.com/openaddresses/openaddresses/issues/187#issuecomment-63327973`
    * [x] 4 `http://www.catastro.minhap.es/ayuda/legislacion/ovc/resoluciondgc20110323_tfs.pdf`
    * [ ] 3 `http://www.bev.gv.at/portal/page?_pageid=713,2573888&_dad=portal&_schema=PORTAL`
    * [ ] 2 `Crappy License`
    * [ ] 2 `http://bric.brussels/en/our-solutions/urbis-solutions/Licence%20Open%20data%20Fr%20v4.pdf`
    * [ ] 2 `http://creativecommons.org/licenses/by/4.0/`
    * [x] 2 `http://opendatacommons.org/licenses/pddl/1.0/`
    * [ ] 2 `http://www.dati.gov.it/iodl/2.0/`
    * [ ] 2 `http://www5.kingcounty.gov/gisdataportal/`
    * [x] 2 `public domain`
    * [ ] 1 `§ 62 of Law 111/2009 Sb - http://www.zakonyprolidi.cz/cs/2009-111#p62`
    * [x] 1 `CC 0`
    * [x] 1 `CC by 3.0`
    * [x] 1 `CC0 (http://creativecommons.org/about/cc0)`
    * [x] 1 `CCBY3.0`
    * [ ] 1 `http://app.kitchener.ca/opendata/license.aspx`
    * [ ] 1 `http://ccgovernment.carr.org/ccg/mapserver4/gis/webpage/TermsOfUse.pdf`
    * [ ] 1 `http://citymaps.durban.gov.za/GISMetaData/Files/Metadata/Cadastral/Approved_Cadastre/addresspoint.htm`
    * [ ] 1 `http://cms.burlington.ca/AssetFactory.aspx?did=18762`
    * [ ] 1 `http://cosb.countyofsb.org/gis/default.aspx?id=3458`
    * [ ] 1 `http://creativecommons.org/licenses/by/3.0/au/deed.en`
    * [ ] 1 `http://data.buenosaires.gob.ar/tyc`
    * [ ] 1 `http://data.dc.gov/TermsOfUse.aspx`
    * [ ] 1 `http://dawa.aws.dk/om`
    * [ ] 1 `http://dds.information.qld.gov.au/DDS/GetLicenseImage.license?ID=15`
    * [ ] 1 `http://egis3.lacounty.gov/dataportal/disclaimer/`
    * [ ] 1 `http://geonb.snb.ca/documents/license/geonb-odl_en.pdf`
    * [ ] 1 `http://geoweb.montevideo.gub.uy/geonetwork/srv/es/metadata.show?uuid=7b33c155-0199-4fca-848e-95d18056a616`
    * [ ] 1 `http://gis.co.franklin.wa.us/datadisclaimer.shtml`
    * [ ] 1 `http://gis.lawrenceks.org/arcgis/rest/services/AddressPoints/MapServer/0`
    * [ ] 1 `http://gis.napa.ca.gov/giscatalog/viewXML.asp?Name=MAINGIS.GIS.ADDRESSES_ALL&meta_style=fgdc`
    * [ ] 1 `http://maps.hscounty.com/mapserver/`
    * [ ] 1 `http://oakville.ca/data/open_data_licence.html`
    * [ ] 1 `http://openguelph.wpengine.com/open-data-guelph/city-of-guelph-open-government-licence/`
    * [ ] 1 `http://ottawa.ca/en/mobile-apps-and-open-data/open-data-terms-use`
    * [ ] 1 `http://princegeorge.ca/cityservices/online/odc/Pages/Terms.aspx`
    * [ ] 1 `http://stlcin.missouri.org/citydata/downloads/terms.cfm`
    * [ ] 1 `http://teto.tampere.fi/lisenssit/tre_avoimen_datan_lisenssi.pdf`
    * [ ] 1 `http://vcgi.vermont.gov/sites/vcgi/files/warehouse/VCGI_Warranty_Copyright_Notice_2013.pdf`
    * [ ] 1 `http://www.acgov.org/acdata/terms.htm`
    * [ ] 1 `http://www.bakersfieldcity.us/gis/gis_spatial_data.htm`
    * [ ] 1 `http://www.banffopendata.ca/Home/About`
    * [ ] 1 `http://www.ccgov.org/dept_planning/gis/orthos/licenseagreement_4_6_07.pdf`
    * [ ] 1 `http://www.ccmap.us/information.asp`
    * [ ] 1 `http://www.city.kamloops.bc.ca/maps/disclaimer.html`
    * [ ] 1 `http://www.cityofhenderson.com/gis/disclaimer.php`
    * [ ] 1 `http://www.citywindsor.ca/opendata/Documents/OpenDataTermsofUse.pdf`
    * [ ] 1 `http://www.co.fresno.ca.us/DepartmentPage.aspx?id=52121`
    * [ ] 1 `http://www.co.jefferson.wa.us/idms/mapserver.shtml`
    * [ ] 1 `http://www.co.mason.wa.us/gis/disclaimer.php`
    * [ ] 1 `http://www.co.pacific.wa.us/gis/DesktopGIS/WEB/index.html`
    * [ ] 1 `http://www.countygp.ab.ca/EN/main/community/maps-gis/open-data/open-data-licence.html`
    * [ ] 1 `http://www.districtofwestkelowna.ca/Modules/ShowDocument.aspx?documentid=7602`
    * [ ] 1 `http://www.douglascountywa.net/departments/tls/gis/`
    * [ ] 1 `http://www.edc.uri.edu/rigis/license.html`
    * [ ] 1 `http://www.gov.pe.ca/gis/index.php3?number=77462&lang=E`
    * [ ] 1 `http://www.hamilton.ca/NR/rdonlyres/C58984A4-FE11-40B9-A231-8572EB922AAA/0/OpenDataTermsAndConditions_Final.htm`
    * [ ] 1 `http://www.k3gis.com/#contact`
    * [ ] 1 `http://www.kitsapgov.com/county/disclaimer.htm`
    * [ ] 1 `http://www.midmogis.org/mapdisclaimer.asp`
    * [ ] 1 `http://www.nanaimo.ca/EN/main/departments/information-technology/DataCatalogue/Licence.html`
    * [ ] 1 `http://www.placer.ca.gov/departments/communitydevelopment/gis/gis_download`
    * [ ] 1 `http://www.regina.ca/residents/open-government/data/terms/index.html`
    * [ ] 1 `http://www.sangis.org/Legal_Notice.htm`
    * [ ] 1 `http://www.sistemapiemonte.it/sitad/ricercaEntita.do?idEntita=10001942&interfaccia=rupar&ricerca=off&authType=guest`
    * [ ] 1 `http://www.skra.is/fasteignaskra/nidurhalsthjonusta/stadfangaskra/user-licence/`
    * [ ] 1 `http://www.victoria.ca/EN/main/city/open-data-catalogue/open-data-licence.html`
    * [ ] 1 `http://www.welland.ca/open/OpendataTermUse.asp`
    * [ ] 1 `http://www.yolocounty.org/community-development/planning-public-works/geographic-information-system-gis-/data-downloads`
    * [ ] 1 `http://www1.toronto.ca/wps/portal/contentonly?vgnextoid=4a37e03bb8d1e310VgnVCM10000071d60f89RCRD`
    * [ ] 1 `https://data.calgary.ca/OpenData/Pages/TermsofUse.aspx`
    * [ ] 1 `https://data.chattlibrary.org/terms`
    * [ ] 1 `https://github.com/CityOfPhiladelphia/OIT-geodata/blob/master/Open%20Address%20Data/Readme.md`
    * [ ] 1 `https://isd.smcgov.org/gis-data-download`
    * [ ] 1 `https://opendata.riga.lv/licence.html`
    * [ ] 1 `https://wiki.openstreetmap.org/wiki/AGIV_CRAB_Import/Free_open_data_licence_Flanders`
    * [ ] 1 `https://www.co.dakota.mn.us/HomeProperty/MappingServices/GISData/Pages/default.aspx`
    * [ ] 1 `Imdemnification?`
    * [ ] 1 `Indemnification (http://www.co.walton.fl.us/index.aspx?nid=926)`
    * [ ] 1 `Indemnification (http://www.leegov.com/gis/data/gis-data)`
    * [ ] 1 `Indemnification (https://my.spokanecity.org/opendata/gis/data/#disclaimer)`
    * [x] 1 `Open Database License (ODbL) v1.0 (http://www.oregonmetro.gov/sites/default/files/Open_Database_and_Content_Licenses.pdf)`
    * [ ] 1 `Open Government License - Canada V2.0 (http://www.halifax.ca/opendata/OD_TermsOfUse.php)`
    * [x] 1 `PD`
    * [x] 1 `Public domain`
    * [ ] 1 `Unknown, see website.`

Closes #1407.

### CODE REVIEW

**Comment by sbma44** [comment]
I can fill in a couple of these:

**http://nlftp.mlit.go.jp/ksj/other/yakkan.html**
People in the OSM wiki [have](http://wiki.openstreetmap.org/wiki/Import/Catalogue/Japan_KSJ2_Import) [repeatedly](http://wiki.openstreetmap.org/wiki/JA:MLIT_ISJ#Licenses) [concluded](http://wiki.openstreetmap.org/wiki/Talk:Import/Catalogue/Japan_KSJ2_Import) that CC-BY-style attribition is okay for MLIT data. Google Translate is pretty clean.

**Spain**
I had @lxbarth review http://www.catastro.minhap.es/ayuda/legislacion/ovc/resoluciondgc20110323_tfs.pdf for me way back when & he said it looked clean. Afraid I don't recall more details there, but I suspect we can find someone literate in Spanish to re-review. Google Translate doesn't do an adequate job, but it is clear that the action occurs in the Annex document, which I *think* forbids redistribution of the information _for cadastral purposes_. It's possible that the prohibition on redistribution is wider, however -- we need clarity. It does seem clear that commercial use is allowed.

Worth noting that there's also some nonsense related to accessing the information. We got it from an INSPIRE-affiliated Atom feed, but to use the formal site you need an X.509 certificate issued by a Spanish tax office(!).

**INEGI/Mexico**
Google Translate does a fine job, it's an attribution license: http://www.inegi.org.mx/terminos/terminos_info.aspx?bi=1

**Comment by migurski** [comment]
Thanks Tom, sounds like I should mark Japan & Mexico as BY, and Spain as neither?

**Comment by sbma44** [comment]
@migurski yup, unless you've got somebody with Spanish skills nearby

**Comment by migurski** [comment]
I’m going to take the risk here.

**Comment by migurski** [comment]
I believe this to be ready to merge; there are [a few sources failing for boring reasons](http://results.openaddresses.io/jobs/35244cd3-dab9-4e06-898a-8e65b9cd8680) like missing `conform` tags that I’ve fixed as much as possible.

**Comment by iandees** [comment]
Damnit I bet these last couple PRs I closed caused a conflict. How do you want to handle this @migurski? Rebase your stuff?

**Comment by migurski** [comment]
I’ve not inspected the conflicts yet, but I can do the merge by hand.

**Pull request merged**
