### PR TITLE
Contributing to: south_africa-western cape-cape town.json

### PR DESCRIPTION
**Pull request by sindile**
Adding/Updating south_africa-western cape-cape town.json

### CODE REVIEW

**Comment by slibby** [comment]
@sindile I think you'll need a couple changes before this will pass the CI:
1. Set "compression": "zip"
2. Add a "conform": {} object to your JSON file as is laid out here: https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md

"conform": {
  "type": "shapefile",
  "street": "STREET_NM_FIELD",
  "number": "NUMBER_FIELD"
  }

**Comment by geobrando** [comment]
@slibby In case you're not aware, issues beginning with "Adding/Updating" have been created using http://openaddresses.io/contribute/, which was created to lower the barrier for participation to those not comfortable adding fully formed sources via a github PR.

I believe the thought has been to allow others that are more comfortable to correct these when necessary.  But I'm not sure how to do that without first merging the PR.  Also, I don't think a conform object is required to pass CI.

**Comment by slibby** [comment]
@geobrando Cool, did not know but now I do! I agree I don't really know how to edit/help this contribution without just starting my own PR in this case.

**Comment by sindile** [comment]
I used http://openaddresses.io/contribute/

to bring to the attention of Openaddress Community the availability of 
this address data sort. Maybe I can be advised on what I need to do in 
order for the import to succeed.

Regards,
<http://openaddresses.io/contribute/>

Sindile Bidla

**Comment by geobrando** [comment]
@sindile Your work is done. Thank you very much for the contribution.  Someone else associated with the project will take care of it.

**Comment by geobrando** [comment]
Looks like this source has previously been added

https://github.com/openaddresses/openaddresses/blob/master/sources/za/wc/cape_town.json

**Pull request closed without merging**
