### PR TITLE
Update Friuli-Venezia Giulia source

### PR DESCRIPTION
**Pull request by stepps00**
This change updates the dataset and fields used for addresses in Friuli-Venezia Giulia, Italy.

### CODE REVIEW

**Comment by stepps00** [comment]
Hey @iandees, the data for this source will need to be re-hosted.

**Comment by iandees** [comment]
I'm in progress on generating a form you can use to upload yourself.

In the meantime, can you make sure the process for generating the file you're asking to rehost is either in the `scripts/` directory of this repo or described in detail here?

**Comment by stepps00** [comment]
Awesome, thanks - I can give the form a try once it becomes available. The process for generating the file is as follows:

- Navigate to https://www.dati.friuliveneziagiulia.it/Regioni-e-citt-/Numeri-Civici-Ascot/fcre-uegn
- Click on the "Esportazione" button
- Select the CSV file download option
- Create new X (lon) and Y (lat) fields in the csv. This can be done in QGIS by:
  - importing the csv as a new layer using the "Add Delimited Text Layer..." option
  - right-clicking on the layer and selecting the the "Export > Save Features As..."  option
  - selecting the "AS_XY" option under Geometry

**Comment by stepps00** [comment]
The zip file has been re-hosted and the data url has been updated.

**Comment by iandees** [comment]
The build error here is from broken MVTs from Mapbox.

**Pull request merged**
