### PR TITLE
added St. Johns County, FL

### LINKED ISSUE #2170: us-fl-st_johns
St Johns County address points shapefile is here: http://www.gis.bocc.co.st-johns.fl.us/GISDataDepot/download.aspx?layer=/GISDataDepot/Library/Address_Site.zip

public domain (any public data in FL unless specifically exempted)

### PR DESCRIPTION
**Pull request by trescube**
Fixes #2170

### CODE REVIEW

**Comment by migurski** [comment]
Re-run this please

**Comment by trescube** [comment]
I'm not sure what to do about this one.  The machine errors on extracting the zip file, but I can't replicate the error locally:

```
>>> with ZipFile('us--fl--st-johns-5bf24dbc.zip', 'r') as z:
...     for name in z.namelist():
...         z.extract(name, '.')
...
'Address_Site.sbx'
'Address_Site.shp'
'Address_Site.shp.xml'
'Address_Site.shx'
'Address_Site.cpg'
'Address_Site.dbf'
'Address_Site.prj'
'Address_Site.sbn'
```

**Comment by migurski** [comment]
I guess I'll try this on a similar Linux setup to see if there's something particular about Python 3.4’s zip implementation on that platform.

**Comment by trescube** [comment]
Re-run this please

**Comment by trescube** [comment]
Still bad... I was hoping that they had published a new (and fixed) zip.

**Comment by trescube** [comment]
Re-run this please

**Comment by trescube** [comment]
Huzzah!

**Pull request merged**
