### PR TITLE
Create bologna.json

### PR DESCRIPTION
**Pull request by slibby**

### CODE REVIEW

**Comment by slibby** [comment]
I think this is failing because the embedded file is civici.Shp, not .shp or .SHP, which OGR expects maybe?

**Comment by ingalls** [comment]
@slibby Mind trying the `file` attribute on the `conform` object?

Docs here: https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#processing-tags

**Comment by slibby** [comment]
@ingalls that's what I tried in the second commit... I think?

**Comment by ingalls** [comment]
Darn, I'm sorry, yes you did. Looks like a possible problem with machine. I can take a look tomorrow, or @migurski might know what is going on right away.

**Comment by slibby** [comment]
Changed to a skip, issue started here: https://github.com/openaddresses/machine/issues/257

**Pull request merged**
