### PR TITLE
British Columbia

### PR DESCRIPTION
**Pull request by ingalls**
This is another big one! Please don't merge this until I have a change to review the output data.

### CODE REVIEW

**Comment by slibby** [comment]
Count: 1,311,190 :clap:

**Comment by ingalls** [comment]
For some reason the ESRI scraper missed a couple - 1311044 but no biggie.

**Comment by ingalls** [comment]
https://fangirlsarewe.files.wordpress.com/2013/06/capt_hook3.jpg

@migurski I think you need to change the hooked icon to ^^.

**Comment by migurski** [comment]
Hmmmm…

**Comment by migurski** [comment]
How does the output data look?

**Comment by migurski** [comment]
Also, can I recommend this change to coverage:

    "coverage": {
        "ISO 3166": {"alpha2": "CA-BC", "country": "Canada", "subdivision": "British Columbia"},
        "country": "ca",
        "state": "bc"
    },

**Pull request merged**
