### PR TITLE
Update Mexico Countrywide

### PR DESCRIPTION
**Pull request by crebollobr**
update INEGI data
fix license share-alike flag and url of license

### CODE REVIEW

**Comment by iandees** [comment]
This is an updated version of the change proposed in #7245, where there is more discussion about this data source and how it was built.

**Comment by iandees** [comment]
Thanks for the change and updating the data!

I'll merge this in as-is, but I'm curious if we can add back the city information to the address.

**Comment by crebollobr** [comment]
I will work in put city in data.
This is next step.
I will merge again with new data
thanks

**Comment by iandees** [comment]
Perfect, thank you!

**Pull request merged**
