### PR TITLE
add Nelson Mandela Bay Municipality, South Africa

### PR DESCRIPTION
**Pull request by thatdatabaseguy**
Couldn't find a license, but here's the conform in case anyone has more luck.

Website: http://www.nelsonmandelabay.gov.za/Business.aspx?pageID=154

### CODE REVIEW

**Comment by migurski** [comment]
Wow, look at that density!

**Comment by nvkelso** [comment]
I've asked them about the license today via http://www.nelsonmandelabay.gov.za/DepartmentFeedback.aspx.

**Comment by nvkelso** [comment]
I think this is fine to merge, it's CC-BY.

Here's the response to my email about the license:

```
Good Day
 
We are still in the process of updating the terms and conditions but in 
essence below are the terms.
 
1)
NMBM makes no warranty of any kind, expressed or
implied, with regard to the data and shall not be held liable
in any event for any incidental or consequential damages in
connection with or arising out of the use of this data.
2)
Provide credit to the NMBM when using the data.
 
3)
You can redistribute the data but please then also send on the T&C.
 
 
 
 
Kind Regards
Franco Cilliers
GIS Analyst
NMBM
Tel: 041 506 1979
-33.961766, 25.621739
2nd Floor Algoa House
Chapel Street, Central, PE
```

**Comment by nvkelso** [comment]
LGTM, merging.

**Pull request merged**
