### PR TITLE
Added us/ky/boone

### PR DESCRIPTION
**Pull request by davidchiles**
I had problems testing this locally. The connection would `Read timed out`.

### CODE REVIEW

**Comment by trescube** [comment]
Re-run this please

**Comment by trescube** [comment]
Re-run this please

**Comment by ingalls** [comment]
@trescube maybe https://secure.boonecountygis.com/ags/rest/services/ParcelLayers/MapServer/0

**Comment by trescube** [comment]
Tried that but getting read timeouts with pyesridump.  I'll try letting the machine handle it.

**Comment by ingalls** [comment]
Closing Stale PRs. Feel free to reopen if still relevant.

**Pull request closed without merging**
