### PR TITLE
Added us/ks/city_of_wichita

### LINKED ISSUE #2002: Add addresses in Wichita, Kansas
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

### PR DESCRIPTION
**Pull request by davidchiles**
Fixes #2002

### CODE REVIEW

**Comment by thatdatabaseguy** [comment]
There's a field called Prop_Addr_Unit in this data set that's appended to Prop_Addr and thus the street field in the output. This could be corrected with "remove_postfix", but I don't think the conforms allow functions to be chained.

**Comment by davidchiles** [comment]
@thatdatabaseguy I think I understand what you mean. 

`street` needs both:
```js
{
    "function": "postfixed_street",
    "field": "Prop_Addr"
}
```
and 
```js
{
    "function": "remove_postfix",
    "field": "Prop_Addr",
    "field_to_remove": "Prop_Addr_Unit"
}
```

Which isn't possible?

**Comment by davidchiles** [comment]
I also notice from the render that this is really all of Sedgwick County. Related #2155.

**Comment by thatdatabaseguy** [comment]
@davidchiles  yep. Perhaps defining a "compound" function for machine would be worthwhile - that can probably save more than one nasty regex. Will try to make a PR for it over the next few days.

**Comment by iandees** [comment]
Re-run this, please.

**Pull request merged**
