### PR TITLE
Added us/ks/sedgwick

### PR DESCRIPTION
**Pull request by davidchiles**

### CODE REVIEW

**Comment by davidchiles** [comment]
🤔  Looks like you can't query this endpoint.

**Comment by trescube** [comment]
I'm on a train with terrible wifi and the file is 57mb, but it looks like the property parcels are available here:

http://gis.sedgwick.gov/gisdata/layer2.asp

**Comment by justinelliotmeyers** [comment]
@trescube is this finished?  Thanks!

**Comment by trescube** [comment]
pyesridump can't grab this data either.  This is a good excuse to write a brute force scraper that I've been thinking about.  Will try tonight.

**Comment by iandees** [comment]
:( please write bugs or pull requests for pyesridump if you can.

**Comment by trescube** [comment]
They appear to have all querying turned off:

```
2017-03-01 11:44:36,011 - cli.esridump - ERROR - Could not parse response from https://gismaps.sedgwickcounty.org/arcgis/rest/services/Map/Op_SiteAddress_Dynamic_SP/MapServer/0/query?returnCountOnly=true&where=1%3D1&f=json as JSON:

<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 11833783245905056836</body></html>
```

I tried requesting with the referer sent by the https://gismaps.sedgwickcounty.org/portal/ and had no luck.  

Would you be open to pyesridump brute force scraping an Esri endpoint?

**Comment by iandees** [comment]
It depends on what you mean by "brute forcing".

**Comment by trescube** [comment]
It's a very dumb approach:  start at [1](https://gismaps.sedgwickcounty.org/arcgis/rest/services/Map/Op_SiteAddress_Dynamic_SP/MapServer/0/1?f=json) (or wherever the first record has been detected), convert the response to geojson, and increment/iterate until the server returns 404/400.  It would be useful for situations like this where the server is locked down pretty tightly and no metadata can be gleaned by programmatic means.

**Comment by trescube** [comment]
Unless pyesridump already supports something that and I was unable to identify how to enable based on the readme and my limited understanding of python.

**Comment by justinelliotmeyers** [comment]
you can do it in chunks too; <500, >501 and <1000, >1001 and <1500, etc

I have done it a few times manually... no fun

**Comment by iandees** [comment]
Can you make a new ticket on pyesridump and let's move the discussion over there.

**Comment by trescube** [comment]
Moved to openaddress/pyesridump#35

**Comment by iandees** [comment]
I'm going to close this because the server is blocking our requests and I do't want to spend any more time trying to get the data.

**Pull request closed without merging**
