### PR TITLE
Initial comit for Canada National Address Register

### PR DESCRIPTION
**Pull request by jwass**
Addresses #7192

### CODE REVIEW

**Comment by jwass** [comment]
Wasn't sure where to put things but guessed `ca/countrywide`. Let me know if there's a better location.

**Comment by iandees** [comment]
Yep, this is perfect.

**Comment by iandees** [comment]
For posterity, the columns available are: ```LOC_GUID,ADDR_GUID,APT_NO_LABEL,CIVIC_NO,CIVIC_NO_SUFFIX,OFFICIAL_STREET_NAME,OFFICIAL_STREET_TYPE,OFFICIAL_STREET_DIR,PROV_CODE,CSD_ENG_NAME,CSD_FRE_NAME,CSD_TYPE_ENG_CODE,CSD_TYPE_FRE_CODE,MAIL_STREET_NAME,MAIL_STREET_TYPE,MAIL_STEET_DIR,MAIL_MUN_NAME,MAIL_PROV_ABVN,MAIL_POSTAL_CODE,BG_DLS_LSD,BG_DLS_QTR,BG_DLS_SCTN,BG_DLS_TWNSHP,BG_DLS_RNG,BG_DLS_MRD,BG_X,BG_Y,BU_N_CIVIC_ADD,BU_USE,REPPOINT_LATITUDE,REPPOINT_LONGITUDE```

**Comment by iandees** [comment]
A couple things to fix in the `batch` and `batch-machine` systems here:

1. The `batch-machine` data downloader doesn't know how to handle `gzip` files. It only knows `zip`. I could re-compress to a zip file, and I probably will to get this moving faster, but I also think we should add support for it in batch-machine, which I started here: https://github.com/openaddresses/batch-machine/pull/58
2. There is special-casing in the data downloader when the data URL in a conform JSON is on the `data.openaddresses.io` or `v2.openaddresses.io` domain to fetch directly from the S3 buckets that back those URLs so that we don't waste data egress costs by going through the internet. That bit of special-casing was working, but the IAM role used by the data downloader doesn't have access to the `data.openaddresses.io` bucket. I manually updated that but also made https://github.com/openaddresses/batch/pull/388 to make it permanent.

**Pull request merged**
