### PR TITLE
G-NAF Australia data

### PR DESCRIPTION
**Pull request by sbma44**
cache creation script & source JSON for http://data.gov.au/dataset/geocoded-national-address-file-g-naf

cf https://github.com/openaddresses/openaddresses/issues/1470

### CODE REVIEW

**Comment by migurski** [comment]
Awesome.

This might time out, but I’m in the process of making it possible for the machine to run for significantly longer in https://github.com/openaddresses/machine/issues/298.

**Comment by porjo** [comment]
Will this addition appear on http://results.openaddresses.io/ as a matter of course, or does that need to be done manually by someone?

**Comment by migurski** [comment]
It will appear as a matter of course.

**Comment by iandees** [comment]
The dots will appear automatically on the dotmap on https://openaddresses.io, but shouldn't the coverage object in the source file here update the static PNG map at results.openaddresses.io?

**Comment by migurski** [comment]
Yes, once the batch set that started after the merging of GNAF is complete. That’s in progress here: http://results.openaddresses.io/sets/67593/

**Comment by migurski** [comment]
(they generally take the duration of each weekend, wrapping up sometime on Monday)

**Comment by mishawakerman** [comment]
// Excuse my ignorance, I'm not familiar with openaddresses and am just looking at it for an (open-source) project.

As per https://data.gov.au/dataset/ds-dga-19432f89-dc3a-4ef3-b943-5326ef1dbecc/details:

> Updated versions of the G-NAF will be published on a quarterly basis from February 2016.

Does/will openaddresses continually update this dataset or is this something that requires manual work each quarter?

**Comment by andrewharvey** [comment]
@mishawakerman As you saw I do try and update this each GNAF release, but of course there is no SLA. It's a pain doing this manually but worth the effort.

**Pull request merged**
