### PR TITLE
Luxembourg addresses

### PR DESCRIPTION
**Pull request by grischard**
I'm delighted to contribute our brand new address dataset for the whole country of Luxembourg.

### CODE REVIEW

**Comment by grischard** [comment]
Possible cause for the SSL error in the test:

https://github.com/kennethreitz/requests/issues/2022

**Comment by grischard** [comment]
cc/ @migurski could you please look into this one? Old openssl version? The link works fine in a browser.

**Comment by migurski** [comment]
I will look into it, thank you for the contribution!

**Comment by migurski** [comment]
Sorry, it’s taking a while for me to be able to look at this. I just returned from a disconnected trip, and I may be able to circle around to the SSL issue this week.

**Comment by grischard** [comment]
Ok! Let me know if there's anything I can do on the data.public.lu side.

We're also working on a way to get an URL that will always return the latest version of the data.

**Comment by sbma44** [comment]
Late to see this, but it's fantastic news -- thanks so much, @grischard! @migurski lmk if there's a way I can be helpful here.

**Comment by grischard** [comment]
@sbma44 Actually I'd love to chat about Mapbox's experience with imports of similar data to OSM, e.g. in New York. Would it please be ok to email you?

**Comment by sbma44** [comment]
@grischard by all means, though I will likely need to refer you to a colleague who is more familiar with that experience. But please don't hesitate to email me -- tlee at mapbox dot com.

**Comment by grischard** [comment]
@migurski I can't reproduce this bug with my local version of `requests` and openssl. Would it maybe be possible to try to simply update requests and openssl on the CI server?

```
import requests
resp = requests.request('GET', "https://download.data.public.lu/resources/adresses-georeferencees-bd-adresses/20160407-174800/addresses.geojson", stream=True)
print("{} addresses found".format(len(resp.json()['features'])))
```

`158370 addresses found`

**Comment by slibby** [comment]
@grischard if you'd like to try this again to see if the SSL issue is addressed, you'll have to "trick" the continuous integration check by adding a "notes" attribute or a whitespace to one of the JSON attributes.

**Comment by grischard** [comment]
Thanks @slibby, looks like @migurski hasn't had the time to look into it yet!

**Comment by migurski** [comment]
Yeah, sorry.

**Comment by grischard** [comment]
Hi @migurski, I'm just checking in to see if you know when you think you'll have a chance to look at this.

**Comment by grischard** [comment]
Hi @migurski, can I gently ask for an update on this? It's been, what, two months now.

**Comment by migurski** [comment]
Yes, thank you for that. I’m still juggling a bunch of stuff, but this issue is on my list.

**Comment by migurski** [comment]
I’ve made a change to our use of HTTPS in https://github.com/openaddresses/machine/pull/328 that I think might fix this. Can I ask you to make a small edit to the source (such as adding a line of whitespace) that will convince the queue it’s seeing something new to process?

**Comment by grischard** [comment]
Hurrah! Thank you @migurski!

**Comment by slibby** [comment]
:+1: :100:

**Comment by migurski** [comment]
Glad that worked!

**Comment by migurski** [comment]
screen shot 2016-06-07 at 10 58 11 am

**Pull request merged**
