### PR TITLE
Chechen Republic, Russia 

### PR DESCRIPTION
**Pull request by sergiyprotsiv**
This covers the majority of Chechen Republic (though not completely). From their official GIS site.
Contains five nearly identical source files for separate cities (Grozny has a regex for city since in that file if the address was in the main city the field was left blank).

### CODE REVIEW

**Comment by nvkelso** [comment]
Is this ready to merge?

**Comment by sergiyprotsiv** [comment]
I think this one is fine

**Comment by migurski** [comment]
Whoa:

**Comment by migurski** [comment]
Seeing some curious offset:

<a href="http://ec2-54-172-233-64.compute-1.amazonaws.com/150428/#lat=43.2025&lng=46.0894&z=14">screen shot 2017-01-31 at 9 48 43 am</a>

**Comment by sergiyprotsiv** [comment]
From what I saw, here the offsets appear for only one file (Kurchaloy) and it appears to be an OSM issue - comparing the data with Google Maps provides almost no offset.

**Comment by migurski** [comment]
So OSM is in the wrong place, but GMaps aerial is in the right place?

**Comment by sergiyprotsiv** [comment]
Yes, exactly, it seems that the OSM has misaligned streets there. Here is the same area vs Google Maps.
screen shot 2017-02-08 at 21 44 24

**Comment by migurski** [comment]
I'm curious if it's possible to get input from someone on the ground. OSM often warns that aerial imagery might be misaligned, and the only thing to do is show up with a GPS unit locally.

**Pull request merged**
