### PR TITLE
Mexico Countrywide

### PR DESCRIPTION
**Pull request by sergiyprotsiv**
A first attempt to load the countrywide Mexican data. Almost 30 million addresses - lets see if the machine can handle this.

I am attaching the script that relies on the JSON file linked to in https://github.com/openaddresses/openaddresses/issues/2593 to get the file names necessary for downloading. When an updated dataset is released, the INEGI website will need to be scrapped again for the file links. The updates are supposed to happen every five years (they are related to the census), but so far this is the only one I found.

The script recursively imports the shapefiles from zips and then from zips within zips, etc. The internal structure is not uniform (sometimes there is a shapefile in a folder, sometimes directly in a zip, sometimes in folder in a zip within a zip, etc). The resulting combined shapefile is 32 GB, but the csv is more manageable (1 GB compressed). I have put it on Dropbox for now, since the S3 upload limit is 256 MB. Can be split up into statewide sources if necessary.

A couple of things to note:
- The datasource as it is now only merges the data that is actually within the shapefiles. This means that the metadata on the municipality is lost (as this is only known when browsing the web). It can definitely be added as an extra column at the expense of a more processed source (and the need to process the shape data in Python instead of relying on command-line OGR). Should be straightforward, let me know if this is better.

- Houses in rural towns rarely have the house number. In the files this is denoted as "SN". My understanding is that the relevant information then is some identifier for the block the house is in, particularly the two intersecting streets (one before and one after). The data on these intersecting streets are actually in the file as well - the question is what is the best way to model it (if necessary).

### CODE REVIEW

**Comment by sergiyprotsiv** [comment]
Ok, the import succeeded, but the projection is wrong and is in fact non-standard EPSG, so the best bet would be to convert to EPSG:4326 when processing the files.

Will launch another run overnight. Any preferences on splitting by state and adding a municipality column?

**Comment by migurski** [comment]
Splitting by state might be unnecessary — Australia is another country that we have in one big pre-processed file, and it’s been fine.

**Comment by sergiyprotsiv** [comment]
Thanks! Any idea why the Travis build fails? I merged the current changes from master, and the build still does not work.

**Comment by migurski** [comment]
I’m not really sure — the error message is pretty useless. I do see that the projection is in the "src" tag, but it should actually be "srs": https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#processing-tags

**Comment by nvkelso** [comment]
Awesome!

The municipality and cross street are interesting to me.

@migurski and @iandees what's the best way to indicate the cross street (intersection) addresses?

**Comment by migurski** [comment]
I'll try to get to the bottom of the atravis check. The data looks great!

**Comment by sergiyprotsiv** [comment]
All of my recent PRs have the same issue, so it could be related to a somehow outdated fork on my side. I tried pulling everything from upstream master and pushing it into my branches, but it does not seem to work.

**Comment by migurski** [comment]
Your stuff looks up-to-date to me! I am fairly sure this is not your fault, but I don’t have an up-to-date Node environment locally that would allow me to test this. Sorry, it might take a little while.

**Comment by iandees** [comment]
The tests pass locally for me. Not sure what Travis's deal is.

**Comment by iandees** [comment]
Oh, they fail now that I merged. I must not have been on the right branch when I tested locally.

**Comment by iandees** [comment]
I am very displeased with the output of our node-based testing framework. I'm going to let this stay broken for now and rewrite our tests in Python with a test framework that gives meaningful output.

**Comment by sergiyprotsiv** [comment]
This was not quite ready to be merged though, will upload a new file with municipalities later on (and we need to figure out what to do with neighboring streets).

**Comment by iandees** [comment]
Sorry, I thought I saw you were ready. You have merge rights anyway, right? I should just let you merge when ready :-)

**Comment by sergiyprotsiv** [comment]
No worries! I also found that there were a few sources missing in the JSON, so will do a quick scrapper to download the missing file

**Comment by trescube** [comment]
Hey, now you know how I feel trying to decipher machine output when something goes wrong!  :)  I appreciate @migurski's efforts to make error messages more meaningful.  

The [schema](https://github.com/openaddresses/openaddresses/blob/master/schema/source_schema.json#L76-L78) is fairly loose with it's definition of coverage (I based it off of https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#coverage-object) and the only required field is `country`.  That error message is not helpful, that's for sure.  I fixed this in another [PR](#2725) or the error will happen anytime the machine runs a source since `npm test` validates every single source.

**Comment by trescube** [comment]
@sergiyprotsiv since you're still adding things, please note the change I made in #2725

**Pull request merged**
