### PR TITLE
updated data url

### PR DESCRIPTION
**Pull request by trescube**

### CODE REVIEW

**Comment by trescube** [comment]
Re-run this please

**Comment by trescube** [comment]
Seems to fail randomly on different chunks, the data may have to be cached.  The layer name implies that it's 3 years old and not updated so caching may be the best approach.

**Comment by iandees** [comment]
Woah.

**Comment by trescube** [comment]
There are < 5 million points in this source but there are > 10 million people in the state so there's probably still value in sourcing as many counties as possible.

**Comment by migurski** [comment]
👏🏼

**Comment by nvkelso** [comment]
Hello outer banks! Nice job!

**Pull request merged**
