### PR TITLE
Update source for us/ca/solano

### PR DESCRIPTION
**Pull request by MiniCodeMonkey**

### CODE REVIEW

**Comment by iandees** [comment]
@ingalls any idea why the CI isn't running on these?

**Comment by MiniCodeMonkey** [comment]
@iandees @ingalls I just tried forcing another CI run by adding a commit, but it still doesn't seem to be running

**Comment by iandees** [comment]
Ping @ingalls. Any ideas what's going on with CI?

**Comment by arch0345** [comment]
This has since been updated in #6293

**Comment by iandees** [comment]
Thanks

**Pull request closed without merging**
