### PR TITLE
Create Douglas County

### PR DESCRIPTION
**Pull request by mmdolbow**
Pretty sure I got this one right

### CODE REVIEW

**Comment by iandees** [comment]
Looks good, thanks!

**Comment by trescube** [comment]
The `number` and `street` fields are already split apart so you don't have to use the regexes.  The source fields are `HNUM_HALF` (there's also `HNUM` but some addresses are 1/2's) and `STREET`.

**Comment by mmdolbow** [comment]
I saw those splits, but when using their interactive map, the fields I specified were what popped up in an "Identify" window, so I thought those were more likely to be complete. For example, there are some records with additional Unit numbers in the ADDRESS line, with separate locations, like these two:
http://dc-web.co.douglas.mn.us/arcgis/rest/services/AGOL/Data_Layers/MapServer/41/2
http://dc-web.co.douglas.mn.us/arcgis/rest/services/AGOL/Data_Layers/MapServer/41/3

**Comment by trescube** [comment]
There's a separate field for `unit`that shouldn't be included in the `street` or `number` field.  Unfortunately this source doesn't separate the unit field out individually like it does for house number and street but you can use a `regexp` to extract it.  Something like this should work: `^.* #(.*)$/`.

**Comment by mmdolbow** [comment]
Thanks. Gonna do another PR to change this - looks like the "Unit" info is available in the "Location" field

**Pull request merged**
