### PR TITLE
adding Chile

### PR DESCRIPTION
**Pull request by astoff**
This is split in two shapefiles, one for Santiago metropolitan region and one for all other regions. I named the source file for the latter `other_regions.json` and put the whole country in the coverage object. Feel free to change that if needed.

The dataset website doesn't seem to contain any specific license info apart from a indemnity note, so I left that field blank in the source files.

### CODE REVIEW

**Comment by flp-gpc** [comment]
There is an issue with this archive (DIRECCIONES_CEDIZ.zip), the 2 uncompressed files (Metropolitana & Regiones) are limited to 2Gb, a lot of addresses is missing.

**Comment by astoff** [comment]
So it seems that the shapefiles are corrupted (the DBFs exceed 2GB). I sent them a message through the website form, in English, a week ago but haven't heard back. Perhaps a message in Spanish has a better chance of arriving at whoever is responsible to fix this.

**Comment by nvkelso** [comment]
The SHP opens for me on a modern 64-bit Mac in QGIS. Though it does look like there are coverage holes (see below). There are 835k records in Santiago (Metropolitan) and in the 835k in regional file. That's suspicious. I've found DBF files will shrink drastically in file size as column are removed.  Since this are near the limit, removing just a column may do the trick? 

@migurski @iandees Is machine running on 32-bit architecture (with 2 GB single file limit memory ceiling)?

**Santiago:**

screen shot 2017-02-10 at 13 51 32

**Other regions:**

screen shot 2017-02-10 at 13 53 21

**Comment by migurski** [comment]
OA is running on a 64 bit system with GDAL 2.1.0:

```
$ uname -s -r -m
Linux 3.13.0-105-generic x86_64
$ gdal-config --version 
2.1.0
```

**Comment by msirenko** [comment]
Mapbox has tried to do some further :hammer_and_wrench: work on the Shapefile, but looks like it indeed is missing data. We reached out to Humberto Toledo, who owns the data portal, to try to get a better version of the data. After a few false starts, he now understands the issue

Per conversation today with Humberto Toledo, we have 3 next steps:

1-Contact the Ministry of Economics: Humberto's team only facilitates data uploads but doesn't actually own the data, Econ Ministry they own the data we’ve been trying to get at. They are one of Chile’s most resourceful ministries and would definitely be interested in partnering with us to clean up that data.

- Jeffrey Alvarado Alvarado;	Ministerio de Economía	Asesor Unidad de Gestión Territorial - División de Tecnología y Desarrollo; 56224733792;	jalvaradoa@economia.cl
- Cristian Pizarro; Ministerio de Economía	Coordinador Unidad de Gestión Territorial - División de Tecnología y Desarrollo; 56224713823; cpizarrom@economia.cl
Caveat is that ☝️ data is old, which brings us to:

2- Contact INE (Instituto Nacional de Estadística - Ministry of Statistics): they are currently working on a brand new project to get all addresses for Chile, it’s a major overhaul of the Econ Ministry’s database. Just getting started and amazing opportunity for us to join and get access to national data.

- Claudio Yañez- INE; Coordinador Departamento de Geografía; ph #56228269645; claudio.yanez@ine.cl
- Raul Ponce- INE;	Jefe Departamento de Geografía; ph #56228269648; raul.ponce@ine.cl

Mapbox team (led by @juliannebg) will pursue these next steps

**Comment by nvkelso** [comment]
Awesome, thanks for update!

**Comment by nvkelso** [comment]
That is one enormous map preview! Nice to see Chile coming together :)

**Comment by astoff** [comment]
OK, I will let someone else do the merge, so that others get the chance to take a look and see if everything is fine.

**Pull request merged**
