### PR TITLE
Contributing to: andor-manetheren-two_rivers.json

### PR DESCRIPTION
**Pull request by ingalls**
Adding/Updating andor-manetheren-two_rivers.json

### CODE REVIEW

**Comment by ingalls** [comment]
See openaddresses/openaddresses.io#47

**Comment by ingalls** [comment]
cc/ @iandees @geobrando

**Comment by geobrando** [comment]
Looks good.  I guess my thinking it would require more thought if we were trying to form filenames that didn't require any manual adjustment from other contributors (i.e. Country ISO code+ region name).  If that's the goal, we could either use some dropdown menu or a lookup table.  Also, the current naming scheme asks for the largest extent (county OR city but not both).   But your changes should at least make it easier to rename.

**Comment by ingalls** [comment]
Yes, I'm hoping to flesh this out later today with something that will verify the fields to ensure better compliance with our coverage standards. Just wanted to get something out the door to fix this as I know how annoying its been.

**Pull request closed without merging**
