### PR TITLE
Contributing to: NewSource.json

### PR DESCRIPTION
**Pull request by schnuerle**
Adding/Updating NewSource.json

### CODE REVIEW

**Comment by iandees** [comment]
Can you rename this file `us-ky-oldham.json`. Also, the `filename` key in here shouldn't be there.

**Comment by schnuerle** [comment]
Hey  it's actually for Jefferson county, not Oldham.  Maybe I should have mentioned that.  So the json file would be named us-ky-jefferson.json.  But which file do you need renamed, the one here? ftp://ftp.lojic.org/Pub/federal/Address%20Sites.zip  

If so I can't edit that file name (it's from a city organization's system).

**Comment by iandees** [comment]
Nope, the file in your pull request. It's currently named "NewSource.json".

**Comment by iandees** [comment]
Also, if this is for Jefferson county the "coverage" object needs to be updated to reflect the correct county.

**Comment by schnuerle** [comment]
Ok I'll work on all that.  I just used an online form so there were no options on it for geoid, etc.

**Comment by geobrando** [comment]
@iandees As mentioned, these were submitted via the web map for those not comfortable working directly in the repo.  I think it's up to us to rename as we're verifying the source.

**Comment by iandees** [comment]
Ah, righto.

@ingalls: can you fix the website so it 1) creates the correct file name and 2) populates the new file with correct values?

In the mean time, I'm going to close this and copy and paste the source. @schnuerle, thanks very much for the contribution!

**Pull request closed without merging**
