### PR TITLE
Belgium license update 

### PR DESCRIPTION
**Pull request by jeffdefacto**
The data source currently lists CC-BY 4.0 for all the Belgium datasets. Updating to match.

https://opendata.bosa.be/index.nl.html

### CODE REVIEW

**Comment by jeffdefacto** [comment]
@iandees Is this the same issue blocking Norway? The build seem to be capitalizing the column name `EPSG:4326_lon` to `EPSG:4326_LON`

**Comment by iandees** [comment]
Yea, looks like it. Let me see if I can get deploys working, then I will try to fix the processing code...

**Comment by skylarmt** [comment]
@iandees Just going to leave this link here for when you get a chance to look at the processing code.  While I was reading through all the issues and PRs related to this bug, I found a commenter that seems to have found the line of code responsible.

https://github.com/openaddresses/batch-machine/issues/61#issuecomment-2453106091

**Comment by iandees** [comment]
Looks like the casing problem is fixed. Hooray!

**Pull request merged**
