### PR TITLE
Arvada, CO Updates

### PR DESCRIPTION
**Pull request by fishcharlie**
- Adding license for addresses
- Adding parcels data

#5803

### CODE REVIEW

**Comment by fishcharlie** [comment]
Not sure what I did wrong. Someone mind taking a look and advising me how to fix it?

**Comment by iandees** [comment]
It's complaining because the parcels conform object can only have "pid" attribute right now. See [the docs](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#parcel-attribute-tags) for details.

If you remove all the address-related stuff from the parcels conform it should work better.

**Comment by fishcharlie** [comment]
@iandees Awesome! Looks like that worked. Thanks so much.

**Comment by iandees** [comment]
Great! Thanks for working through this and figuring it out.

**Pull request merged**
