### PR TITLE
Update us-mn-hennepin.json

### PR DESCRIPTION
**Pull request by geospatialem**
Updated Hennepin County, Minnesota by adding notes/metadata resources and changing the associated fields (lon, lat, street, postcode).

### CODE REVIEW

**Comment by iandees** [comment]
Hi Kitty! Thanks for the update to the source for my favorite county in the US :smile:. The build failed because there's no comma at the end of the "metadata" line. Try fixing that and see if it makes the build go green.

**Comment by geospatialem** [comment]
I'm not sure why the build is still failing.. any ideas, @iandees?

**Comment by iandees** [comment]
I don't think it likes the `notes` field. Can you put all that stuff in a single string instead of an object?

**Comment by geospatialem** [comment]
Sorry about the long commit trail, @iandees. 

I'm wondering if we can create another readme file that can help describe the field names that are supported. It took me a while to get the process down *(sorry about that)* but it may be beneficial for others as well. What do you think?

**Comment by iandees** [comment]
The fields are described in [CONTRIBUTING.md](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#optional-tags), which isn't particularly obvious. It would make sense to point to it from the readme.

**Pull request merged**
