### PR TITLE
Contributing to: it-taa-rovereto.json

### PR DESCRIPTION
**Pull request by napo**
Adding/Updating it-taa-rovereto.json

### CODE REVIEW

**Comment by migurski** [comment]
Thank you @napo! The data [doesn’t look to contain street names](http://data.openaddresses.io.s3.amazonaws.com/runs/5544/sample.json) —is it valid address data?

**Comment by migurski** [comment]
Duplicate of #1106.

**Comment by napo** [comment]
@migurski you are right.
The dataset of Rovereto contains only the id of the street names, if you want have the complete dataset, you have to join the other table.
http://www2.comune.rovereto.tn.it/servizionline/extra/opendata/Strade.zip

The dataset of Trento is nice but, there is a problem:
you need to filter the data because the dataset contains each place where is a label with the address number. This means that, in some buildings, there are more as one label. Eg. a label on the main entrance, another on the gate or the secondary entrance.

**Comment by geobrando** [comment]
Hello @napo. Thanks for the contribution.  Since the data from both sources need processing before they can be included, I'm closing #1106.  OA would certainly appreciate any effort to process these.  OA could host the files that you produce, or you could host them somewhere and script updates as offered. 

[Machine](https://github.com/openaddresses/machine) is currently able to perform tasks such as joining/splitting fields, generating polygon centroids, and srs transformations.  In my personal opinion, it would be useful to add functionality to machine and the source schema expanded to allow joins between multiple data files, filtering, etc.  But I don't see that becoming a reality any time soon.  You'll see others raising a need for this [here](https://github.com/openaddresses/openaddresses/issues/735) and [here](https://github.com/openaddresses/openaddresses/issues/177).

If you plan to submit new sources, please check out the new [CONTRIBUTING.md](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md) as there have been some changes to the source JSON schema, filename convention, and the folder structure.

**Pull request closed without merging**
