### PR TITLE
Update Australia for May 2017

### LINKED ISSUE #1701: au-countrywide quarterly update needs reprocessing
As per https://github.com/openaddresses/openaddresses/blob/master/sources/au/countrywide.json the source must be regenerated now that there is a May release of http://data.gov.au/dataset/geocoded-national-address-file-g-naf

`http://s3.amazonaws.com/data.openaddresses.io/cache/au.zip` still shows `Last-Modified: Sat, 05 Mar 2016`

### PR DESCRIPTION
**Pull request by migurski**
Still need to run this on a higher-memory instance. Closes #1701.

### CODE REVIEW

**Comment by migurski** [comment]
That took a weirdly-long time and emitted a complaint about PostGIS 2.3. I might have some further updates to make to the Dockerfile for this to work.

**Comment by ingalls** [comment]
@migurski this good to go in?

**Comment by andrewharvey** [comment]
FYI The newer Aug 17 update is released now.

**Comment by migurski** [comment]
Great, thanks. I never returned to the May file to make it work; there were some changes along the way that required additional effort to make work. Hopefully I can get these done for the August file.

**Comment by andrewharvey** [comment]
August file out out now!

https://data.gov.au/dataset/geocoded-national-address-file-g-naf

**Comment by andrewharvey** [comment]
> That took a weirdly-long time and emitted a complaint about PostGIS 2.3. I might have some further updates to make to the Dockerfile for this to work.

Were you using PostGIS 2.3? I see ubuntu:17.04 has postgis 2.3 and upstream uses postgis 2.3 so probably best if we update the docker file to use that.

> Great, thanks. I never returned to the May file to make it work; there were some changes along the way that required additional effort to make work. Hopefully I can get these done for the August file.

Let me know if you need a hand, otherwise I'll leave this one with you.

**Comment by tastrax** [comment]
Hi folks, I just noticed the number of addresses has not increased for some time despite the August update. Is the latest update actually the latest or is it just a glitch in the numbers being recorded to the website?

**Comment by andrewharvey** [comment]
@tastrax this PR isn't merged, so what's currently in OA is the Feb 17 release as per https://github.com/openaddresses/openaddresses/blob/master/sources/au/countrywide.json

**Comment by andrewharvey** [comment]
I'm updating this PR for Aug 17.

**Comment by andrewharvey** [comment]
hi @migurski , thanks for working on this, I've taken the work you did here and built upon it over at https://github.com/openaddresses/openaddresses/pull/3413. I'll wait for the CI check to finish, but it looks okay to me!

So we just need to copy the files I'm hosting to the OA s3 cache.

**Comment by migurski** [comment]
Awesome @andrewharvey! I'll check out that PR in a bit, but on first glance it looks solid. If you'd like to upload the zip file to our S3 bucket now, I have added you to our Github org so you can use this: http://results.openaddresses.io/upload-cache

**Comment by andrewharvey** [comment]
@migurski Thank you! But I'm not sure about granting that app access to "read and write all user data. This includes the following: Private email addresses, Private profile information, Followers" and "read and write all public repository data" as I mentioned in https://github.com/openaddresses/openaddresses/pull/3173#discussion_r134915137.

Is there another way I can run `aws s3 sync --acl public-read /tmp/work/cache s3://data.openaddresses.io/cache` as mentioned in https://github.com/openaddresses/openaddresses/tree/master/scripts/au#using-docker?

**Comment by migurski** [comment]
Sadly, that's the baseline scope for Github. Would it help to know that you [can revoke access](https://github.com/settings/applications?o=used-desc) immediately after granting and using it? @iandees would have more information on whether there's another way.

**Comment by andrewharvey** [comment]
@migurski Sorry for being so difficult! Could you grant access to this new GH account I opened for this https://github.com/andrewharvey-openaddr ? Then I can just use that to upload to the cache. Cheers.

**Comment by migurski** [comment]
No problem, sorry for the hassle on our end as well! I have invited your new account.

**Comment by andrewharvey** [comment]
I've pushed the file to the cache and updated the source, over at https://github.com/openaddresses/openaddresses/pull/3413 just waiting on CI. Now that I've pushed files to the cache, next question is how do I delete them when we move to the next quarter release? Or are you happy to have these files accumulate?

**Comment by migurski** [comment]
I haven't been deleting past files. We use so much S3 and it's not costing us a ton, so I'm okay with having these accumulate.

**Pull request merged**
