### PR TITLE
Savsjö, Sweden

### PR DESCRIPTION
**Pull request by sergiyprotsiv**
Savsjö municipality, Sweden. This looks like a distant suburb of what you thought was remote. Cannot check the rest responses myself (QGIS cannot display results), but it is sufficiently similar to the previous sources that I think this should be fine.

### CODE REVIEW

**Comment by sergiyprotsiv** [comment]
Looks like an issue with ESRI downloader. Doing it via the web interface to the server works fine.

**Comment by iandees** [comment]
Curious: I thought all Esri layers had to have an ID column. This is the first one I've seen that doesn't.

This will need some work in `machine` to support this.

**Comment by slibby** [comment]
@iandees it's a broken service, it's really an fluke that it's even able to "appear" published as we do always (apparently not) require an ID field. [Basic queries at REST](http://giswww.savsjo.se/arcgis/rest/services/Savman/SavmanBakgrund/MapServer/3/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&f=html) do work,  but I'm not sure there's any way to have `machine` programatically go through 1000 rows at a time if there's no logical offset with `id`

**Comment by sergiyprotsiv** [comment]
Is it maybe possible to set the "order by" clause to order by for example "XKOORD, YKOORD"? If not, I can probably do this manually and cache it.

**Comment by iandees** [comment]
It looks like the `FNR` column is an ID-like thing that we could de-dupe on. It's just not specified as the Esri ID type so `machine` doesn't use it.

**Comment by sergiyprotsiv** [comment]
I tried ordering by FNR and got duplicates. I think FNR is a parcel ID, which I can imagine host multiple addresses, though I did not check

**Pull request merged**
