### PR TITLE
Update ch/countrywide.json --> Correct the x and y

### PR DESCRIPTION
**Pull request by gismountains**

### CODE REVIEW

**Comment by gismountains** [comment]
Incorreect -->
image

**Comment by andrewharvey** [comment]
hi I'm not sure what's going on here, when I open the CSV in QGIS with EPSG:2056 and use the original/current fields

"lon": "GKODE",
"lat": "GKODN",

It correctly positions in CH. Don't know if there is an issue somewhere else in the OA processing code either because the data bot preview doesn't look right with your change either.

:shrug:

**Comment by iandees** [comment]
I think this is a bug in batch: https://github.com/openaddresses/batch/issues/90

**Comment by iandees** [comment]
I'm going to close this as the lat/lon columns seem to be picked correctly in the source.

**Pull request closed without merging**
