### PR TITLE
Update Norway countrywide source

### LINKED ISSUE #7270: Norway country-wide addresses source is invalid
Correct open address path: [https://kartkatalog.geonorge.no/metadata/matrikkelen-adresse-leilighetsnivaa/365b0591-b536-42a6-a20d-22e404fbfe55?search=address](https://kartkatalog.geonorge.no/metadata/matrikkelen-adresse-leilighetsnivaa/365b0591-b536-42a6-a20d-22e404fbfe55?search=address)
While you are at it, map _kommunavn_ to _city_

### PR DESCRIPTION
**Pull request by arch0345**
Closes #7270

### CODE REVIEW

**Comment by jwass** [comment]
Over on #7270 @iandees thought URLs like these will expire eventually. Is there a way to ensure the URL here is stable?

**Comment by iandees** [comment]
Looks like we're getting bitten by a `KeyError` here again. Something in our pipeline is upper-casing CSV row names. Last time I looked at this I couldn't figure out where/why we're doing this. It involves a change to the `batch-machine` code, I think.

**Comment by eisams** [comment]
City is not "kommunenavn" but "poststed". The municipiality name is not used in Norwegian addresses

**Comment by iandees** [comment]
This finally finished downloading and processing. I don't see any sort of street name in the output, though. Is there a better column to pick for that?

**Comment by iandees** [comment]
Well we'll go with this for now and see if anyone can find more street names.

**Pull request merged**
