### PR TITLE
mass conversion to regexp instead of split/auto_number/auto_street

### PR DESCRIPTION
**Pull request by stephenkhess**
maintains 4 space indentations
changes limited to lines affected
maintains newline at EOF

### CODE REVIEW

**Comment by migurski** [comment]
Awesome! The machine will be chewing on this for a while…

**Comment by stephenkhess** [comment]
Darn, I'll get these errors fixed up today or tomorrow

**Comment by stephenkhess** [comment]
Huzzah!

**Comment by iandees** [comment]
Nice, thanks!

**Pull request merged**
