### PR TITLE
swap au/vic/statewide to gdb source

### PR DESCRIPTION
**Pull request by andrewharvey**

### CODE REVIEW

**Comment by ingalls** [comment]
I don't know why this one didn't finish processing, going to try bumping it again before I spend a bunch of time digging in

**Comment by andrewharvey** [comment]
@ingalls I can't see anything in the log that indicates a problem, just seems to stall.

**Comment by andrewharvey** [comment]
Opened #6909 to try and address the check failure

**Comment by andrewharvey** [comment]
data-pls passed now, just need to get in the run-source fix and I think this one is good to go.

**Comment by andrewharvey** [comment]
Thanks @iandees

**Pull request merged**
