### PR TITLE
Removing canton abbreviation suffixes from Swiss cities

### PR DESCRIPTION
**Pull request by thatdatabaseguy**
See #2290

### CODE REVIEW

**Comment by thatdatabaseguy** [comment]
Re-run this please

**Comment by thatdatabaseguy** [comment]
Yep @trescube that worked. Error wasn't entirely clear, but may have to do with different regex flavors in Javascript vs. Python.

So this commit also changes validation of the regex field to "string" instead of "regex". The webhook would still fail quickly if the regex doesn't compile on the Python side.

**Comment by thatdatabaseguy** [comment]
This should also fix #2311.

Any objections?

**Comment by trescube** [comment]
Nope, merge away!

**Pull request merged**
