### PR TITLE
Update west_parry_sound_district.json

### PR DESCRIPTION
**Pull request by KHobbs3**
Added license information.

Closes: https://github.com/openaddresses/openaddresses/pull/5290
Closes: https://github.com/openaddresses/openaddresses/pull/5289

### CODE REVIEW

**Comment by iandees** [comment]
Looks like a dupe PR?

**Comment by ingalls** [comment]
This was the only one passing circle - so I think it's the canonical

**Comment by JosephKuchar** [comment]
> Looks like a dupe PR?

My bad - I gave @KHobbs3 a quick demo this morning to update the JSONs, but it had been a while so I forgot that using "back" to fix mistakes is a bad idea that results in duplicate PRs. Sorry about that!

**Comment by ingalls** [comment]
This has been merged in another branch - no changes on this branch

**Pull request closed without merging**
