### PR TITLE
updated data url and conform

### PR DESCRIPTION
**Pull request by trescube**

### CODE REVIEW

**Comment by nvkelso** [comment]
Beautiful :)

On Wed, Apr 19, 2017 at 8:48 AM, OpenAddresses Bot <notifications@github.com

**Comment by migurski** [comment]
This ran with short-lived machine code 4.10.0 with a slippymap bug; retry with newer to see if https://github.com/openaddresses/machine/issues/610 is a problem:

Re-run this please.

**Comment by trescube** [comment]
Thanks, @migurski !

**Comment by migurski** [comment]
Yup, sorry this happened! 

By the way: the double previews over the past few days are because I'm quietly testing a Docker-driven worker with a duplicate task queue.

**Pull request merged**
