### PR TITLE
New Caledonia countrywide

### PR DESCRIPTION
**Pull request by sergiyprotsiv**
This is the source listed in https://github.com/openaddresses/openaddresses/issues/2928

The server is a bit unstable, but let's see if the machine can pull everything out.

### CODE REVIEW

**Comment by migurski** [comment]
Grump, “504 Gateway Time-out”.

**Comment by migurski** [comment]
Re-run this please.

**Comment by migurski** [comment]
Testing a thing with Machine:

Re-run this, please.

**Comment by sergiyprotsiv** [comment]
Re-run this, please.

**Comment by trescube** [comment]
Managed to grab with pyesridump so trying this again...

Re-run this, please.

**Comment by trescube** [comment]
`NUM_GRAF` appears to be number (`NUMERO`) and unit (`COMP_NUM`) combined, though I may be wrong on this.  In some instances, `NUM_GRAF` is `0` while `NUMERO` is non-zero and the same value as in the full address field `TXT_RECHERCHE`.

**Comment by trescube** [comment]
Since the source is unreliable, I uploaded the pyesridump to https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/trescube/852a94/new-caledonia.geojson.zip

**Comment by nvkelso** [comment]
Just area around capital, but excellent to include :)

**Comment by sergiyprotsiv** [comment]
Seems to pull fine straight from the website, merging with the original ESRI server as source

**Pull request merged**
