### PR TITLE
Add makeloveland florida data

### PR DESCRIPTION
**Pull request by ingalls**
Adds parcel centroids for florida.

### CODE REVIEW

**Comment by ingalls** [comment]
fl

**Comment by ingalls** [comment]
wow

**Comment by ingalls** [comment]
build

**Comment by ingalls** [comment]
^^ A few screenshots from QGIS.

**Comment by ingalls** [comment]
cc/ @migurski @iandees @sbma44

**Comment by sbma44** [comment]
:tada:

**Comment by iandees** [comment]
While this is really awesome and I am super duper happy to be working with @dexterslu and company (and thanks for doing the conversion, @ingalls), I would love to figure out a way to get the raw data direct from the source so we can continue saying that we are a collection of primary data sources.

Just something to think about. I love having more addresses!

**Comment by ingalls** [comment]
@iandees I have a list of ESRI endpoints which @dexterslu was kind enough to provide which cover much of the area as well. I'll be adding those in the next few days

**Comment by dexterslu** [comment]
@iandees definitely understand and appreciate that. all of the data is available through the [florida department of revenue](http://dor.myflorida.com/dor/property/resources/data.html) the data comes in two separate files, one is simply the parcel geometry with APN and the other is a tax roll.

**Comment by iandees** [comment]
Sweet, thanks @ingalls and @dexterslu!

**Pull request merged**
