### PR TITLE
Add a source for Texas statewide

### PR DESCRIPTION
**Pull request by iandees**
Fixes https://github.com/openaddresses/openaddresses/issues/2179

### CODE REVIEW

**Comment by migurski** [comment]
Nice. I’m going to add a footprint polygon for this, based on a list of included counties.

**Comment by migurski** [comment]
Does this look right? 

screen shot 2016-11-30 at 8 42 54 pm

**Comment by migurski** [comment]
Also, we'll need a website property here to be able to track this later, since we're hosting a cached version ourselves.

**Comment by nvkelso** [comment]
@migurski I've noted **7 counties to remove** from the Texas footprint in the GIF below. The blue ? turns out to be  a military base that spans multiple counties so that's why there's a weird hole there (no change in footprint proposed there). The projections aren't quite the same between the images, but close enough.

texas_footprint

**Comment by migurski** [comment]
Thanks, here's a new one:

screen shot 2016-12-01 at 5 16 41 pm

**Pull request merged**
