### PR TITLE
added city of Kharkiv, Ukraine

### LINKED ISSUE #2176: Kharkiv Ukraine
http://cdr.citynet.kharkov.ua/arcgis/rest/services/gis_ort_stat_general/MapServer/1

I tried to quick pull some down and verify - looks like points plot, but didn't want to come in WGS84 - just a fyi

### PR DESCRIPTION
**Pull request by trescube**
Fixes #2176

### CODE REVIEW

**Comment by sergiyprotsiv** [comment]
Hi,
In my test last week there was an issue with Kharkiv. Basically the coordinate system it seems to be following is wrong and in my tests Kharkiv ended up deep inside Kenya. Could you check if this happens for you too? I am pretty sure it is using one of the Pulkovo projections, but the offsets from origin are clearly wrong.
Sergiy

**Comment by trescube** [comment]
Records still appear to be landing in Kenya.  We'll investigate.

**Comment by migurski** [comment]
Yeah that preview map should be a tip-off.

**Comment by trescube** [comment]
Oh yeah, good point.  I see a lot of dots and assume that it's correct.

**Pull request merged**
