### PR TITLE
WIP: Broward County, FL, USA: updated data url and conform

### PR DESCRIPTION
**Pull request by trescube**
Don't merge, source was broken but Arcgis source contains far fewer points than the shapefile.

### CODE REVIEW

**Comment by albarrentine** [comment]
Hm, this source only has 481k addresses vs. the shapefile which has 713k.

**Comment by trescube** [comment]
Weird, showed up in new data, figured it was more up-to-date.  Source was broken anyway, I'll try the relocated shapefile.

**Comment by albarrentine** [comment]
And it seems like the cities may not be distributed by the population.

The first source has almost 90k addresses in Ft Lauderdale vs. 39k in this one.

**Comment by albarrentine** [comment]
@trescube hm, that is weird, it looks like it should in theory be more up-to-date. It just seems like it's missing data. The top city in this is Davie which is definitely smaller than Ft. Lauderdale.

**Comment by trescube** [comment]
Relocated zip file is here but it's stalling out when downloading:  https://bcgis.broward.org/GISData.htm

**Comment by albarrentine** [comment]
Hm, same. Maybe we should cache it, or just retry the source until it finishes. Might help to try downloading at night when people are out of the office.

**Comment by trescube** [comment]
New .zip file contains 477,759 records.

**Comment by albarrentine** [comment]
Hm, how's the city distribution look? `awk -F',' '{ print $6 }' broward.csv | sort | uniq -c | sort -nr` is what I used.

**Comment by trescube** [comment]
csv wasn't behaving so I exported to sqlite:

```
|city name|count|
|DAVIE|49002|
|PEMBROKE PINES|39740|
|FORT LAUDERDALE|39405|
|LAUDERHILL|35037|
|DEERFIELD BEACH|32306|
|HOLLYWOOD|31093|
|MIRAMAR|30131|
|CORAL SPRINGS|25668|
|PLANTATION|20809|
|SUNRISE|19664|
|POMPANO BEACH|18504|
|MARGATE|17993|
|WESTON|17731|
|TAMARAC|16336|
|COOPER CITY|11305|
|PARKLAND|10771|
|COCONUT CREEK|9474|
|OAKLAND PARK|9244|
|NORTH LAUDERDALE|8811|
|DANIA BEACH|6725|
|WEST PARK|4906|
|LAUDERDALE LAKES|4378|
|WILTON MANORS|4169|
|LIGHTHOUSE POINT|3484|
|HALLANDALE BEACH|2839|
|PEMBROKE PARK|2802|
|SOUTHWEST RANCHES|2403|
|LAUDERDALE BY THE SEA|1415|
|DR|1157|
|SEA RANCH LAKES|238|
|HILLSBORO BEACH|200|
|LAZY LAKE|17|
|HALANDALE BEACH|2|
```

**Comment by stefanb** [comment]
See #3969 for alternative solution with just fixing the URL, without needing to adjust conform object.

**Comment by stefanb** [comment]
Does it look feasable to migrate to esri data source or should we just update the URL of the CSV as is working fine in #3969 ?

**Comment by stefanb** [comment]
FYI, a simpler fix with just the URL change was merged into master branch in #3969.

**Comment by arch0345** [comment]
Source has since been updated in #6490

**Pull request closed without merging**
