### PR TITLE
Add Tulsa county, OK

### LINKED ISSUE #2005: Add addresses in Tulsa, OK
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

### PR DESCRIPTION
**Pull request by iandees**
Fixes #2005

### CODE REVIEW

**Comment by iandees** [comment]
Bah humbug. The polygon data in the WKT field is too long for the Python CSV implementation 😦 .

**Comment by davidchiles** [comment]
Is this the same issue happening in https://github.com/openaddresses/openaddresses/pull/2093?

**Comment by iandees** [comment]
@davidchiles yep, looks like it.

**Comment by migurski** [comment]
I had no idea there was a limit; maybe CSV is not the best format for storing cached data.

**Comment by migurski** [comment]
Re-run this, please.

**Comment by migurski** [comment]
Tulsa

**Pull request merged**
