### PR TITLE
Bangkok, Thailand

### PR DESCRIPTION
**Pull request by sergiyprotsiv**
House number only source from the city of Bangkok's ESRI server (https://github.com/openaddresses/openaddresses/issues/2440). No license info.

### CODE REVIEW

**Comment by nvkelso** [comment]
Dense!

**Comment by slibby** [comment]
I _think_ that the Travis build is failing from a missing `street` in the conform object, which I believe is a requirement. @migurski can you validate that? The Travis failure log is pretty obscure

**Comment by migurski** [comment]
Yuck, yeah, that is super obscure. A missing "street" is a problem though!

**Comment by sergiyprotsiv** [comment]
Yeah, the missing street discussion was started here: https://github.com/openaddresses/openaddresses/issues/2440
Basically, it could be fine for Pelias, but not necessarily for other users.

**Comment by iandees** [comment]
I'm going to close this for now. I think the next step here if someone wants to take it is to build a script that joins with the centerlines layer in the same map service.

**Pull request closed without merging**
