### PR TITLE
Add additional fallback city option for Yukon

### PR DESCRIPTION
**Pull request by jeffdefacto**
Adds additional city name option for places without city or unincorporated name

### CODE REVIEW

**Comment by jeffdefacto** [comment]
@iandees Any idea why `first_non_empty` would be causing this failure?

**Comment by iandees** [comment]
The error is

```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/openaddr/__init__.py", line 139, in conform
    out_path, feat_count = task4.convert(source_config, decompressed_paths, workdir)
  File "/usr/lib/python3.10/site-packages/openaddr/conform.py", line 416, in convert
    rc = conform_cli(source_config, source_path, dest_path)
  File "/usr/lib/python3.10/site-packages/openaddr/conform.py", line 1155, in conform_cli
    transform_to_out_geojson(source_config, extract_path, dest_path)
  File "/usr/lib/python3.10/site-packages/openaddr/conform.py", line 1132, in transform_to_out_geojson
    out_row = row_transform_and_convert(source_config, extract_row)
  File "/usr/lib/python3.10/site-packages/openaddr/conform.py", line 856, in row_transform_and_convert
    feat = row_convert_to_out(source_config, row)
  File "/usr/lib/python3.10/site-packages/openaddr/conform.py", line 1082, in row_convert_to_out
    output["properties"][field] = row.get(cfield)
TypeError: unhashable type: 'dict'
```

I think the `field` variable is a `dict` in this case. I wonder if this function ever worked...

**Comment by iandees** [comment]
Solved the bug 🎉

**Comment by jeffdefacto** [comment]
Awesome!

**Pull request merged**
