### PR TITLE
Belarus countrywide

### PR DESCRIPTION
**Pull request by sergiyprotsiv**
A conform to import the source for Belarus discussed in https://github.com/openaddresses/openaddresses/issues/3404.

@thatdatabaseguy, could you please check the preferred format for addresses. Specifically, whether we should have "korpus" as part of the house number or as a unit.

Some fields in the input csv were obviously created as numeric, might need a regex on them to remove decimals and replace zeroes with nulls.

### CODE REVIEW

**Comment by thatdatabaseguy** [comment]
It covers Minsk! Thanks @sergiyprotsiv

Format looks fine. Both fields being floats/decimals in the source means either some preprocessing or some postprocessing - I'm fine with the latter. Since there's no other unit field, it should be OK to stick the building field under unit.

**Comment by nvkelso** [comment]
Looks like nearly 100% coverage!

**Comment by sergiyprotsiv** [comment]
Thanks to @justinelliotmeyers ! The only issue is that we now have houses like 1.00000000000Б, i.e. the letter is appended to the string representing the floating point number. Is there any simple way to deal with it in the conform? Otherwise I'll just reprocess the input csv to remove the floats.

**Comment by thatdatabaseguy** [comment]
I added a pull request https://github.com/openaddresses/machine/pull/670 for stripping multiple trailing zeroes, but for some reason my PRs to machine are not triggering a build.

@sergiyprotsiv might want to preprocess it for the moment if it's not too much trouble.

**Pull request merged**
