### PR TITLE
Medellín, Colombia

### PR DESCRIPTION
**Pull request by astoff**
This source contains a field called `INTERIOR` which I believe should be mappedto unit, but I am not sure.  Also, the house number field (`PLACA`) includes the contents of the `INTERIOR` field at the end, inside parentheses, so it should probably be regexed away.

The website mentioned in the source has an "open data" section, but it does not seem to specify the terms of use.  Moreover, I am not sure this source can actually be directly accessed from that section of the website.

### CODE REVIEW

**Comment by thatdatabaseguy** [comment]
Re-run this, please

**Comment by thatdatabaseguy** [comment]
Re-run this, please.

**Comment by thatdatabaseguy** [comment]
Re-run this, please

**Comment by astoff** [comment]
Re-run this, please

**Comment by thatdatabaseguy** [comment]
Ugh, this server is really flaky.

Re-run this please.

**Pull request merged**
