### PR TITLE
Taiwan - Yilan

### PR DESCRIPTION
**Pull request by sergiyprotsiv**
This source contains one file per township (covering the whole province), since the countywide address layer has a weird crop.

What's the best way to do coverage objects? So far I have put the whole county into each file, but I think the correct way would be to put in the polygons for the township, right?

### CODE REVIEW

**Comment by sergiyprotsiv** [comment]
Is there a simple way to combine "remove_prefix" and "regex" functions? Need to remove the road name from the beginning of the address before doing the parsing.

**Comment by migurski** [comment]
Testing a new version of Machine:

Re-run this, please.

**Comment by sergiyprotsiv** [comment]
@thatdatabaseguy When you have time, can you take a look at the regex for this source? Basically, I want to do the same splitting of house number and unit as in other Taiwanese sources, but before that to remove the street name from the address. If there a simple way to combine "remove_prefix" and "regex" functions, would be simple. From what I understand, we can't use functions of functions, right?

**Comment by andrewharvey** [comment]
Closes #3503

**Pull request merged**
