### PR TITLE
Fixed conform tags in Poland

### PR DESCRIPTION
**Pull request by migurski**
Removed incorrect field merge and added postcode, region, and city tags.

### CODE REVIEW

**Comment by sbma44** [comment]
@migurski my recollection is that the merge was there because a substantial portion of the database does't have a street address. merging the village name into that field seemed to be the best way to produce useful geocoding behavior.

**Comment by migurski** [comment]
Huh, okay. If we’re producing output with city fields, would that be enough?

**Comment by migurski** [comment]
We’re pretty close to final output with city names, so I’m going to go ahead and let this through.

**Comment by sbma44** [comment]
sounds good. I'm facing a similar situation with the Czech address set right now. Plenty of municipalities without street names.

**Pull request merged**
