### PR TITLE
skip us-mn-scott, add kandiyohi

### PR DESCRIPTION
**Pull request by mmdolbow**
Looks like we might need to wait a bit for this one to settle. There is a new "OpenData" folder on the root of the endpoint, which is encouraging.

### CODE REVIEW

**Comment by mmdolbow** [comment]
The scott file has failed, which is why I want to skip it. What do I need to do to make this pull request happier?

**Comment by iandees** [comment]
Get one of us to merge it :smile:. Thanks! Hopefully we can get Scott County back.

**Comment by iandees** [comment]
Looks like they've moved their stuff behind a proxy:

http://gis.co.scott.mn.us/Proxy/proxy.ashx?http://gis.co.scott.mn.us/scgis/rest/services/Property_Info/PUBLIC_PARCEL_APP_RW/MapServer/25

The proxy uses some ESRI API token to gain access to the backing ESRI endpoint. I don't think our code will handle that as-is.

**Comment by mmdolbow** [comment]
There is a lot of peer pressure in the metro to open up the data, and I hopefully will hear about it if it happens. Thanks.

**Comment by mmdolbow** [comment]
Yes, the proxy establishes a login, and once you have a session open you can view the REST endpoint. But that session expires and then you're toast. However, still holding out hope that "OpenData" folder might have a service in it someday.

**Pull request merged**
