### PR TITLE
Add us/mo/bates.json

### PR DESCRIPTION
**Pull request by slibby**

### CODE REVIEW

**Comment by slibby** [comment]
@justinelliotmeyers here's the PR I created from that sample data (with a few typos in the commits for fun!)

**Comment by iandees** [comment]
👏 

Thanks for putting this together @slibby and @justinelliotmeyers.

I just put the Dropbox file in our S3 bucket:
http://data.openaddresses.io.s3.amazonaws.com/cache/us/mo/bates.zip

**Comment by iandees** [comment]
...and then updated the source to point to the new URL.

**Comment by migurski** [comment]
Maybe time to add S3 cache upload to Machine so this is easier?

**Comment by iandees** [comment]
I think pointing to existing docs for `awscli` or `s3cmd` or `Transmit.app` would be better than building it into machine.

**Comment by migurski** [comment]
In machine it'd be possible to rely on Github org membership auth rather than distributing AWS keys & secrets, though.

**Comment by iandees** [comment]
Huh, interesting. Let's move that convo to a new ticket.

**Pull request merged**
