### PR TITLE
Contributing to: united_states-tx-new braunfels.json

### PR DESCRIPTION
**Pull request by bmoregeo**
Adding/Updating united_states-tx-new braunfels.json

### CODE REVIEW

**Comment by iandees** [comment]
Thanks for this! It looks like you used our online tool to submit this change. Are you comfortable with renaming the file to `us-tx-new_braufels.json`?

**Comment by bmoregeo** [comment]
Yeah that sounds great.  

sorry for all of the dupes. The UI said *ready for review* but still showed the form I wasn't sure if it meant I needed to review or someone else was going to review.

**Comment by iandees** [comment]
Ah, thanks for the feedback. I'll see what we can do to make that better/more intuitive.

**Comment by migurski** [comment]
I’ll add a _conform_ based on the sample.

**Comment by migurski** [comment]
@bmoregeo, I made some updates in https://github.com/openaddresses/openaddresses/commits/bmoregeo-1436534402756. Can you incorporate them into your PR?

**Comment by geobrando** [comment]
Currently In sources 

https://github.com/openaddresses/openaddresses/blob/0b82da51590d4a99911716ba1fb37da1db145687/sources/us/tx/new_braunfels.json

**Pull request closed without merging**
