### PR TITLE
Add Grand Forks county, ND

### LINKED ISSUE #2181: Grand Forks, ND
gfgis_nd

http://opendata.arcgis.com/datasets/b44652e9403344a0b49316d0d7e1e20f_0?geometry=-98.809%2C47.638%2C-95.104%2C48.282

### PR DESCRIPTION
**Pull request by iandees**
Fixes #2181.

This data source has a whole lot more columns but they aren't filled in :(.

### CODE REVIEW

**Comment by trescube** [comment]
I've been trying to sort this one out in #2195,  the regexes are a pain.

**Comment by iandees** [comment]
Alritey, I'll close this one out then.

**Comment by trescube** [comment]
Well, how did you make out? If your PR covers it, then let's go with that.

**Comment by iandees** [comment]
Not so well. The sample shows that I screwed up the street regex.

**Pull request closed without merging**
