### PR TITLE
Move source files into subdirectories to make navigating easier

### PR DESCRIPTION
**Pull request by iandees**

### CODE REVIEW

**Comment by migurski** [comment]
CI did not run on this pull request because the server timed out, I guess because it’s so enormous?

**Comment by migurski** [comment]
Also I see you’re preserving the country code prefixes on the file names, i.e. `xx/xx-region.json`. The France files should be renamed to look like this, too.

**Comment by ingalls** [comment]
Would you both be open for discussion for following the france example and dropping the county code? This seems redundant as it is in the file structure and the `coverage` object of the source.

**Comment by migurski** [comment]
I’m open to that as well.

**Comment by ingalls** [comment]
Also @iandees you'll need to update the node tests to recognize sub-directories. As it stands this change is not actually being tested by travis.

**Comment by iandees** [comment]
Seems fine to me. I can adjust the PR this afternoon.

**Comment by migurski** [comment]
Is this a rationale for using Python in the unit tests?

**Comment by iandees** [comment]
I'm going to close and delete this branch so I can re-do it from master in one commit rather than bounce all over the place.

**Pull request closed without merging**
