### PR TITLE
fixing Berlin, Germany

### PR DESCRIPTION
**Pull request by ubahnverleih**

### CODE REVIEW

**Comment by ubahnverleih** [comment]
hm the test failed. I guess the problem is, that i tried to fix the coordinates with regex (replacing ',' with '.')

**Comment by iandees** [comment]
Yep, the `lat` and `lon` attributes in the `conform` object don't support the regex stuff that other fields support.

**Comment by iandees** [comment]
But there's no great reason they couldn't... any thoughts @migurski?

**Comment by NelsonMinar** [comment]
That regex looks complicated. How about just having the conform parser accept comma in lat/lon columns instead of point? I'm surprised this hasn't come up before!

**Comment by migurski** [comment]
Huh, yeah. It’d be nice for the regexep to work, and it would also be nice for the commas to work.

**Comment by ubahnverleih** [comment]
I'm not sure why this test failed. Output looks OK for me. Any idea?

**Comment by iandees** [comment]
Looks like the excerpting process failed, @migurski. I'll merge this in anyway.

**Pull request merged**
