### PR TITLE
Added us/ca/tulare

### PR DESCRIPTION
**Pull request by davidchiles**

### CODE REVIEW

**Comment by migurski** [comment]
Seemingly no geometry in this source?

**Comment by davidchiles** [comment]
There is a `MM_XDDLONG` & `MM_YDDLATI` field. I'll fix it up.

**Comment by davidchiles** [comment]
Oh I guess `lat` & `lon` can only be set on csv type.

**Comment by davidchiles** [comment]
Actually looks like this is the better endpoint 

https://gis.tularecounty.ca.gov:6443/arcgis/rest/services/Public/Address_points/MapServer/0

**Comment by davidchiles** [comment]
@migurski Is there a way to run [machine](https://github.com/openaddresses/machine) locally so I can try a figure out what's going on here?

**Comment by migurski** [comment]
There is! What's your comfort level with Python code? This doc will help you install it locally, at which point you can run `openaddr-process-one` to give it a run: https://github.com/openaddresses/machine/blob/master/docs/install.md

**Comment by davidchiles** [comment]
@migurski Thanks for you help. I was able to get machine setup in a VM. It helped to see the requests it was making. And it turned out there was no geometry in the endpoint I was using. I found one that had geometry and it looks to all be working now.

Let me know if you want me to squash all these commits.

**Comment by migurski** [comment]
No need to squash, and glad this worked for you! The installation directions are fairly new; is there anything about them you’d want to see written differently?

**Comment by davidchiles** [comment]
Installation went smoothly for me.

**Pull request merged**
