### PR TITLE
data url changed for Estonia

### PR DESCRIPTION
**Pull request by iSudo**
latest address data can now be fetched from here

### CODE REVIEW

**Comment by iSudo** [comment]
i made changes in target service, now should work as expected

**Comment by iSudo** [comment]
@iandees can you please check this and possibly merge? We built this service in order to provide latest address data for openaddresses, and we are also in need of the latest openaddresses data.

**Comment by iandees** [comment]
I appreciate the work you put into making this work, but I'm a little bit worried about pointing to an unofficial data source. It looks like the service you built is proxying or redirecting the download? How often does the data update?

**Comment by iSudo** [comment]
Hi, yes, the download is being proxied, its not the original place of addresses, true, but it is official, I'm working with the Estonian Land Board, and this is what ive come up with. Our national addresses are being updated approximately once a month.

**Comment by iSudo** [comment]
Is there something else I could do to make this pullrequest acceptable?

**Comment by iandees** [comment]
Sorry, I was still thinking about it. I'll merge it for now but would prefer to see a more direct link.

**Comment by iSudo** [comment]
Thanks, when can we expect this to reflect in results.openaddresses ?

**Comment by iandees** [comment]
The system refreshes data at least once a week, so probably by this weekend.

**Pull request merged**
