### PR TITLE
TN

### PR DESCRIPTION
**Pull request by ingalls**
Ref: https://github.com/openaddresses/openaddresses/issues/1700

### CODE REVIEW

**Comment by migurski** [comment]
I’ll accept this one; can’t ssh from in-flight wifi at the moment.

**Comment by migurski** [comment]
Sorry this might take some time, I need to figure out how to add some capacity without knocking the server over. I had been planning to replace it with a bigger one coinciding with a Python 3 / Ubuntu 16.04 upgrade, but it’s taking some time for Amazon to make an AMI available.

**Comment by migurski** [comment]
Moved the temp dir over to a much-larger EBS volume, and made a small edit to trigger a re-run. Let’s see how this goes.

**Comment by migurski** [comment]
😠 

```
 File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/worker.py", line 99, in do_work
   url, fingerprint = upload_file(s3, key_name, cache_path)
 File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/worker.py", line 30, in upload_file
   key.set_contents_from_filename(filename, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1362, in set_contents_from_filename
   encrypt_key=encrypt_key)
 File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1293, in set_contents_from_file
   chunked_transfer=chunked_transfer, size=size)
 File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 750, in send_file
   chunked_transfer=chunked_transfer, size=size)
 File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 951, in _send_file_internal
   query_args=query_args
 File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 668, in make_request
   retry_handler=retry_handler
 File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
   retry_handler=retry_handler)
 File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
   raise ex
error: [Errno 104] Connection reset by peer
```

**Comment by migurski** [comment]
That error has happened a few times now, so I’m thinking it’s not transient. I’ll need to dig in later on; suspecting that S3 doesn't like the very large GeoJSON files?

@ingalls, would it be possible to convert the TN data into a shapefile? I want to fix this error, but since you’re excited to see this source added they may be a more efficient way to get it going.

**Comment by migurski** [comment]
I’m attempting to convert this to a shapefile using ogr2ogr and seeing a failure to read; curious if it's a think you’ve run into?

```
ERROR 1: GeoJSON parsing error: continue (at offset -1)
ERROR 4: Failed to read GeoJSON data
FAILURE:
Unable to open datasource `us-tn.geojson' with the following drivers.
```

**Comment by tmcdon89** [comment]
Out of curiosity, what does the "ready" label signify?

**Comment by migurski** [comment]
That’s me using waffle.io to signify that this issue is in progress. I wish it wasn't visible here.

**Comment by migurski** [comment]
Making what might be progress turning this into a more-agreeable shapefile and wrapping the download script at https://github.com/openaddresses/openaddresses/tree/4a3d2f591/scripts/us/tn#readme.

**Comment by migurski** [comment]
screen shot 2016-06-17 at 10 27 07 am

**Comment by ingalls** [comment]
Woot!! 🎉

**Comment by migurski** [comment]
I do wonder about those missing counties, though.

**Comment by ingalls** [comment]
@migurski the map online has missing ones as well - so just guessing not all the counties are participating

**Comment by migurski** [comment]
Bummer, but okay. Wish I had a better way to represent that on the coverage map, guess I could drop in a geometry.

**Pull request merged**
