### PR TITLE
DC Parcels

### PR DESCRIPTION
**Pull request by ingalls**
### Context

DC Parcel Source

### CODE REVIEW

**Comment by ingalls** [comment]
Screenshot from 2021-02-17 16-04-33

Very exciting - processed data from the live service. Unfortunately this uncovered a couple bugs 

- [ ] Street/Number are being output as the properties? Didn't see this in local testing - should just be PID
- [ ] No Preview Image, Expected but should update the image creater to support polys
- [ ] Use GitDiff to attempt to only run modified layer in diff? To prevent 2 sources from being run when only 1 was added?

**Comment by iandees** [comment]
> No Preview Image, Expected but should update the image creater to support polys

Preview image is also not working for points: https://github.com/openaddresses/openaddresses/pull/5481

**Comment by ingalls** [comment]
Working on this here: https://github.com/openaddresses/batch/pull/113

**Comment by iandees** [comment]
🎉 🎉 🎉

**Comment by iandees** [comment]
Great work, Nick!

**Pull request merged**
