### PR TITLE
Add Iowa's Clay and Story counties

### PR DESCRIPTION
**Pull request by waldoj**

### CODE REVIEW

**Comment by slibby** [comment]
@waldoj looks like both shapefiles include town, postcode, district (county) and region (state) - can you add those to your conform objects before merging?

**Comment by waldoj** [comment]
I...cannot. I have no idea of how to do that. ¯\\\_(ツ)\_/¯

**Comment by slibby** [comment]
so it'd be something like this:
```
	"conform": {
		"number": {
			"function": "regexp",
			"field": "address",
			"pattern": "^([0-9]+)"
		},
		"street": {
			"function": "regexp",
			"field": "address",
			"pattern": "^(?:[0-9]+ )(.*)",
			"replace": "$1"
		},
		"city": " POSTAL_COM",
		"district": "COUNTY",
		"region": "STATE",
		"postcode": "ZIP_CODE",
		"type": "shapefile"
	}
```

**Comment by waldoj** [comment]
Watch out! I'm learning things!

**Comment by waldoj** [comment]
I'm using QGIS and _things are happening._

**Comment by waldoj** [comment]
Woo! Now I know a new thing! Thanks, @slibby. :)

**Comment by slibby** [comment]
:100:

**Pull request merged**
