### PR TITLE
Update us-fl-citrus.json

### PR DESCRIPTION
**Pull request by iandees**

### CODE REVIEW

**Comment by migurski** [comment]
I want to look into why this one and #1051 both come back as “nothing to check” in the CI.

**Comment by iandees** [comment]
Oh, good catch! I merged them because they got a green checkmark. Maybe I went too fast?

**Comment by migurski** [comment]
No you’re fine but it’s still weird.

**Comment by migurski** [comment]
This one [did get run](http://ci.openaddresses.io/jobs/184d67c0-0154-4cce-801d-96ca0f2175db), maybe a subsequent merge is clobbering the status here.

**Pull request merged**
