### PR TITLE
Remove already-deprecated support for "type" source tags

### LINKED ISSUE #4411: Remove old tags from source schema
Follow-up to #4409 — do this in a month when we’re confident they can go.

### PR DESCRIPTION
**Pull request by migurski**
Follow-up to #4409. Closes #4411.

- [x] Remove old tags from source schema
- [x] Wait until Feb 2019 to merge so we know this has worked for other people’s PRs

### CODE REVIEW

**Comment by geobrando** [comment]
@migurski  Just saw this. Should we be holding off on any new source PRs for now?

**Comment by trescube** [comment]
@geobrando You can submit PR with the new tags, I've been doing so off and on since @migurski updated all the existing sources.

**Comment by geobrando** [comment]
@trescube  I see.  My PR was not a new source but a change to an existing source and it looks like it had already been updated. Thanks.

**Comment by migurski** [comment]
You should be fine to merge! I changed the title of this PR to make it more clear what’s happening. We’ve already introduced support for the new tags and updated all the sources, now we just need to complete removal of support for the old tags. I wanted to give this a ~month of observation so I will likely merge this PR in the middle of Feb.

**Pull request merged**
