### PR TITLE
Better source for Otter Tail

### PR DESCRIPTION
**Pull request by mmdolbow**
According to the download site, this is updated weekly

### CODE REVIEW

**Comment by trescube** [comment]
Switch `"protocol": "https"` to `"protocol": "http"`, the machine is smart enough to pick up on the difference.

**Comment by mmdolbow** [comment]
any chance this can get merged soon?

**Comment by trescube** [comment]
Hey @mmdolbow, sorry, I let these slip off my radar.  I'll start going thru them.

**Comment by mmdolbow** [comment]
No worries, thank you!

**Pull request merged**
