### PR TITLE
Contributing to: br-es-vitória.json

### PR DESCRIPTION
**Pull request by astoff**
Adding/Updating br-es-vitória.json

### CODE REVIEW

**Comment by geobrando** [comment]
Since lat/lon are no longer required conform fields we need to update the tests and this should pass.

**Comment by astoff** [comment]
Should I add lat.lon fields so this can be merged?

Also, there is no formal license statement on the website, but I was informed by email that the data can be used freely provided attribution in given.  What is the best way to keep track of this information?

**Comment by ingalls** [comment]
For attribution see: https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#optional-tags

**Comment by astoff** [comment]
The diacritical in the file name was causing an error, so I renamed the file.  The website wizard should strip accented characters from city names.

**Pull request merged**
