### PR TITLE
Create port_moody.json

### PR DESCRIPTION
**Pull request by KHobbs3**
Created source file for Port Moody, BC.

### CODE REVIEW

**Comment by ingalls** [comment]
@KHobbs3 It looks like the data link here is invalid:
https://opendata.arcgis.com/datasets/7bc8ca82182141d2b3f0452fe593d528_30.zip

**Comment by justinelliotmeyers** [comment]
@KHobbs3  @ingalls https://services9.arcgis.com/XMHGoEc3tdJ8TphG/arcgis/rest/services/Addresses/FeatureServer/37

source:
https://data.portmoody.ca/datasets/d485aaa4f27641bf88ccb5fe79180bed_37

**Comment by KHobbs3** [comment]
> @KHobbs3 @ingalls https://services9.arcgis.com/XMHGoEc3tdJ8TphG/arcgis/rest/services/Addresses/FeatureServer/37
> 
> source:
> https://data.portmoody.ca/datasets/d485aaa4f27641bf88ccb5fe79180bed_37

Thanks, took note of that and will look into this

**Comment by KHobbs3** [comment]
> @KHobbs3 @ingalls https://services9.arcgis.com/XMHGoEc3tdJ8TphG/arcgis/rest/services/Addresses/FeatureServer/37
> 
> source:
> https://data.portmoody.ca/datasets/d485aaa4f27641bf88ccb5fe79180bed_37

@justinelliotmeyers What would the "number" and "street" fields be for this dataset?

**Comment by justinelliotmeyers** [comment]
@KHobbs3 yikes - that actually looks like junk! Sorry about that - I usually always check to make sure the data looks good, but that is missing everything!

try this little guy:
https://services9.arcgis.com/XMHGoEc3tdJ8TphG/ArcGIS/rest/services/Parcel_Information/FeatureServer/0

**Comment by KHobbs3** [comment]
> @KHobbs3 yikes - that actually looks like junk! Sorry about that - I usually always check to make sure the data looks good, but that is missing everything!
> 
> try this little guy:
> https://services9.arcgis.com/XMHGoEc3tdJ8TphG/ArcGIS/rest/services/Parcel_Information/FeatureServer/0
> 
> use address field

Thank you! I'll just verify the license information before making another PR...

**Pull request merged**
