### PR TITLE
Add get method to the schema

### PR DESCRIPTION
**Pull request by macieg**
Following the steps described here -> https://github.com/openaddresses/batch/pull/83#issuecomment-719858083

### CODE REVIEW

**Comment by ingalls** [comment]
@macieg Thanks for all your hard work getting this together, if you can just add docs per the format of the existing here this will be ready to merge: https://github.com/openaddresses/openaddresses/blob/master/ATTRIBUTE_FUNCTIONS.md

**Comment by macieg** [comment]
@ingalls done, as you wish :)

**Comment by macieg** [comment]
@ingalls ping

**Comment by ingalls** [comment]
Hey thanks for the ping, I get a million GH notifications. This looks fantastic. I'll get it merged and batch updated.

**Pull request merged**
