### PR TITLE
Contributing to: za-nl-ethekwini.json

### PR DESCRIPTION
**Pull request by luiscape**
Adding/Updating za-nl-ethekwini.json

### CODE REVIEW

**Comment by sbma44** [comment]
I'm afraid that tests are failing because `type` should be `http`. This is an ambiguously named field, but if you have a look at the [docs](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md) you'll see that this field has to be `http`, `ftp` or `ESRI`.

Looking at the diff, I'm unsure of what else the PR is doing besides flipping that field. Did the data need a refresh?

**Comment by ingalls** [comment]
This is coming from the online editor so my guess is that it was a test. I'm going to close this. @luiscape feel free to reopen if this is not the case.

**Comment by luiscape** [comment]
@ingalls sorry for that folks. Indeed, it was a test -- or less than that. It wasn't totally clear at the time that I was making a commit. Sorry once again.

**Comment by iandees** [comment]
@ingalls the bug I was pointing out was that it set the "type" to "zip". The editor shouldn't let that happen.

**Pull request closed without merging**
