### PR TITLE
Create garrett.json

### PR DESCRIPTION
**Pull request by jbchurchill**
I attempted to set up a .json file modeled after the Allegany.json file. Ours is based on our County's "Address Points" point file and the fields are different.

### CODE REVIEW

**Comment by trescube** [comment]
Sorry, the values for `district` and `region` have to match the case in the source (`COUNTY` and `STATE`).  Otherwise it looks great!

**Comment by jbchurchill** [comment]
I think I have this done as requested. Let me know if there is anything else that wasn't correct.

**Comment by jbchurchill** [comment]
Ok I changed the case of COUNTY and STATE. I guess I didn't realize they were pointing to the source.

**Comment by trescube** [comment]
Oh, I see!  Yeah, the attribute values should be taken directly from the ESRI source verbatim.

**Comment by trescube** [comment]
Looks great, thanks again for the contribution!  

If you're willing to help out on more sources, you can look for holes in the coverage at any level (city, county, state, or country) or check out [Lost sources](https://results.openaddresses.io/dashboard) for sources that used to work but don't anymore!

**Pull request merged**
