### PR TITLE
Add New Mexico Statewide

### PR DESCRIPTION
**Pull request by ingalls**
Got a tipoff that the state address file from 2016 lives here: http://rgis-data.unm.edu/rgis/ApolloPro.aspx

### CODE REVIEW

**Comment by trescube** [comment]
That is a fine looking map (lived in New Mexico for 2 years).

**Comment by iandees** [comment]
@ingalls how did you download and cache these?

**Comment by iandees** [comment]
For posterity:
1. Go to the website http://rgis-data.unm.edu/rgis/ApolloPro.aspx
1. On the left, under "Search RGIS Data Catalog", search for `address points`
1. First result in the lower right should be "New Mexico Address Points"
1. Click it so the row highlights red, then click the Download link above it

**Comment by nvkelso** [comment]
Last big hole in the western USA, great work!

**Comment by migurski** [comment]
A fine-looking state in a fine-looking aspect ratio.

**Pull request merged**
