### PR TITLE
Komi Republic, Russia

### PR DESCRIPTION
**Pull request by sergiyprotsiv**
Data for the northerly Komi Republic

### CODE REVIEW

**Comment by sergiyprotsiv** [comment]
This server is a bit slow, but I got it working locally. Is it possible to set the default timeout to something like 300 seconds?

**Comment by migurski** [comment]
Yes, I think I can do that! I'm unsure where it’s set now, but: https://github.com/openaddresses/machine/issues/528

@sergiyprotsiv, would you like to be added to the OA Github org so you can work on branches directly in this repository?

**Comment by sergiyprotsiv** [comment]
Re-run this please.

**Comment by sergiyprotsiv** [comment]
Re-run this please.

**Comment by sergiyprotsiv** [comment]
Re-run this please.

**Comment by sergiyprotsiv** [comment]
Nooo, it got 616K out of 640K and died. Try again, otherwise will upload a cached version.

**Comment by thatdatabaseguy** [comment]
The "TYPE_S" field refers to the thoroughfare type e.g. улица, so maybe it should be:

```json
"street":  ["TYPE_S", "NAME_S"],
```

or perhaps the inverse order?

**Comment by nvkelso** [comment]
Can this be merged?

**Comment by sergiyprotsiv** [comment]
I think this one is fine too, though only a fraction of building s contain an address

**Comment by thatdatabaseguy** [comment]
LGTM

**Pull request merged**
