### PR TITLE
ga

### PR DESCRIPTION
**Pull request by ingalls**

### CODE REVIEW

**Comment by iandees** [comment]
GA!

**Comment by ingalls** [comment]
ANSI:INCITS 38:2009 13!

**Comment by iandees** [comment]
Can you make sure you're adding docs/code to describe how you're building these zips that end up in data.openaddresses.io?

**Comment by migurski** [comment]
This makes me think we need a way to detect staleness in the data we are hosting ourselves.

**Comment by ingalls** [comment]
@migurski I agree. We have the `year` tag which I added in the original spec to do just that. But with machine this would be far better to automate and then deprecate the `year` tag.

**Pull request merged**
