### PR TITLE
Data download issue with San Mateo, California

### PR DESCRIPTION
**Pull request by jdstone-loansnap**
The original file download link was invalid, as was the path to the file within the zip file. Fixed both.

### CODE REVIEW

**Comment by migurski** [comment]
Actually, this might not be a bug Machine. Can you update your PR with this on line 18:

```
         "file": "SAN_MATEO_COUNTY_ACTIVE_PARCELS.shp", 
```

**Comment by jdstone-loansnap** [comment]
Thanks, I did see the output log and the sample output.  I found this closed issue from earlier, [#252](https://github.com/openaddresses/openaddresses/issues/252), that looks like a similar issue was run into in the past.

**Comment by migurski** [comment]
We recently changed the tags for OA sources and it might affect this PR. [Moving forward, "type" tags are now either "protocol" or "format"](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#core-tags). If this PR is still active it might need to be updated.

**Comment by jdstone-loansnap** [comment]
@migurski, we can close this pull request if you'd like or think we should.

**Pull request closed without merging**
