### PR TITLE
Switzerland, countrywide

### PR DESCRIPTION
**Pull request by gismountains**
Switzerland, countrywide

### CODE REVIEW

**Comment by ingalls** [comment]
Oh wow, @gismountains this is amazing. Looks like our processing server has some trouble finding the field `GKODE`

**Comment by gismountains** [comment]
I see the error message that "GKODE" cannot be read. But there seems to be a general problem left. The attributes cannot be distinguished. Is it on the UTF-8-BOM (\ ufeff)? Or is it the delimiter ";"?

**Comment by sergiyprotsiv** [comment]
Thanks a lot @gismountains, this looks fantastic.
As for the error, my guess would be that it is the BOM marker. I can't find the `iconv` encoding code for UTF-8 with BOM, maybe worth trying "utf-8-sig" or something like that or trying to remove the "encoding" field altogether. @migurski, any advice on how the machine handles encoding conversion?

**Comment by sergiyprotsiv** [comment]
Another (and much more likely) solution could be to add "csvsplit" : ";" to conform. I just noticed it was missing.

**Comment by sergiyprotsiv** [comment]
Looks good to me!

**Comment by iandees** [comment]
This looks great, but the license looks questionable to me. On https://www.geocat.ch/geonetwork/srv/eng/md.viewer#/full_view/56553efe-4a2c-449d-93ba-cf7edd518d56, the use restrictions page says "Any commercial utilisation is excluded".

**Comment by gismountains** [comment]
@iandees I think this is outdated. But I check with the responsible person for the metadata.

**Comment by ingalls** [comment]
Hey @gismountains really excited about this potential source, any update on the licensing side?

**Comment by gismountains** [comment]
Hey @ingalls. I got a feedback from the responsable person. The license-information is outdated. Update is following soon, I check and let you know.

**Comment by K-Leon** [comment]
Thanks for your hard work!
Any updates on this?

**Comment by gismountains** [comment]
Still pending.... sorry for no better news.

**Comment by ingalls** [comment]
@gismountains Just checking in :)

**Comment by gismountains** [comment]
@ingalls Yes, you can. It is now clear about the licensing. In the zip-file it is written in the "license.txt" file in german, french and italien:
Open use. Must provide the source.
- You may use this dataset for non-commercial purposes.
- You may use this dataset for commercial purposes.
- You must provide the source (author, title and link to the dataset).

**Comment by ingalls** [comment]
@gismountains This is magical!! Thank you so much for working through this!

**Comment by iandees** [comment]
Oh that's beautiful.

**Comment by migurski** [comment]
Oh wow, yeah.

**Pull request merged**
