### PR TITLE
added `unit` to US/OK and US/OH

### PR DESCRIPTION
**Pull request by trescube**

### CODE REVIEW

**Comment by trescube** [comment]
Well, I forgot to switch branches and ended up adding US/OH to this branch.

**Comment by migurski** [comment]
Heh. 

screen shot 2016-03-11 at 8 33 50 pm

**Comment by iandees** [comment]
These have a `addr_half` in the `number` merge list but that column doesn't exist in the source:
- sources/us/oh/harrison.json
- sources/us/oh/henry.json
- sources/us/oh/highland.json
- sources/us/oh/lawrence.json
- sources/us/oh/licking.json
- sources/us/oh/tuscarawas.json

**Comment by iandees** [comment]
sources/us/oh/toledo.json's conform object has `type` set to `shapefile` when it should be `geojson`.

**Pull request merged**
