### PR TITLE
Contributing to: .json

### PR DESCRIPTION
**Pull request by evaryont**
Adding/Updating .json

### CODE REVIEW

**Comment by evaryont** [comment]
Woah, that was unintentional. First time filling out the contribution form, didn't realize what the fields all mapped to.

This is for the city of Scottsdale, AZ in the USA.

**Comment by geobrando** [comment]
@evaryont No worries.  Unfortunately, this data appears to be street centerlines and not address data.  Looks like their actual [address data](https://eservices.scottsdaleaz.gov/eservices/dmc/ProductIntro.aspx) is only available for $500+processing fee.  But thanks for contributing.

**Comment by evaryont** [comment]
What is the policy for data like this? I don't mind collecting the money to purchase it and rehosting it (assuming that Scottsdale GIS would allow that), but it would defintely be only a one-time situtation.

**Comment by iandees** [comment]
We haven't started paying for data yet, but I imagine we'll have to soon if we want to increase our coverage.

In this particular case we'd have to work out special arrangements because their disclaimer says the data cannot be redistributed after purchase.

**Pull request closed without merging**
