### PR TITLE
Seminole County, FL, USA. ESRI GDB

### PR DESCRIPTION
**Pull request by riordan**
Linked to #1620

### CODE REVIEW

**Comment by iandees** [comment]
@riordan can you try sending a whitespace change to see if this works after GDB support was added in https://github.com/openaddresses/machine/pull/349?

**Comment by riordan** [comment]
Turns out it actually needed a `conform`. 

This also overwrites @trescube's work with the script to do this. Should probably be paired with something to remove the S3 file #1758

**Comment by trescube** [comment]
@riordan you're dead to me

**Comment by iandees** [comment]
This looks good to me, but has merge conflicts.

**Pull request closed without merging**
