### PR TITLE
Add barton

### PR DESCRIPTION
**Pull request by ingalls**
Extracts addresses from accessors PDF using build scripts found here: https://github.com/ingalls/barton_ks_addresses

### CODE REVIEW

**Comment by ingalls** [comment]
hmm @migurski do you know what the error is being caused by off the top of your head or should I go digging?

**Comment by migurski** [comment]
Looks like [a stray “:” in one of the column names](http://data.openaddresses.io.s3.amazonaws.com/runs/2371/output.txt).

**Comment by ingalls** [comment]
Sigh, thanks @migurski I was thinking it was a problem with the source data, my sleepy brain didn't even consider it being the json file. Fixed.

**Comment by migurski** [comment]
:+1:

**Pull request merged**
