### PR TITLE
Fixes for Biella and Verona

### PR DESCRIPTION
**Pull request by musuruan**
Renamed files to avoid city_of_ just like Torino, Venice, Bologna, Ferrara, etc.
   
Removed "region" from Biella. It's not necessary and moreover Biella is in Piemonte and not in Lombardia.
    
Updated website for Biella Open Data.

### CODE REVIEW

**Comment by iandees** [comment]
Looks like number localization errors? The decimal for the latitude and longitude fields is a comma in the source data. We don't have a great way to resolve that right now. 🤔

**Comment by musuruan** [comment]
How was Verona data committed in the first place? I've just renamed the file...

**Comment by iandees** [comment]
Yea, we can deal with that later. Thanks!

**Comment by iandees** [comment]
The number localization error appears to be a warning that we can ignore here.

I think Mapbox has started to serve error messages to our map image rendering pipeline, which breaks that step of the build.

**Pull request merged**
