### PR TITLE
WIP: added city of Tacoma, WA

### LINKED ISSUE #1947: Add addresses in Tacoma, WA
Status:
- [x] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

### PR DESCRIPTION
**Pull request by trescube**
Fixes #1947

### CODE REVIEW

**Comment by nvkelso** [comment]
Bingo!

On Wed, Feb 1, 2017 at 10:10 AM, OpenAddresses Bot <notifications@github.com

**Comment by trescube** [comment]
WAIT! There's still work to do on units, that's why it's WIP.

**Comment by trescube** [comment]
I thought I had all the variations but there are some outliers.

**Comment by migurski** [comment]
Oh no, sorry! I didn't notice the "WIP" in the title.

**Comment by thatdatabaseguy** [comment]
@trescube here's (the street name version of) a regex that should fix units:

```json
"^(?:\\d+(?: 1\/2)?)\\s+(.+?)(?:\\s+(?:#.*|[A-DF-MO-RT-VX-Z]|[A-Z]?-?\\d+[A-Z]?|(?:UNIT|STE|BLDG)\\s+\\w+|REAR|LOWR|UPPR))?$"
```

- allows an optional letter on the end of a unit number e.g. "3502 S MASON AVE 8B"
- single letter at the end of the street name can be a post-directional (in/around Seattle the directionals are usually NE/NW/SE/SW though so that might not be necessary).

**Pull request merged**
