### PR TITLE
Slovenia countrywide - updated data and improved scripts

### PR DESCRIPTION
**Pull request by stefanb**
...to be compliant with the CC-BY license of the source dataset

Improves #2926, continuation of  #2980

### CODE REVIEW

**Comment by nvkelso** [comment]
Ideally OpenAddresses gets the source data from the source, or we host on our own S3 bucket. But it looks like https://github.com/openaddresses/openaddresses/pull/2982/commits/909901f5dba13b7ad6e1ae12e4e2aa7426405f18 switches to OpenStreetMap local chapter hosting. Please advise.

**Comment by stefanb** [comment]
Slovenian data requires some processing to download (it is behind form login) and de-normalize the data.
There is a `Makefile` for GNU `make`  script in scripts/si that does it all, but i have no access to your amazon s3 bucket to publish the results there.

If you can have 
* `make` executed periodically (eg once a month), 
* someone register at the data source (they just require email and they send a password, registrant has to agree to use the data in accordance with the CC-BY 2.5 license) and
* publish to openaddress' s3 bucket.

Then i will gladly change the scripts accordingly.

**Comment by nvkelso** [comment]
@stefanb thanks for the background! @iandees what do you want to do here?

**Comment by iandees** [comment]
Thanks for doing all the work on the download script here, @stefanb. I'm ok with using externally-hosted data for this because the script to generate the data is so well documented. 👍

**Comment by stefanb** [comment]
Tnx!
I'll add it to crontab. What is the current schedule, when should the data
be ready?

12. maj 2017 01:31 je oseba "Ian Dees" <notifications@github.com> napisala:

Merged #2982 <https://github.com/openaddresses/openaddresses/pull/2982>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openaddresses/openaddresses/pull/2982#event-1079138194>,
or mute the thread

**Comment by migurski** [comment]
Hi, we don’t currently run upstream source scripts like this on any kind of schedule. The closest thing is Australia’s ~quarterly updates, which we [process with a docker script](https://github.com/openaddresses/openaddresses/tree/master/scripts/au) when reminded in https://github.com/openaddresses/openaddresses/issues/1701.

**Comment by stefanb** [comment]
I meant global batch import schedule (twice per week?), so that I can
adjust mine (running make in scripts/si) accordingly.

13. maj 2017 01:29 je oseba "Michal Migurski" <notifications@github.com>
napisala:

**Comment by migurski** [comment]
Ah okay. Our global batch does happen ~twice weekly, typically on Mondays and Fridays.

**Pull request merged**
