### PR TITLE
Added Umbria

### PR DESCRIPTION
**Pull request by sergiyprotsiv**
Added a good dataset for Umbria.

It is generally available via the REST service (http://geo.umbriaterritorio.it/ArcGIS/rest/services/Public/ECOGRAFICO_CATASTALE1_WGS84/MapServer/0), but the resulting files contain only the code for municipality, not the name. So this is the data downloaded from the REST service and joined with municipality data from Istat.

### CODE REVIEW

**Comment by nvkelso** [comment]
Re-run this please

**Comment by trescube** [comment]
What's the next step with this one?  It sounds like the REST data is missing the city name which must be looked up elsewhere in a post-processing step, but the standard operating procedure is to register a script to recreate the data in `/scripts`?

**Comment by sergiyprotsiv** [comment]
I have all the scripts for the Italian regions, but did not find time to figure out exactly how to do this via Github (a bit of a novice here). If you can suggest the proper way, I'll try to put this up during the weekend. Or I can send these via email.

**Comment by trescube** [comment]
I've not had to handle custom scripts, but looking at other things in `/scripts`, it looks like we're favoring creating a directory in `/scripts`, adding all the custom scripots, then creating a docker file to run the exporting scripts.  See: 
https://github.com/openaddresses/openaddresses/tree/master/scripts/us/tn

If you want to tackle it, please do so, otherwise email everything to stephen@mapzen.com and I can take a crack at it.

**Comment by trescube** [comment]
The same probably applies to #1900, #1898, #1897, and #1894.

**Comment by migurski** [comment]
Yeah — the docker part is optional, but helps in cases like Australia’s data where it's necessary to run a complex set of pieces like PostGIS, etc.

**Comment by iandees** [comment]
I'd rather we pull straight from the source and not manually merge in city information. For me, pulling from a primary source trumps more-complete data.

**Comment by sergiyprotsiv** [comment]
Re-run this please

**Comment by sergiyprotsiv** [comment]
This is ready to be merged, I think

**Pull request merged**
