### PR TITLE
adding Dubai addresses 🇦🇪

### PR DESCRIPTION
**Pull request by thatdatabaseguy**
From #3021, split into Arabic and English files similar to Saudi Arabia.

### CODE REVIEW

**Comment by thatdatabaseguy** [comment]
Re-run this please.

**Comment by nvkelso** [comment]
Those islands!

On Thu, Jun 1, 2017 at 10:58 PM, OpenAddresses Bot <notifications@github.com

**Comment by CChelmis** [comment]
@thatdatabaseguy, is it possible to map Long/Lat/Makani info to building names?

**Comment by thatdatabaseguy** [comment]
@CChelmis there's not a field in OpenAddresses for building name, so wouldn't be able to list it here. If you have building polygons, it's possible to reverse geocode to the building to get the name. We do this for planet-wide OSM buildings with [libpostal's R-tree polygon indices](https://github.com/openvenues/libpostal/blob/master/scripts/geodata/polygons/reverse_geocode.py).

It seems like there's a building layer here with names: http://www.makani.ae/arcgis/rest/services/DMap_EL_2015/MapServer/7, but not an obvious and correct way to join it to entrances/Makani.

**Comment by CChelmis** [comment]
@thatdatabaseguy tbh just getting started with OpenAddresses and geocoding. I was curious though, from the file(sources/ae/du/dubai-en.json) the Makani for the entrance corresponding to the Index Tower for example is 26484 89015. However, if you search for Index in http://www.makani.ae the same entrance appears to have Makani 26486 89012. So was not clear to me where this discrepancy is coming from. Moreover, searching for 26484 89015 in http://www.makani.ae yields no results.

**Comment by nvkelso** [comment]
Building name would be useful to add to data model. Not very common, but useful when it is.

**Comment by migurski** [comment]
This looks to be the same as “Building” in the NAD Schema: 

screen shot 2017-06-05 at 5 54 39 pm

**Comment by thatdatabaseguy** [comment]
@CChelmis hm, makani.ae may use this layer instead: http://www.makani.ae/arcgis/rest/services/SmartApp/MapServer/3, which contains "26484 89015" but not "26486 89012". That was the first layer I looked into but it didn't have street names, so opted for the layer that did (both street and house number are [required](https://github.com/openaddresses/openaddresses/blob/79f38428cf38bf02b70c3b88800de3c2a15c6941/schema/source_schema.json#L136) for OpenAddresses). The response from makani.ae does appear to return street names, but it's unclear which layers are included as the ESRI requests are made server-side.

Possible that (some of?) the Makani numbers in the layer used here are out of date.

**Pull request merged**
