### PR TITLE
Fix some sources

### PR DESCRIPTION
**Pull request by iandees**

### CODE REVIEW

**Comment by migurski** [comment]
Re-run this please.

**Comment by migurski** [comment]
Re-run this please.

(Testing new 3.x installation)

**Comment by migurski** [comment]
Re-run this please.

**Comment by migurski** [comment]
Re-run this please.

**Comment by iandees** [comment]
Re-run this please.

**Comment by iandees** [comment]
Re-run this please.

**Comment by iandees** [comment]
Gonna get this merged in and come back to fixing the errors later.

**Pull request merged**
