### PR TITLE
WIP: added Belmont County, OH, USA

### LINKED ISSUE #2677: Belmont County, OH
I have the address points as a shapefile sent by their GIS manager. Waiting to hear back from him about license/redistribution.

### PR DESCRIPTION
**Pull request by trescube**
Fixes #2677 

waiting on info about license/redistribution

### CODE REVIEW

**Comment by migurski** [comment]
Testing some more to make sure https://github.com/openaddresses/machine/pull/605 worked:

Re-run this, please.

**Comment by migurski** [comment]
Testing some more to make sure https://github.com/openaddresses/machine/pull/605 worked:

Re-run this, please.

**Comment by migurski** [comment]
Testing one last time (for today) to make sure https://github.com/openaddresses/machine/pull/605 worked:

Re-run this, please.

**Comment by migurski** [comment]
Actually, one more for https://github.com/openaddresses/machine/pull/605 sorry:

Re-run this, please.

**Comment by migurski** [comment]
Testing again, to see if https://github.com/openaddresses/machine/pull/587 worked:

Re-run this, please.

**Comment by trescube** [comment]
@nvkelso I saw this disclaimer text on http://belmont-oh.bhamaps.com/.  Does it look okay for OA to ingest?

"The base mapping contained herein was photogrametrically compiled to National Map Accuracy Standards by Kucera International Inc., Willoughby, Ohio, from aerial photography dated April 2001, March 2006 and April 2011 based on ground control in the Ohio State Plane Coordinate System, South Zone, NAD 83(95), US survey foot.  The parcel lines on this map, if any, were digitized from paper tax maps and adhere to no accuracy standard.  All data on this map were created for the use of Belmont County for county government purposes.  The suitability of this map for any other use is not guaranteed and the user assumes all risk for such uses.  Belmont County, Ohio, assumes no legal responsibility for the information on this map.  Users noting errors or omissions are encouraged to contact the Belmont County Geographic Information System Office."

**Comment by nvkelso** [comment]
Yes, that’s fine.

It’s basically saying “we made it for us, it works for us, it may not work
for you, but try it out”.

**Comment by trescube** [comment]
Superseded by #3097

**Pull request closed without merging**
