### PR TITLE
Added us/ms/statewide

### PR DESCRIPTION
**Pull request by MiniCodeMonkey**

### CODE REVIEW

**Comment by MiniCodeMonkey** [comment]
What's the best way to retry this? It looks like their server is just intermittently timing out. I had to to retry once when I tested locally as well.

**Comment by iandees** [comment]
Rerun this please.

**Comment by iandees** [comment]
This looks good, but it doesn't seem to be statewide. Do you happen to know what MDEQ is? It looks like it's a subset of the counties that are working together.

**Comment by MiniCodeMonkey** [comment]
Updating source name to reflect that it's a partial statewide source (looks like it may evolve to be statewide over time).

Not sure about the MDEQ name, but here's some info on MDEM (the prefix for the layer name) https://www.mdeq.ms.gov/mdem/

**Comment by MiniCodeMonkey** [comment]
Oooh. MDEQ is Mississippi Department of Environmental Quality which maintains the data.

**Pull request merged**
