### PR TITLE
mass switch from old style auto_number/auto_street to regexp for more…

### PR DESCRIPTION
**Pull request by stephenkhess**
… accurate number/address extraction

### CODE REVIEW

**Comment by iandees** [comment]
It looks like you changed the indent on all these files. Can you switch them back to 4 spaces please?

**Comment by stephenkhess** [comment]
Yep, sorry about that, I wrote a script to handle them so that's easily fixable.

**Comment by stephenkhess** [comment]
GAH!  Fixed the indent but git does not appear to notice the difference.

**Comment by iandees** [comment]
Also, it looks like you're not writing out a newline as the last character. Can you add an extra `\n` to the end?

**Comment by stephenkhess** [comment]
Screw it, I'm starting over, the indentation checkin will trigger all the bad sources to run tests again.

**Pull request closed without merging**
