### PR TITLE
Portugal - Lisboa

### PR DESCRIPTION
**Pull request by sergiyprotsiv**
This is a minimal source for Lisbon, Portugal. Covers just the municipality itself. There are two more address datasets in the source, but the others are designed for lower zoom levels.

Coverage does not contain geometry so far, will add it to all Portuguese sources eventually.

### CODE REVIEW

**Comment by sergiyprotsiv** [comment]
Most of the addresses seem okay, but there are quite a few that obviously contain wrongly formatted data or text, but without an obvious pattern. Shall I just filter out the addresses with regex (e.g. ^[0-9]+[A-Za-z]) and perhaps risk removing some of the valid ones, or keep things as they are?

**Comment by astoff** [comment]
This is a bit of nitpicking, but could you replace `"city": "Lisbon"` with `"county": "Lisboa"` in the coverage? (Also, should it include `"state": "11"` or `"state": "Lisboa"` or not?).

Here's a quick explanation of Portugal's organization (from what I gather from Wikipedia). The country's administrative subdivisions are distrito > câmara municipal (aka município or concelho) > freguesia. They are analogous to state > county > civil township in the US. Cities and towns are an independent, and apparently somewhat informal, kind of entity. However, for added confusion, distritos and câmaras municipais are often named after their main city.

Now, it seems that most address data in Portugal will come from the câmaras municipais (as indicated by the "cm-" prefix in the domain names). It looks like the city and municipio of Lisboa coincide, but it will not be the case for all other regions, so let's be consistent from the beginning.

As to the regex, it seems to me that the only thing to fix is to remove all text between parenthesis at the end of the street names and numbers. Things like "Bloco 64B" are valid house numbers.

**Comment by astoff** [comment]
The numbers look good to me. The same regexp should do the job for street names.

**Comment by sergiyprotsiv** [comment]
Re-run this, please.

**Comment by sergiyprotsiv** [comment]
Re-run this, please.

**Comment by astoff** [comment]
Looks good to me!

**Comment by migurski** [comment]
Testing a new version of Machine:

Re-run this, please.

**Pull request merged**
