### PR TITLE
BE-Flanders: Corrected EPSG string and character encoding

### PR DESCRIPTION
**Pull request by pietercolpaert**
According to the metadata file, this should be correct

### CODE REVIEW

**Comment by pietercolpaert** [comment]
Tested the dump and the coordinates are still of. Something going wrong with Lambert72 → WGS84 convertor

**Comment by pietercolpaert** [comment]
https://github.com/xivk/crab-tools/blob/master/python/lambert.py → This would be a correct convertor

**Comment by sbma44** [comment]
Ick. Thanks for catching this. Agreed that this still doesn't look right:

image

It's hard for me to believe that GDAL/osgeo is incapable of this, though, if given the correct EPSG code.

**Comment by migurski** [comment]
For comparison, here’s an overlay with OSM that makes it look like an east/west shift:

flanders

**Comment by pietercolpaert** [comment]
@xivk told me there are many GIS tools that don't handle EPSG:313X0 correctly. Maybe he could elaborate on whether GDAL would be able to handle this ok though?

**Comment by xivk** [comment]
Not sure... In any case don't dismiss the possibility of bugs in the tools used to convert this projection, including GDAL. You can use this tool to verify:

http://zoologie.umh.ac.be/tc/

...  or use the python script @pietercolpaert suggested.

**Comment by pietercolpaert** [comment]
@xivk unless the SHP file is using EPSG:3812 (Lambert 2008) instead of the indicated EPSG:31370 (Lambert72)? I'm going to try this, just to be sure, and check out the results in a next commit

**Comment by pietercolpaert** [comment]
It's still off... I'm going to revert it to what is given in the metadata

**Comment by sbma44** [comment]
Sounds like we ought to cache a correctly-reprojected dataset and ticket
this projection in machine and gdal. Can you post a link to a correct 4326
version of the data?

**Comment by pietercolpaert** [comment]
Hi @sbma44 - We have a 2013 version put in CSV files on github over here: https://github.com/xivk/crab-tools/tree/master/crab_csv - generated by @xivk. Maybe he can post an update of this on his repo, zip it in one CSV file and provide you with that?

**Comment by sbma44** [comment]
@pietercolpaert @xivk that sounds great. I can get this data into http://data.openaddresses.io/cache/ for you once the file is ready to go.

**Comment by xivk** [comment]
I converted the latest version again to one big csv here:

ftp://ftp.osmsharp.com/crab/CRAB-csv.zip

**Comment by sbma44** [comment]
I'm afraid that the LON column didn't make it through, @xivk 
image

**Comment by pietercolpaert** [comment]
@xivk indeed: there's no longitude in the dump...

**Comment by xivk** [comment]
Uploading a corrected version now... but will take a while at 32KB/s (working from Mali)

**Comment by xivk** [comment]
@sbma44 OK, please try again.

**Comment by sbma44** [comment]
Looks good!

image

```
$ head -n 10 crab.csv | csvlook
|-----------+-----------------------+----------------------+---------+------------------+-------------------|
|  POSTCODE | COMMUNE               | STREET               | HOUSENR | LAT              | LON               |
|-----------+-----------------------+----------------------+---------+------------------+-------------------|
|  9000     | Gent                  | Klaverstraat         | 1A      | 51.0722684736021 | 3.71081530237952  |
|  3511     | Hasselt               | Mevrouwhofstraat     | 42      | 50.9535585976835 | 5.27084054458466  |
|  3270     | Scherpenheuvel-Zichem | Vuggelberg           | 6       | 50.9630134788687 | 4.94402812369739  |
|  2431     | Laakdal               | Makelhoeve           | 2       | 51.067314092224  | 5.006627611033    |
|  9170     | Sint-Gillis-Waas      | Polenlaan            | 50      | 51.2524774321331 | 4.08183993091726  |
|  2200     | Herentals             | Hoge Weg             | 4       | 51.1470769322371 | 4.82118320483419  |
|  2610     | Antwerpen             | Kerkelei             | 24      | 51.1676513240308 | 4.39708285437998  |
|  2960     | Brecht                | Molenstraat          | 100     | 51.3405956131847 | 4.61990954122569  |
|  8510     | Kortrijk              | Oude Aalbeeksestraat | 64      | 50.7693088431531 | 3.2567011475209   |
|-----------+-----------------------+----------------------+---------+------------------+-------------------|
```

I've uploaded the zipfile to `http://data.openaddresses.io/cache/be-CRAB-csv.zip`. Note the new `be-` that I added to the front of it -- my hope was to make it easier for future generations of OpenAddresses archivists to make sense of what's going on. The file it contains is still called crab.csv, like so:

```
sbma44-mbp:~/Desktop/be $ unzip -l be-CRAB-csv.zip 
Archive:  be-CRAB-csv.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
223789495  07-28-15 15:06   crab.csv
 --------                   -------
223789495                   1 file
```

**Comment by migurski** [comment]
:boom:

**Comment by sbma44** [comment]
Hangon, reverting -- `data` field needs to be updated

**Comment by pietercolpaert** [comment]
This still isn't correct in opeaddresses.io?

**Comment by sbma44** [comment]
Looks ok to me: http://data.openaddresses.io.s3.amazonaws.com/be-flanders.zip

image

**Comment by pietercolpaert** [comment]
I meant the visualization on the homepage... Doesn't this get updated from time to time?

**Comment by sbma44** [comment]
Ah. Yes, it does, though the one on openaddresses.io requires manual intervention. The one at data.openaddresses.io refreshes automatically.

**Pull request merged**
