### PR TITLE
added statewide Kansas, USA

### PR DESCRIPTION
**Pull request by trescube**

### CODE REVIEW

**Comment by trescube** [comment]
rerun this please

**Comment by nvkelso** [comment]
Wow!

**Comment by trescube** [comment]
ooh, that's pretty

**Comment by migurski** [comment]
[A Perfectly Flat Kansas](https://www.reddit.com/r/MapPorn/comments/3qr09l/a_perfectly_flat_kansas_1080x757os/)

**Comment by nvkelso** [comment]
Ha! What is this? :)

**Comment by migurski** [comment]
> [My plan to create a perfectly flat and level Kansas](http://cartographerswithoutborders.org/post/132149989593/my-plan-to-create-a-perfectly-flat-and-level) by moving 5,501 cubic miles of earth from west to east. It’s the ideal Kansas. Still some details to work out about rivers, roads, etc. Watch out for the 900-foot cliff bisecting Kansas City.

**Pull request merged**
