### PR TITLE
Add NC Board of Elections Statewide Geocodes

### PR DESCRIPTION
**Pull request by JessePresnell**
## Source Information
All geocodes from the North Carolina State Board of Elections voterfile, keyed on address. 

### Schema
```
-- ----------------------------------------------------------------------------
Purpose: 	Address Points data layout:
File name: 	address_points_sboe.zip
Date effective: April 4, 2018

-- ----------------------------------------------------------------------------
geocode_id  int              NCSBE Unique ID
county_id   int              NCSBE County ID (1 to 100)
county      varchar(20)      County Name               
st_address  varchar(75)      Residential address house number and street name
city        varchar(30)      Residential address city name
zip         varchar(9)       Residential address zip code
house_no    varchar(6)       Residential address house number
half_no     varchar(6)       Residential address half number          
st_pre      varchar(2)       Residential address prefix direction
st_name     varchar(30)      Residential address street name
st_type     varchar(4)       Residential address street type
st_suf      varchar(2)       Residential address suffix  direction
lat_feet    varchar(16)      Y Coordinate in NAD_1983_StatePlane_North_Carolina_FIPS_3200_Feet (EPSG:2264)
long_feet   varchar(16)      X Coordinate in NAD_1983_StatePlane_North_Carolina_FIPS_3200_Feet (EPSG:2264)
latitude    varchar(10)      Y Coordinate in WGS 84 decimal degrees (EPSG:4326)               
longitude   varchar(10)      X Coordinate in WGS 84 decimal degrees (EPSG:4326)
```

### Head
```
9113037	29	DAVIDSON	425 VALLEY DR	WINSTON-SALEM	27107	425	\N	\N	VALLEY	DR	\N	810295.582684472	1651372.993274935.970684	-80.178192 
9113038	29	DAVIDSON	745 BAILEY RD	WINSTON-SALEM	27107	745	\N	\N	BAILEY	RD	\N	809537.341090724	1652537.382678435.968639	-80.174227 
9113039	29	DAVIDSON	469 INVERNESS DR	WINSTON-SALEM	27107	469	\N	\N	INVERNESS	DR	\N	823729.137182146	1656121.92111306	36.007738	-80.162676 
9113040	29	DAVIDSON	3416 FRIENDSHIP LEDFORD RD	WINSTON-SALEM	27107	3416	\N	\N	FRIENDSHIP LEDFORD	RD	\N	814140.482474983	1656986.03683889	35.981427	-80.159376 
9113041	29	DAVIDSON	109 WINGED FOOT CT	WINSTON-SALEM	27107	109	\N	\N	WINGED FOOT	CT	\N	825121.205264151	1655789.87879814	36.011552	-80.163853 
9113042	29	DAVIDSON	1761 JOHN GREEN RD	WINSTON-SALEM	27107	1761	\N	\N	JOHN GREEN	RD	\N	811404.849822894	1661726.92696339	35.974064	-80.143247 
```

### CODE REVIEW

**Comment by iandees** [comment]
Does the file actually contain the string `\N` or is that a newline? If it's a newline without proper quoting, it will break the CSV reader.

**Comment by JessePresnell** [comment]
@iandees 
> Does the file actually contain the string `\N` or is that a newline? If it's a newline without proper quoting, it will break the CSV reader.

`\N` in this file is `NULL` -- any recommendations for how to handle that?

**Comment by iandees** [comment]
> `\N` in this file is `NULL` -- any recommendations for how to handle that?

The code doesn't know how to handle special-case "null". If you created the file, it should just be a blank string. It might be a good idea to add support for special 'empty' strings to the conform section parsing in machine.

**Comment by JessePresnell** [comment]
> The code doesn't know how to handle special-case "null". If you created the file, it should just be a blank string. It might be a good idea to add support for special 'empty' strings to the conform section parsing in machine.

@iandees, unfortunately, I didn't create this file. I can replace the `\N` characters independently and land the file, but that may not be very helpful in automating the import of the file. 

I just run 

```python
import pandas as pd

file_path = "Shapefiles/Address_pts/address/address_points_sboe.txt"
df = pd.read_csv(file_path, sep='\t', names=["geocode_id","county_id","st_address","city","zip","house_no","half_no","st_pre","st_name","st_type","st_suf","lat_feet","long_feet","latitude","longitude"], header=0, na_values="\\N")
print(df.iloc[0])
```

**Comment by JessePresnell** [comment]
Looks like the data was parsed correctly from previewing the https://data.openaddresses.io/runs/900015/us/nc/nc_board_of_elections.zip file

**Comment by JessePresnell** [comment]
@iandees am I misreading the parsed data or did this correctly get parsed? Anything else I can do here?

**Comment by iandees** [comment]
Ah, sorry. I'd like to see it pull in the full name of the street before we merge it in. Right now it's only pulling in part of the name without the prefix or suffix.

**Comment by JessePresnell** [comment]
@iandees I believe this should pull prefix and suffix in now. The columns being used to parse address here shouldn't have NULL values, and therefore the `\N` problem should largely be moot. Waiting for the parse to come back to know for sure.

**Pull request closed without merging**
