### PR TITLE
add us-ks-shawnee county

### PR DESCRIPTION
**Pull request by ingalls**

### CODE REVIEW

**Comment by ingalls** [comment]
@NelsonMinar @migurski could one of you check this one out when you get a chance? It works with both the node & python versions of `esri-dump`. Otherwise I can load the file into the cache.

**Comment by iandees** [comment]
The source is just timing out.

**Comment by ingalls** [comment]
Yeah I saw that in the log. What makes me suspicious is that
curling/esridumping the source works perfectly when done locally

**Comment by NelsonMinar** [comment]
Huh, weird, the log shows it downloaded stuff from an ESRI endpoint for 25 minutes and then the server went offline. I suspect a transient error with the source server. Now that it's merged we should know more after a few attempts.

**Pull request merged**
