### PR TITLE
FL Statewide Dept of Revenue addresses for 2021

### PR DESCRIPTION
**Pull request by albarrentine**
Updating statewide source for 2021

### CODE REVIEW

**Comment by albarrentine** [comment]
`openaddr.cache.DownloadError: 403 response from https://data.openaddresses.io/cache/uploads/albarrentine/bcdbc8/statewide_2021-01-01.csv.zip`

Guessing an ACL issue with S3?

**Comment by iandees** [comment]
Yea, this would be fixed by https://github.com/openaddresses/batch/issues/134

**Comment by MiniCodeMonkey** [comment]
Sounds like this can be merged after a re-run 👍

**Comment by albarrentine** [comment]
Re-run this please.

**Pull request merged**
