### PR TITLE
Contributing to: united_states of america-highlands county, fl.json

### PR DESCRIPTION
**Pull request by bmoregeo**
Adding/Updating united_states of america-highlands county, fl.json

### CODE REVIEW

**Comment by migurski** [comment]
Hm, the service looks to be dead: http://data.openaddresses.io.s3.amazonaws.com/runs/1345/output.txt

**Comment by migurski** [comment]
@iandees this is the second place I’ve seen `compression: text`, might it also be a result of bad UI in our submission tool? I’ve not used it either.

**Comment by bmoregeo** [comment]
I'm going to just start editing these through github. There is some funky stuff going on through the website.

**Comment by migurski** [comment]
:+1: and sorry for the website issues!

**Pull request closed without merging**
