### PR TITLE
Update des_moines.json

### PR DESCRIPTION
**Pull request by iojjjjiiii**
Updated the URL, as the source path changes monthly.

### CODE REVIEW

**Comment by trescube** [comment]
There's something wrong with their query endpoint.

**Comment by trescube** [comment]
Wait, what?  In pyesridump, it sometimes redirects to the HTML query page, sometimes it downloads all the data.  I'm confused.

**Comment by trescube** [comment]
Re-run this please

**Comment by trescube** [comment]
Re-run this please

**Comment by iojjjjiiii** [comment]
Didn't seem to help...

**Comment by trescube** [comment]
If you want to trigger another attempt, use "Re-run this please" like I did above.

**Comment by iojjjjiiii** [comment]
Re-run this please

**Comment by iojjjjiiii** [comment]
Thanks for the tip but wow it is not obvious that it's an actual instruction and not a personal request :)

**Comment by trescube** [comment]
Ha!  I hadn't even considered that!  You must have been very confused.

**Comment by iojjjjiiii** [comment]
No kidding I am :) This is only my third day on github and wow it is a steep learning curve! Appreciate the help, though.

**Comment by trescube** [comment]
No problem, glad to be of assistance!  Just to save you some potential future embarrassment, that shortcut is only useful on this repo.

**Comment by iojjjjiiii** [comment]
Good to know. Thanks again!

**Pull request closed without merging**
