### PR TITLE
[wip] fix au/tas/launceston

### PR DESCRIPTION
**Pull request by andrewharvey**

### CODE REVIEW

**Comment by iandees** [comment]
Is this still WIP, @andrewharvey ?

**Comment by iandees** [comment]
I'm going to merge these for now. If more changes are needed, feel free to open up another PR.

**Comment by andrewharvey** [comment]
hi @iandees this wasn't really ready to be merged (it's why I left WIP still in the title, maybe we should use an "in progress" label for PRs not ready?), anyway thanks for trying to clean up the open PR list :+1: 

The reason it wasn't ready is because the source data looks like this:

**address**: `1/10 Teal Court NEWNHAM TAS 7248`
**houselabel**: `1/10`

which we want transformed into

| k | v |
|---|---|
| **unit** | 1 |
| **number** | 10 |
| **street** | Teal Court |
| **city** | NEWNHAM |
| **region** | TAS |
| **postcode** | 7248 |

with this PR it looks like:

| k | v |
|---|---|
| **unit** | 110 |
| **number** | 1/10 |
| **street** | Teal Court NEWNHAM TAS 7248|
| **city** | 1/10 Teal CourtNEWNHAM |
| **region** | 1/10 Teal Court NEWNHAMTAS |
| **postcode** | 7248 |

which is really wrong

I've opened a new PR revering that which I'll merge once CI passes and I've restored my branch so it can continue to be worked on.

The reason this PR is still sitting here is I wasn't able to get the regex's working. That and I was never able to work out how to run it locally so I could easily see the results of my regexp without pushing the branch and seeing the results. If you'd like to see this PR closed, any help in this regard would be very much appreciated! :pray: 

Thanks.

**Comment by andrewharvey** [comment]
PS @iandees do you know how to reopen this PR so we can continue to work on it and merge it once it's ready?

**Comment by iandees** [comment]
Apologies! I was indeed a little merge happy yesterday. There's no way to re-open a pull request, unfortunately.

**Comment by andrewharvey** [comment]
It's okay @iandees I know you were just trying to clean up the large list of open PRs. I've created the "in progress" label so it's clearer which PRs aren't ready to be merged.

**Pull request merged**
