### PR TITLE
conform object added for VT e911 addresses - should now be parse-able

### PR DESCRIPTION
**Pull request by wboykinm**
These should be GTG. @iandees - is it okay for `accuracy` to be numeric? I couldn't find a good example.

Rooftops of VT, inbound:

### CODE REVIEW

**Comment by iandees** [comment]
Looks like `accuracy` is not supported. Can you just remove that line from the conform object?

**Comment by wboykinm** [comment]
@iandees Should I remove `accuracy` from the docs then? Seems like a pretty important item.

**Comment by iandees** [comment]
It [looks like](https://github.com/openaddresses/openaddresses/blob/master/test/sources.js#L69-L70) `accuracy` should be a number, but the `openaddresses-conform` project doesn't use it at all and it's not listed in the [list of available `conform` options](https://github.com/openaddresses/openaddresses/blob/master/test/sources.js#L53).

I would say leave it out of this source for now.

**Comment by wboykinm** [comment]
All good then; who merges?

**Comment by iandees** [comment]
Meee.

**Comment by iandees** [comment]
Next time @migurski runs it we should have data, but the map won't update until @sbma44 re-renders it.

**Comment by sbma44** [comment]
@iandees I reran the map right after the Spain import, but it looks like Flanders data had a busted SRS. Rerunning it now, should be up by tomorrow.

**Pull request merged**
