### PR TITLE
[Ranged Addresses]: usa-new_jersey-newark.json

### PR DESCRIPTION
**Pull request by riordan**
Adding/Updating usa-new_jersey-newark.json

### CODE REVIEW

**Comment by iandees** [comment]
Can you move this to `sources/us/nj/newark.json` please?

**Comment by geobrando** [comment]
@iandees  As this was submitted via the app, it still won't pass as it needs a conform.  That really needs to be updated, possibly to populate an issue instead of a PR. Think @riordan can handle it as he works for Mapzen but others wouldn't know how to get this to pass the CI

Also, @riordan I think you meant for the data url to be `http://njgin.ci.newark.nj.us/arcgis/rest/services/CityBaseMap/8Parcels/MapServer/0`, correct?

**Comment by migurski** [comment]
I’m hearing a major need to get the app updated. Been chatting with @ajturner about this.

**Comment by riordan** [comment]
Thanks @geobrando! Since this is my first submission, I wasn't sure how the export was intended to be formatted.

Happy to make the changes.

But the real contributor here is @jqnatividad, who's been working with Newark on their open data portal and got them really excited about contribution to the project. A few of @ontodia's hosted CKAN data portal clients are really excited about making it easy for projects to leverage their open data, so this feels like the start of something really good.

Patch coming soon.

**Comment by riordan** [comment]
@migurski lemme know how I can help out on that.

**Comment by migurski** [comment]
I’m hoping to speak with ESRI folks about it tomorrow, but the short version is that the app can only be improved with user participation to make sure we don’t guess at a confusing UI again. I’d like their help getting direct introductions to local government people who could participate as guinea pigs. Could Joel be one of these?

**Comment by geobrando** [comment]
@riordan It looks like this source does not have situs addresses but only owner addresses.  OA is expanding to be a repository of parcels in addition to address points, but currently we're only accepting sources with physical addresses.

I just brought up this point in https://github.com/openaddresses/machine/issues/163.  In the meantime, I've added this source to the [parcel wiki](https://github.com/openaddresses/openaddresses/wiki/Parcel-Sources).

Thanks again.

**Comment by slibby** [comment]
@geobrando I think "PROPLOC" might work with some Regex work: 
`PROPLOC: 41-43 COMMONWEALTH AVE`

http://njgin.ci.newark.nj.us/arcgis/rest/services/CityBaseMap/8Parcels/MapServer/0/query?where=OBJECTID%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=PROPLOC&returnGeometry=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=pjson

However, returns Address Ranges for most parcels, not sure that's been discussed here before.

**Comment by geobrando** [comment]
@slibby You are right! Missed that field.  But yes, address ranges are not supported.  Though I'm quite sure there's some that have found their way into our collection.  If they're mostly ranges I would say we shouldn't use it.

Was mentioned in the roadmap thread https://github.com/openaddresses/openaddresses/issues/996

**Comment by riordan** [comment]
Update: it appears to be a mix of ranges + single addresses.
18114 ranged out of 46218 total

**Comment by jqnatividad** [comment]
Thanks @riordan for submitting this.  We'll work directly with Newark GIS folks to ensure we have clean data. And yes @migurski, would be happy to be a guinea pig.  

Perhaps we can create best practices/standard for sharing this kind of data and use Newark as our reference implementation?

Right now, we're currently working with a few cities in the Northeast with their CKAN installations.  One vision I discussed with @riordan is to work on ckanext-mapzensearch, whereby we incentivize municipalities to publish open address data, which is then harvested/submitted to openaddresses.io, and geocoded against by Mapzen Search.

The hope is, this creates a virtuous cycle that has several benefits:

* cities get a high-quality open source geocoder powered with their open address data without having to expose their ESRI geocoder
* this geocoder can then be used to geo-enrich other datasets they publish
* general public / tech community can use a much better open source geocoder without the severe throttling limitations of geocoders like Google, etc.
* there's an option to mount an in-premise geocoders for high-throughput users (e.g. local civictech projects)

**Comment by iandees** [comment]
Working with CKAN would be amazing. Right now we poll our data sources semi-regularly and download their entire contents to the best of our ability. A CKAN plugin or extension or similar that hit some openaddresses thing to tell us when new data is available (whether someone is interested in contributing brand spanking new data or if there's updates to an existing dataset) would be amazing.

**Comment by jqnatividad** [comment]
@iandees, @riordan and I discussed that as well! :)

Wouldn't it be amazing if openaddresses can just check the data.json of a CKAN instance, and automagically find open address data based on some standard metadata around the open address dataset in the catalog?

And to complete the loop, when the CKAN instance with the oa/mapzen integration geocodes a dataset, you can even find out what "version" of a dataset is being used...

**Comment by iandees** [comment]
I'm going to close this PR because we can't do ranged addresses right now.

If the other things brought up in this ticket (CKAN integration, etc.) are still interesting to folks, please file a new ticket.

**Pull request closed without merging**
