### PR TITLE
added countrywide Uruguay

### LINKED ISSUE #2917: Uruguay Nation-wide Addresses
uy_oa_yeeeeehawwww_sample
uy_oa_yeeeeehawwww

After talking it over with @iandees we will add the data - I see no mention of any terms (Source: http://correo.com.uy/ ) - so we need to maintain that in the metadata if possible.

Dropbox link coming soon ;)

### PR DESCRIPTION
**Pull request by trescube**
Fixes #2917

### CODE REVIEW

**Comment by trescube** [comment]
The data isn't fantastic but it's reasonable.

**Comment by astoff** [comment]
The field "letra" is probably a suffix to the number, and should be concatenated.

**Comment by nvkelso** [comment]
"Wrote 929117 points to /tmp/points-86eu3t99.bin”!

**Comment by migurski** [comment]
Yup! When drawing the preview images that get posted here in comments, we stream all the points to a file in binary form to make it quick to saw through them:

https://github.com/openaddresses/machine/blob/d2d0dc4ae/openaddr/preview.py#L210-L220

**Comment by muralito** [comment]
Where does the source file https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/trescube/bf749a/uy.zip does come from?

**Comment by nvkelso** [comment]
It’s listed in the original issue:
https://github.com/openaddresses/openaddresses/issues/2917

**Pull request merged**
