### PR TITLE
Added 2 Canadian sources

### PR DESCRIPTION
**Pull request by MiniCodeMonkey**
Note: The Kimerbley source *should* process correctly after this has been merged in https://github.com/openaddresses/machine/pull/763

### CODE REVIEW

**Comment by andrewharvey** [comment]
What license is this data made available under?

**Comment by MiniCodeMonkey** [comment]
That's a great questions! Both of these are published as open data without warranty. I have not been able to find a specific license attached to them.

For Cranbrook, here is the disclaimer on map load:

```
This map is for general purposes only.
The City of Cranbrook makes no warranties regarding the
accuracy or suitability of the map for any purpose.
This map is not intended for navigation or legal use or purposes
and should not be relied on as such.
The City of Cranbrook will not be liable for any damage, loss
or injury resulting from the use of the map or information
on the map.
The map may be changed at any time.
```

**Comment by nvkelso** [comment]
That’s for the web app. Is there data specific license? Or email contact?

**Comment by MiniCodeMonkey** [comment]
The web app is the source of this data source. Kimberley data was provided by Christopher Jones from their planning department. No specific license is attached with this data that I have been able to find.

**Comment by MiniCodeMonkey** [comment]
These are both looking good now 👍

**Pull request merged**
