### PR TITLE
add au buildings from Microsoft

### PR DESCRIPTION
**Pull request by andrewharvey**
preemptive PR for buildings

### CODE REVIEW

**Comment by andrewharvey** [comment]
@iandees it looks like all the cache files were wiped

> openaddr.cache.DownloadError: 403 response from https://data.openaddresses.io/cache/uploads/andrewharvey-openaddr/ec6370/au-feb2021.zip

This file I just uploaded a week or so ago and it worked before. When I try to download the latest cache file from http://results.openaddresses.io/sources/au/countrywide to restore it, it also gives a 403.

Is this a problem on the OA infrastructure end?

**Comment by iandees** [comment]
Yea, looks like it. @ingalls I think we need to add a bit of code to batch that fetches data with URL `https://data.openaddresses.io` from `s3://data.openaddresses.io` instead, so we can skip the CDN costs. I'll file a ticket on that.

**Comment by iandees** [comment]
The data wasn't wiped, I just added a referrer check and machine-batch isn't doing the S3 hack that I thought it was doing. We can fix these! See https://github.com/openaddresses/batch/issues/134

**Comment by ingalls** [comment]
I've bumped this as I've added S3 support to `batch`. @andrewharvey Do you use slack? Would love to get you on the OA slack if you do.

**Comment by ingalls** [comment]
```
NoSuchBucket: The specified bucket does not exist
```

**Comment by andrewharvey** [comment]
@ingalls yes please add me `andrew@alantgeo.com.au`

**Comment by ingalls** [comment]
Sent you an invite - @iandees just has to accept it

**Comment by ingalls** [comment]
rerunning with bug fix here: https://batch.openaddresses.io/run/885

**Pull request merged**
