### PR TITLE
Add city of Auburn, AL

### LINKED ISSUE #1967: Add addresses in Auburn, AL
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

### PR DESCRIPTION
**Pull request by iandees**
Fixes #1967.

### CODE REVIEW

**Comment by migurski** [comment]
Testing https://github.com/openaddresses/machine/pull/420:

Re-run this please.

**Comment by migurski** [comment]
Re-run this please.

**Comment by migurski** [comment]
💥 http://s3.amazonaws.com/data.openaddresses.io/runs/125208/preview.png 💥 

preview image

**Comment by nvkelso** [comment]
Satellite suburbs!

**Comment by migurski** [comment]
You can see the university clipped out of the southwestern quadrant:

Auburn

**Comment by nvkelso** [comment]
Polish university apartment blocks ;)

**Comment by migurski** [comment]
😄

**Pull request merged**
