### PR TITLE
[wip] add oa v2 au/nz parels/buildings

### PR DESCRIPTION
**Pull request by andrewharvey**

### CODE REVIEW

**Comment by nvkelso** [comment]
Thanks for tackling this, a huge chunk of work!

**Comment by andrewharvey** [comment]
https://catalogue.data.wa.gov.au/dataset/building-outlines/resource/fcfadd8a-f069-312a-86ff-a9a2d7c94339

**Comment by migurski** [comment]
We recently changed the tags for OA sources and it might affect this PR. [Moving forward, "type" tags are now either "protocol" or "format"](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#core-tags). If this PR is still active it might need to be updated.

**Comment by migurski** [comment]
Great! I think Nick had been working on it, but I don't believe it’s being actively advanced at the moment. Thanks for keeping this branch around.

**Comment by andrewharvey** [comment]
I've added all the parcels from here in new PRs. This PR will still be useful later if buildings are supported, but for now I'll close it.

**Pull request closed without merging**
