### PR TITLE
Update MN URIs that are broken

### LINKED ISSUE #4706: Polk County, Minnesota Addresses
GIS URI Changed: Updated to
http://gis.co.polk.mn.us/arcgis/rest/services/PolkALL/MapServer/20/

### LINKED ISSUE #4707: Pennington County, Minnesota Parcels
GIS URI Changed: http://gismap.co.pennington.mn.us/arcgis/rest/services/Pennington/Pennington_Internal/MapServer/29

### LINKED ISSUE #4708: Add Chippewa County, Minnesota
https://gis.chippewa.mn/arcgis/rest/services/OpenData/OpenData/MapServer/20

### LINKED ISSUE #4709: Add Dodge County, Minnesota
https://maps.co.goodhue.mn.us/server/rest/services/CountyDataDC/Dodge_Parcels/MapServer/0/

### LINKED ISSUE #4710: Add Faribault County, Minnesota
https://services2.arcgis.com/fxB2C8mQfjMb1848/ArcGIS/rest/services/TaxParcels/FeatureServer/0

### LINKED ISSUE #4711: Add Cook County, Minnesota
https://services.arcgis.com/L3KwVADPEG6iD24f/ArcGIS/rest/services/Tax_Parcel_Polygons_Public_View/FeatureServer/0

### LINKED ISSUE #4712: Add Jackson County, Minnesota
http://136.234.46.34/arcgis/rest/services/CriticalInfrastructureSites/MapServer/1

### LINKED ISSUE #4713: Add Sibley County, Minnesota
https://services1.arcgis.com/ca9pZxSKQMiPIqAL/ArcGIS/rest/services/AddressPoints/FeatureServer/0

### LINKED ISSUE #4714: Add Marshall County, Minnesota
http://gismap.co.marshall.mn.us/arcgis/rest/services/Marshall/Marshall_Public_LINK/MapServer/26

### LINKED ISSUE #4715: Add Mahnomen County, Minnesota
https://services8.arcgis.com/eORKbx5CWReJmkoa/arcgis/rest/services/TaxParcels/FeatureServer/0

### PR DESCRIPTION
**Pull request by Garrett-W**
Closes #4715
Closes #4714
Closes #4713
Closes #4712
Closes #4711
Closes #4710
Closes #4709
Closes #4708
Closes #4707
Closes #4706
City instead, CO didn't have address info #4720

### CODE REVIEW

**Comment by Garrett-W** [comment]
#4706 & #4707

**Comment by iandees** [comment]
Whew, this is great @Garrett-W! Thanks for finding all these. Are you ready for this to be merged?

**Comment by ingalls** [comment]
@Garrett-W Just wanted to chime in and also express how much we appreciate PRs like this!!

**Comment by Garrett-W** [comment]
> Whew, this is great @Garrett-W! Thanks for finding all these. Are you ready for this to be merged?

It's as ready as I'm going to get it. Their's a couple of format cleanups, but otherwise the data looks pretty valid.

**Comment by iandees** [comment]
Great, thanks!

**Pull request merged**
