### PR TITLE
adding Henry County, GA

### PR DESCRIPTION
**Pull request by thatdatabaseguy**
Taking a guess on the coordinate system.

### CODE REVIEW

**Comment by iandees** [comment]
Looks like the SRS should be `epsg:2240`.

**Comment by iandees** [comment]
The .prj file doesn't seem to result in a correct projection in QGIS at least. I had to set the layer SRS manually by searching based on the strings in the .prj file.

**Comment by iandees** [comment]
Or maybe I'm just doing something wrong in QGIS :).

**Comment by thatdatabaseguy** [comment]
It seems like for shapefiles there's some metadata that specifies the projection. That map looks more or less correct though a spot check of the addresses seems to have them a block or two off of OSM/Google. Will try epsg:2240 to see if that's closer.

**Comment by thatdatabaseguy** [comment]
Hm same result, but map looks good.

**Pull request closed without merging**
