### PR TITLE
Add churchill county nv

### PR DESCRIPTION
**Pull request by trescube**

### CODE REVIEW

**Comment by migurski** [comment]
Addresses look good; city probably shouldn't be defined though.

**Comment by migurski** [comment]
Also, this weirdness in the original source made me a little sad:

<a href="http://ec2-54-172-233-64.compute-1.amazonaws.com/152391/#lat=39.47677&lng=-118.77575&z=17">screen shot 2017-01-30 at 9 10 24 pm</a>

**Comment by trescube** [comment]
I was outputting city with the raw `CONCAT` value for edge-case comparisons.  It will be removed in the final output.

**Comment by trescube** [comment]
Yeah, the data is a little dirty.

**Comment by trescube** [comment]
Fixes #2447

**Comment by iandees** [comment]
(The "Fixes #xyz" thing only works in the description of the PR, not a comment)

**Comment by trescube** [comment]
I'll figure out github one of these days

**Comment by migurski** [comment]
\o/
new data!

**Pull request merged**
