### PR TITLE
Changed order of specific/generic in Montréal

### LINKED ISSUE #1147: ca-qc-montreal needs merge change
For the roads in montreal the current code is : 
````
    "merge": [
                "SPECIFIQUE",
                "GENERIQUE"
        ]
````
it should be changed to:
````
    "merge": [
                "GENERIQUE",
                "SPECIFIQUE"
        ]
````

as the roads in quebec should be like this:
*Avenue Pierre Baillargeon*
and not like this:
*Pierre Baillargeon Avenue*

### PR DESCRIPTION
**Pull request by migurski**
* [x] Switch to new merge syntax.

Closes #1147

### CODE REVIEW

**Comment by migurski** [comment]
Damn I think this needs some stuff that @ingalls is working on.

**Comment by ingalls** [comment]
@migurski just finishing up a some work related stuff and then I'll whip that PR into shape.

**Comment by ingalls** [comment]
Updated with my PR: https://github.com/openaddresses/openaddresses/blob/master/sources/ca-qc-montreal.json#L17-L20

**Comment by migurski** [comment]
The bigger test failed due to cached results from yesterday, but [Montréal is fine](http://data.openaddresses.io.s3.amazonaws.com/runs/9562/output.txt) so I’m merging.

**Pull request merged**
