### PR TITLE
Kuwait countrywide

### PR DESCRIPTION
**Pull request by sergiyprotsiv**
An official source from the Kuwait Public Authority for Civil Information. Looks great to me!

### CODE REVIEW

**Comment by nvkelso** [comment]
Are two different sources (and duplicate address features) the only current
OpenAddresses config? Has there been discussion around adding language code
postfixed fields on the same original features (assuming the original
feature had multiple columns per language)?

**Comment by migurski** [comment]
No discussion about postfixed fields so far! Our language support has been focused on whole-source properties, as in https://github.com/openaddresses/openaddresses/pull/1613 and [the language tag](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#optional-tags). How might it look?

**Comment by nvkelso** [comment]
What we do in Who’s On First is to add a `:languagecode` postfix to the
property name (ignore the _p and _a for your use case).

- https://github.com/whosonfirst/whosonfirst-names

For example:

```
{
    "wof:name": "Montreal",
    "wof:lang": [ "eng", "fre" ],
    "name:eng_p": "Montreal",
    "name:eng_a": "YMQ",
    "name:fre_p": "Montréal",
    "name:kor_p": "몬트리올",
}

```

**Comment by iandees** [comment]
It might be a good idea to file a new issue to talk about the languagecode suffix so discussion doesn't get lost on this pull request.

**Comment by nvkelso** [comment]
@iandees I've moved it to: https://github.com/openaddresses/machine/issues/521.

**Comment by thatdatabaseguy** [comment]
Data looks good. The "neighborhoods" in this one appear to be [Kuwait's "areas"](https://en.wikipedia.org/wiki/Areas_of_Kuwait), which appear to be a district in some cases and a city in others, but I'd just as soon call them districts.

**Comment by sergiyprotsiv** [comment]
Re-test this please

**Comment by nvkelso** [comment]
Re-test this, please.

**Comment by migurski** [comment]
Re-run this please

**Comment by nvkelso** [comment]
Is there more to do here with Al's comment in https://github.com/openaddresses/openaddresses/pull/2358#issuecomment-273617956?

**Comment by thatdatabaseguy** [comment]
@nvkelso nope, good to go.

**Pull request merged**
