### PR TITLE
Brazil census addresses

### PR DESCRIPTION
**Pull request by astoff**
This PR is preliminary. The dataset covers the whole country, but I have included only São Paulo state as a sample. If you would like to accept it, please let me know how to upload the preprocessed data to OA's cache. I will then prepare the data for the whole country (one source file per state) and update the pull request.

There are a few choices I made in the preprocessing script that I will be happy to discuss if necessary.

### CODE REVIEW

**Comment by thatdatabaseguy** [comment]
São Paulo data LGTM. About 60% have lat/lon but that's still ~740k addresses, virtually all of which have house number (or SN for sem numero), street, city, and postcode.

@migurski there seem to be a few different patterns for caching in the existing scripts. Is there a preference and are these scripts automated or run manually?

**Comment by migurski** [comment]
The scripts are not automated, they get run manually. There's not a strong preference, but if it’s possible to wrap it up in a container like Docker, it may make them easier to run in the future. [Tennessee, New Zealand, and Australia follow that pattern](http://mike.teczno.com/notes/openaddr/docker-address-data.html).

**Comment by astoff** [comment]
I have updated the script to reflect the discussion on https://github.com/openaddresses/openaddresses/issues/2303. I'd say it's ready to merge.

I also have the preprocessed data for the whole country ready to upload (just tell me where). If you prefer to run the script on your end, use https://gist.github.com/astoff/5dc8f0df2e5a63a6750ce981ee1414b5 to generate the JSONs.

**Comment by nvkelso** [comment]
This is super exciting, thanks for your hard work on the PR with repeatable scripts and 1-time data builds :)

The OpenAddress S3 uploader will take files up to 256 mb in size:

- https://results.openaddresses.io/upload-cache

To use it you'll need to be logged in via Github **AND** publicize your membership in the OpenAddresses organization.

**Comment by nvkelso** [comment]
Connects with https://github.com/openaddresses/openaddresses/issues/2303.

**Comment by nvkelso** [comment]
In the GIST you say:

`#        ('53', 'Distrito Federal',         'DF'), #This has a funny address format, needs special conform`

Has that been fixed subsequently, or will we need a followup issue to resolve the special conform for the capital's address format?

**Comment by migurski** [comment]
Fantastic! FYI @nvkelso, I fixed the bug where membership must be public. It can be private now and the upload will still work. Can also raise the limit above 256MB if needed.

**Comment by astoff** [comment]
@nvkelso There are two things with Distrito Federal: First, there is a better statewide dataset (https://github.com/openaddresses/openaddresses/pull/2311, but it is failing to download). Second, I am not really sure how to map Brasilia's address scheme to the usual number + street scheme—i'm trying to check with a local.

**Comment by thatdatabaseguy** [comment]
Looked into addresses in Brasilia a little while back. The city uses a grid system that's unlike anywhere I've ever seen. The [UPU example](http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/braEn.pdf) is:

```
Sr. Luis Carvalho
SBN – Quadra 13 – Bloco B – 8º andar
BRASÍLIA – DF
70002–900
BRAZIL
```

Here "SBN" would be a sector of the city, which together with "Quadra 13" (usually combined and shortened, so "SBN 13") is sort of like a neighborhood, but also the name of the principal street within said neighborhood. Then "Bloco B" is a named/numbered building (and "8º andar" = 8th floor).

For OpenAddresses it probably makes the most sense to call "SBN 13" the street and "Bloco B" the house number.

**Comment by astoff** [comment]
@thatdatabaseguy That's how I did it in https://github.com/openaddresses/openaddresses/pull/2311. In the census, everything is concatenated in the street field, so there's no realiable way to split out the "bloco".

**Comment by thatdatabaseguy** [comment]
Ah ok. Would a regex in the transform work? Haven't looked at the raw census files for DF yet but it seems like the addresses there are very structured so something like this might do the trick if everything's concatenated:

```json
    "number": {
        "function": "regexp",
        "field": "street name",
        "pattern": "^(?:.*?)(?:\\s*(Bloco\\b.*))?$"
    },
    "street": {
        "function": "regexp",
        "field": "street name",
        "pattern":  "^(.*?)(?:\\s*Bloco\\b.*)?$"
    }
```

**Comment by astoff** [comment]
Well, there are many variants (bloco, bl, lote, lt) so it would need testing. But I think the other PR (local gov data) is much better anyway. Should we not worry?

**Comment by astoff** [comment]
All right, so (assuming it builds) I will let somebody else do the merging, so others get a change to see if it looks OK.

Please squash and merge—there is a large deleted file in an intermediate commit.

**Comment by thatdatabaseguy** [comment]
Looks good to me! It's probably worthwhile to investigate the other source for Distrito Federal.

**Comment by migurski** [comment]
🇧🇷 a whole new country of data! 🇧🇷

**Comment by nvkelso** [comment]
The data was only for this one region as a sample? I think there may be
some more work to do to get everything in?

**Comment by migurski** [comment]
I do see 30 files in this PR!

**Comment by thatdatabaseguy** [comment]
For whatever reason the map only shows São Paulo, but [all the states were built as part of the PR](http://results.openaddresses.io/jobs/5ad2e0f1-9cfa-4a81-bfba-73d0564c596e).

**Comment by nvkelso** [comment]
Thanks for the links, I see them now :)

**Comment by migurski** [comment]
Ah yeah, sorry, the part of `machine` that decides which map to post back is not the most reliable thing. That’s a bug for me.

**Pull request merged**
