### PR TITLE
Updated us/oh/miami to more up-to-date source

### PR DESCRIPTION
**Pull request by MiniCodeMonkey**
This source has addresses from newer developments that were not present in the previous static zip file dump

### CODE REVIEW

**Comment by trescube** [comment]
This layer has address points if that's preferable:

http://services2.bhamaps.com/arcgis/rest/services/AGS_Miami_CO_OH_GISMap/MapServer/0

**Comment by MiniCodeMonkey** [comment]
@trescube Thanks a bunch for pointing that out 🙌 Updated the source, and doing another sanity check when the source job has completed.

**Comment by MiniCodeMonkey** [comment]
I can confirm that the data looks good AND that it has addresses from new developments in the county that were not in the previous dataset.

This is good to merge in my end.

**Comment by trescube** [comment]
Thanks, @MiniCodeMonkey!

**Pull request merged**
