### PR TITLE
Moved us/ky/boone to us/ar/boone

### PR DESCRIPTION
**Pull request by davidchiles**

### CODE REVIEW

**Comment by iandees** [comment]
This data is for [Boone County, AR](https://censusreporter.org/profiles/05000US05009-boone-county-ar/), not Boone County, KY. The geoid was correct, the filename was wrong.

**Comment by davidchiles** [comment]
oh whoops

**Comment by iandees** [comment]
Awesome, thanks!

**Comment by davidchiles** [comment]
Too many Boones!

**Pull request merged**
