### PR TITLE
Add KS Sources

### PR DESCRIPTION
**Pull request by ingalls**
cc/ @iandees @migurski

### CODE REVIEW

**Comment by migurski** [comment]
Seeing some failures on these, like:

* http://data-test.openaddresses.io.s3.amazonaws.com/runs/205/output.txt
* http://data-test.openaddresses.io.s3.amazonaws.com/runs/201/output.txt

etc.

**Comment by iandees** [comment]
I think you need to specify `OA:x` and `OA:y` for `lon` and `lat`, respectively. I'm not sure if the processing steps will guess that automatically.

**Comment by ingalls** [comment]
@migurski how does one know what the run # from the PR?

**Comment by ingalls** [comment]
@iandees seems to be working as expected: http://data-test.openaddresses.io.s3.amazonaws.com/runs/225/output.txt

**Comment by migurski** [comment]
@ingalls for the moment, you’d go to https://github.com/openaddresses/openaddresses/settings/hooks/5060155 and look at responses from recent deliveries, which would send you here: http://ci.openaddresses.io/jobs/24958d54-78ea-4811-be46-0d157c2702bf

That runaround is because I’m just wrapping up testing on the CI service. Pretty soon, results would show up alongside the ones from Travis on this page right here.

**Comment by migurski** [comment]
Turned it on. Thomas County looks to be failing because of [corrupt data coming back from ArcGIS](http://data-test.openaddresses.io.s3.amazonaws.com/runs/282/output.txt). It worked okay previously, so I’m going to merge.

**Pull request merged**
