### PR TITLE
Updated Taiwan regional data

### PR DESCRIPTION
**Pull request by jeffdefacto**
This adds a few new provinces and updates several others to 2023 and 2024 data. All the old esri links were dead but some of the provinces are available in https://data.gov.tw/ or on county websites with a clear CC-BY compatible license. The available data itself is mostly standardized in content but the download format is all over the place and the district and region information is stored as a reference number which needs to be joined from another source [here](https://www.dgbas.gov.tw/public/data/dgbas03/bs1/%E8%A1%8C%E6%94%BF%E5%8D%80%E5%9F%9F%E5%8F%8A%E6%9D%91%E9%87%8C%E4%BB%A3%E7%A2%BC/%E5%90%84%E7%B8%A3%E5%B8%82%E5%8F%8A%E7%9B%B4%E8%BD%84%E5%B8%82.pdf) to get the actual names. I converted it to a csv and have attached here for future use [Taiwan_county_district_codes.csv](https://github.com/user-attachments/files/17416800/Taiwan_county_district_codes.csv)

There is an "area" (地區) column that seems to be used in lieu of a street name in some instances so I added that to the street joins but can pull it out if someone with better context knows better.

### CODE REVIEW

**Comment by jeffdefacto** [comment]
Hi @iandees, can you rehost these datasets please.

https://jeffu.dev/data/changhua_addresses_2024.csv.zip
https://jeffu.dev/data/keelung_addresses_2024.csv.zip
https://jeffu.dev/data/kaohsiung_addresses_2024_10.csv.zip
https://jeffu.dev/data/miaoli_addresses_2024.csv.zip
https://jeffu.dev/data/new_taipei_city_addresses_2024.csv.zip
https://jeffu.dev/data/taoyuan_addresses_2024_08.csv.zip
https://jeffu.dev/data/tainan_addresses_2023.csv.zip
https://jeffu.dev/data/taipei_city_addresses_2024_10_02.csv.zip
https://jeffu.dev/data/taichung_addresses_2024_06.csv.zip
https://jeffu.dev/data/yunlin_addresses_2023.csv.zip

**Comment by iandees** [comment]
* https://data.openaddresses.io/cache/uploads/iandees/720b5a/changhua_addresses_2024.csv.zip
* https://data.openaddresses.io/cache/uploads/iandees/75b8be/keelung_addresses_2024.csv.zip
* https://data.openaddresses.io/cache/uploads/iandees/71cacd/kaohsiung_addresses_2024_10.csv.zip
* https://data.openaddresses.io/cache/uploads/iandees/c9537e/miaoli_addresses_2024.csv.zip
* https://data.openaddresses.io/cache/uploads/iandees/22864b/new_taipei_city_addresses_2024.csv.zip
* https://data.openaddresses.io/cache/uploads/iandees/f796d0/taoyuan_addresses_2024_08.csv.zip
* https://data.openaddresses.io/cache/uploads/iandees/6ff385/tainan_addresses_2023.csv.zip
* https://data.openaddresses.io/cache/uploads/iandees/af53d6/taipei_city_addresses_2024_10_02.csv.zip
* https://data.openaddresses.io/cache/uploads/iandees/a682ba/taichung_addresses_2024_06.csv.zip
* https://data.openaddresses.io/cache/uploads/iandees/55f72f/yunlin_addresses_2023.csv.zip

**Comment by jeffdefacto** [comment]
This is ready to go now

**Comment by iandees** [comment]
Nice, thanks for doing the update.

**Pull request merged**
