### PR TITLE
Added Taney County

### PR DESCRIPTION
**Pull request by migurski**
Used pre-release Beacon scraper.

Part of #2661 — does it close?

### CODE REVIEW

**Comment by iandees** [comment]
That's some Beacon-ey data!

**Comment by migurski** [comment]
🏄 “Beaconic,” the kids like to say 🤙

**Comment by iandees** [comment]
"Get off my Beacon!" 👴

**Comment by nvkelso** [comment]
Looks legit to me :)

**Comment by migurski** [comment]
Merged!

**Pull request merged**
