### PR TITLE
Contributing to: switzerland-zürich-zürich.json

### PR DESCRIPTION
**Pull request by DonGoginho**
Adding/Updating switzerland-zürich-zürich.json

### CODE REVIEW

**Comment by slibby** [comment]
@DonGoginho It looks like that CSV doesn't contain Latitude and Longitude data, so you would need to change it to reference the zipped shapefile (https://data.stadt-zuerich.ch/storage/f/adressen/adressen.zip) to get this to pass. 

You'll also want to add a "conform" object, which there are examples of in: https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md

and in:
https://github.com/slibby/openaddresses/commit/44931ba8497e79ddf970f690e3202b7dde97b2de

Let me know if you'd like some help, I'm happy to provide a sample.

**Comment by DonGoginho** [comment]
Hej Sam

Oh sorry, true, I forgot about wgs84. But on the open data catalog of Zurich there is also a GeoJSON file, that already comes with lat long (WGS84) geocoordinates:
https://data.stadt-zuerich.ch/storage/f/adressen/adressen.json 

Can you use this one instead?

Best regards, Marco

**Comment by slibby** [comment]
@DonGoginho I've created a Pull Request with the geojson file which is successful: https://github.com/openaddresses/openaddresses/pull/1276

**Comment by slibby** [comment]
@DonGoginho This has been merged: https://github.com/openaddresses/openaddresses/pull/1276

Check it out!

image

**Comment by DonGoginho** [comment]
Great, it looks good. But what do the unmerged commits mean in the previous comment? Something still wrong?

**Pull request closed without merging**
