### PR TITLE
Added Piemonte

### PR DESCRIPTION
**Pull request by sergiyprotsiv**
Added Piemonte, which appears to have very good coverage.
This is the WMS server at http://geomap.reteunitaria.piemonte.it/ws/taims/rp-01/taimsbasewms/wms_sfondo_cart_rif_bn?request=getcapabilities&service=WMS (layer AccessoCarraio), which I converted to shape file and put on Dropbox. 

Again, let me know if there is a better procedure.

### CODE REVIEW

**Comment by nvkelso** [comment]
Re-run this please

**Comment by sergiyprotsiv** [comment]
Here again a straightforward dump of a WFS server to the shapefile. Should be a GDAL one-liner.
Let me know if you want me to upload the file to S3, but please grant me the privileges then.

**Comment by nvkelso** [comment]
Once you publicize your membership in OpenAddresses org via Github admin you'll have permissions to upload using S3.

**Comment by migurski** [comment]
Re: public membership, I've got an issue to fix that bug here: https://github.com/openaddresses/machine/issues/482

**Comment by sergiyprotsiv** [comment]
Hard to say what is happening here. Doing `curl "http://geomap.reteunitaria.piemonte.it/ws/taims/rp-01/taimsbasewms/wms_sfondo_cart_rif_bn?service=WFS&version=1.1.0&request=GetFeature&typeName=AccessoCarraio&CRC=EPSG:4326" -o it-piemonte.gml` locally seems to produce a valid 220 MB GML file.

**Comment by iandees** [comment]
I think it's looking for a file ending in `.gml`, not a file ending in `.xml`.

**Comment by panchohuevos** [comment]
Delete

**Comment by sergiyprotsiv** [comment]
The original website is now down and the replacement does not support WFS. Reverting the source back to the cached data.

**Pull request merged**
