### PR TITLE
Added attribution license tags

### LINKED ISSUE #1343: Document new attribution tag support
Third task for https://github.com/openaddresses/openaddresses-ops/issues/7: document new attribution tags in license dictionaries.

### PR DESCRIPTION
**Pull request by migurski**
Closes #1343.

### CODE REVIEW

**Comment by geobrando** [comment]
Was going to update the tests before this was merged but can start a new branch

**Comment by iandees** [comment]
Sorry, I was a bit merge-happy this morning.

**Comment by migurski** [comment]
Crap, I always forget about the tests in this repository. Sorry.

**Comment by geobrando** [comment]
No big deal.  Working on them now

**Pull request merged**
