### PR TITLE
updated conform (Wilson County, TX)

### PR DESCRIPTION
**Pull request by trescube**

### CODE REVIEW

**Comment by trescube** [comment]
Re-run this please

**Comment by trescube** [comment]
Re-run this please

**Comment by sbma44** [comment]
I can reproduce this error locally -- looks like an underpowered server getting overwhelmed. @migurski is there any way to throttle machine requests for a particular source?

**Comment by trescube** [comment]
Re-run this please

**Comment by trescube** [comment]
Source is now at https://webmap.trueautomation.com/arcgis/rest/services/WilsonMapSearch/MapServer/1

`situs` field needs to be parsed extra-special-like, it contains things like:

- 1008 ESCHENBURG ST POTH, TX 78147
- 11172 FM 541 W MC COY, TX 78113

**Comment by trescube** [comment]
Source is no longer available, along with a lot of other Texas sources previously located at mapsatbis.com.

**Pull request closed without merging**
