### PR TITLE
adding Mogilev, Belarus

### PR DESCRIPTION
**Pull request by thatdatabaseguy**
Same format/regexes as Vitebsk

### CODE REVIEW

**Comment by thatdatabaseguy** [comment]
Only 1154 addresses in there, which seems low, but otherwise looks ok. Maybe there's a better layer.

**Comment by sergiyprotsiv** [comment]
There is another layer with 250K addresses here: http://mogilev.gismap.by/arcgis/rest/services/Poisk/MapServer/2

**Comment by thatdatabaseguy** [comment]
Thanks @sergiyprotsiv! Trying that one now.

**Comment by thatdatabaseguy** [comment]
Huzzah, looks like about 140k with house numbers!

I couldn't find a working, accessible layer for the other Belarusian oblasts, but if you do come across one, please feel free to copy these configs and add it in. The regexes should be working pretty well at this point (for parsing this style of address anyway).

**Comment by sergiyprotsiv** [comment]
There are a bunch of sources for Gomel (one for each part of the region): http://gomel.gismap.by/arcgis/rest/services/poisk/MapServer
And that service also has data for Minsk: http://gomel.gismap.by/arcgis/rest/services/Poiskminsk/MapServer/2
They occasionally time out though have some character encoding issues. Pyersidump gets them via quad tree queries, but the text os all wrong.

**Comment by thatdatabaseguy** [comment]
Ah, had tried that source but when trying to test a query in the browser it returned a 403. If the Gomel source is working programmatically I can add it.

**Pull request merged**
