### PR TITLE
add city of Cape Coral, FL, USA

### LINKED ISSUE #3576: Cape Coral, FL parcels
https://capeims.capecoral.net/arcgis/rest/services/AGOL/Ownership_Public/FeatureServer/0

### PR DESCRIPTION
**Pull request by trescube**
Fixed #3576

### CODE REVIEW

**Comment by trescube** [comment]
@albarrentine does the `chain` function work?  I have 2 PRs using it but both appear to fail.

**Comment by migurski** [comment]
[The error](https://s3.amazonaws.com/data.openaddresses.io/runs/299018/output.txt):

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/openaddr/process_one.py", line 87, in process
    cache_result = cache(temp_src, temp_dir, extras)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/__init__.py", line 104, in cache
    downloaded_files = task.download(source_urls, workdir, data.get('conform'))
  File "/usr/local/lib/python3.4/dist-packages/openaddr/cache.py", line 341, in download
    query_fields = EsriRestDownloadTask.field_names_to_request(conform)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/cache.py", line 332, in field_names_to_request
    return list(filter(None, sorted(fields)))
TypeError: unorderable types: NoneType() < str()
```

**Comment by trescube** [comment]
I implemented as described in the [documentation](https://github.com/openaddresses/openaddresses/blob/master/ATTRIBUTE_FUNCTIONS.md#chain).

**Comment by albarrentine** [comment]
@trescube (my bad, thought I'd already responded to this), there's an open pull request on machine that needs to be merged before `chain` can really be used: https://github.com/openaddresses/machine/pull/656, but when I submitted it, the build/webhooks weren't running for some reason. @migurski any updates on getting the machine build running for PRs?

**Comment by iandees** [comment]
Re-run this please.

**Pull request merged**
