### PR TITLE
Add Sunshine Coast, BC, Canada

### PR DESCRIPTION
**Pull request by iandees**

### CODE REVIEW

**Comment by iandees** [comment]
@migurski where's my @openaddresses-bot !? I miss it.

**Comment by migurski** [comment]
Huh, webhook didn’t run for this and https://results.openaddresses.io is blank. Checking…

**Comment by migurski** [comment]
Re-run this please.

**Comment by migurski** [comment]
Also, `sources/ca/bc/sunshine_cast.json` should be `sources/ca/bc/sunshine_coast.json`.

**Comment by iandees** [comment]
🌤

**Pull request merged**
