### PR TITLE
Contrib geneva

### PR DESCRIPTION
**Pull request by slibby**

### CODE REVIEW

**Comment by slibby** [comment]
Unfortunately the download URL seems to be quite intermittent. Could this be added to the hosted cache?

**Comment by ingalls** [comment]
I'm on a mobile internet connection now, I'll try to get this uploaded first thing tomorrow.

**Comment by ingalls** [comment]
@slibby sorry for the delay `data.openaddresses.io/cache/ch-geneva.zip`

**Comment by slibby** [comment]
:+1: thanks, Nick.

image

**Pull request merged**
