### PR TITLE
Added Sardegna

### LINKED ISSUE #1477: Sardegna, IT
Made some progress but a bit stumped now.

File: http://webgis.regione.sardegna.it/scaricocartografia/DBMPzip/Strato%2003%20-%20Indirizzi/strato03.zip

From: http://www.sardegnageoportale.it/index.php?xsl=1598&s=291551&v=2&c=8831&t=1

Shapefile ST03TE01CL06PTS.shp, joined with tables ST03TE01CL01 and ST03TE01CL02: https://www.dropbox.com/s/5r0sbz42jpw0l6o/sardegna_joined_addresses.zip?dl=0 

I am able to get to number + street name, but no city name or postcode, which will be necessary before they can be contributed.
image

### PR DESCRIPTION
**Pull request by sergiyprotsiv**
Adding the data from most of Sardegna. 

There are two files to be dowloaded from the page indicated  (strato03 and strato09) and a trivial join between house, street, location and municipality tables is needed.

I made the processing offline in QGIS and uploaded the processed file to dropbox. Let me know if another procedure is preferred.

Closes #1477.

### CODE REVIEW

**Comment by slibby** [comment]
this will close https://github.com/openaddresses/openaddresses/issues/1477

**Comment by nvkelso** [comment]
Re-run this please

**Comment by sergiyprotsiv** [comment]
I did the simple join here in QGIS GUI. Let me know if you want a script that will be able to do this automatically, won need to research a bit. Perhaps an intermediate SQLite form or something like that?

**Comment by migurski** [comment]
Format seems okay to me, and thanks for your recent contributions! I think it would make sense to make you a member of the OA Github organization, so that you [can upload to S3](https://results.openaddresses.io/upload-cache) instead of relying Dropbox, and so that you can make branches directly in this repository.

**Comment by iandees** [comment]
I'm going to merge this but I do want to move data out Dropbox and into S3.

**Pull request merged**
