### PR TITLE
Added Lombardia in Italy

### PR DESCRIPTION
**Pull request by sergiyprotsiv**
This covers most of Lombardia, though some municipalities are missing, most notably the city of Milan. There seems to be ongoing work to bring the data from all municipalities online, so hopefully this gets updated in the near term.

### CODE REVIEW

**Comment by sergiyprotsiv** [comment]
There might be some issues with downloading the data directly. If so, it might need to be cached from here: http://www.geoportale.regione.lombardia.it/download-pacchetti?p_p_id=dwnpackageportlet_WAR_geoportaledownloadportlet&p_p_lifecycle=0&metadataid=%7B16C07895-B75B-466A-B980-940ECA207F64%7D

**Comment by nvkelso** [comment]
Re-run this please

**Comment by cesaregerbino** [comment]
Using these these direct links you'll be able to download addresses open datasets about Lombardia Region divided on the Provinces ... 

http://www.geoportale.regione.lombardia.it/rlregis_download/service/package?dbId=323&cod=12 --> Varese
http://www.geoportale.regione.lombardia.it/rlregis_download/service/package?dbId=323&cod=13 --> Como
http://www.geoportale.regione.lombardia.it/rlregis_download/service/package?dbId=323&cod=14 --> Sondrio
http://www.geoportale.regione.lombardia.it/rlregis_download/service/package?dbId=323&cod=15 --> Milano
http://www.geoportale.regione.lombardia.it/rlregis_download/service/package?dbId=323&cod=16 --> Bergamo
http://www.geoportale.regione.lombardia.it/rlregis_download/service/package?dbId=323&cod=17 --> Brescia
http://www.geoportale.regione.lombardia.it/rlregis_download/service/package?dbId=323&cod=18 --> Pavia
http://www.geoportale.regione.lombardia.it/rlregis_download/service/package?dbId=323&cod=19 --> Cremona
http://www.geoportale.regione.lombardia.it/rlregis_download/service/package?dbId=323&cod=20 --> Mantova
http://www.geoportale.regione.lombardia.it/rlregis_download/service/package?dbId=323&cod=97 --> Lecco
http://www.geoportale.regione.lombardia.it/rlregis_download/service/package?dbId=323&cod=98 --> Lodi
http://www.geoportale.regione.lombardia.it/rlregis_download/service/package?dbId=323&cod=108 --> Monza e Brianza

In this way I think that you can automatize the downloads also for future update!!

Do you need I prepare a separate JSON for each province?

Cesare

**Comment by sergiyprotsiv** [comment]
Hi Cesare, thanks a lot! 
These seem to be the same links I have put into the JSON files before (see Files Changed at the top of this PR), but last time there were some issues for the machine to download them. I think that this is due to the need to accept the "terms" when you enter the Geoportale website, so it sets some cookie and the links do not work without that cookie. Any chance for a work-around on OA side (i.e. some sort of stateful "session" download, I am no expert) or asking the guys in Lombardia to open their links?
Sergiy

**Comment by nvkelso** [comment]
Use the OpenAddresses S3 uploader to upload the downloaded files.

**Comment by cesaregerbino** [comment]
Hi Sergi!
I've tried to download a zip file using wget and seems work fine .....
Here you're a sample that you can try

`wget "http://www.geoportale.regione.lombardia.it/rlregis_download/service/package?dbId=323&cod=12" -O Varese.zip`

So in this manner you can automatically download the zip files (I hope ... )

image

In Varese.zip file you'll find the shapefiles that you need

**Comment by sergiyprotsiv** [comment]
I seem to have found the issue with Lombardia: the address string in my original JSON files included the url encoding for the ampersand ("&amp;"), whereas Cesare's links work well. 
I have changed the files now, but the machine is still having problems with it, can you check? Also, could not easily fix the file for Varese (the last one, "va.json"), please change "&amp;" to "&" in the URL there too.
Good news is that no uploads are required, should be sourced straight from the Region's website.

**Comment by sergiyprotsiv** [comment]
Ok, I think Lombardia is now done - it all gets downloaded straight from sources. 
The bot has only plotted one province out of twelve though, perhaps it is related to the fact that this PR has multiple files, so it just took a random one of those.

**Comment by cesaregerbino** [comment]
Good! Are there any other open issues on Italy on which I can try to help?

**Comment by nvkelso** [comment]
@cesaregerbino These are the open Italy issues:

- https://github.com/openaddresses/openaddresses/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20italy

If you can help sort thru them noting which ones have been addressed by your recent PRs (and close the issue) and which ones still need to be added (via new PRs) that would be a huge help. Thanks!

**Pull request merged**
