### PR TITLE
Update Alpine County, CA

### PR DESCRIPTION
**Pull request by arch0345**

### CODE REVIEW

**Comment by iandees** [comment]
Looks like there might be a typo in the schema 🤔

**Comment by iandees** [comment]
Ah nope, typo in the source file here. I misread the error from pre-commit. Updated!

**Comment by iandees** [comment]
The `regexp` function uses this code [here](https://github.com/openaddresses/batch-machine/blob/master/openaddr/conform.py#L914-L915). I wonder if `re.sub()` has a different behavior when the `pattern` doesn't match at all 🤔

**Comment by skylarmt** [comment]
This PR should be closed because https://github.com/openaddresses/openaddresses/pull/7520 was merged instead.  And my regexes are a lot easier on the eyes :)

**Pull request closed without merging**
