### PR TITLE
[WIP] Add data for France.

### LINKED ISSUE #1034: France
http://adresse.data.gouv.fr

### PR DESCRIPTION
**Pull request by migurski**
* [x] Add sample data for Paris.
* [x] Add [remaining departments](https://en.wikipedia.org/wiki/Departments_of_France).
* ~~Check that machine can cope with `sources/fr/*.json` subdirectories.~~

Closes #1034.

### CODE REVIEW

**Comment by sbma44** [comment]
This is an ODbL source, but the vast majority of data that makes it up is licensed under better terms. Can I suggest that we use those instead? OA is a really useful rhetorical tool for improving the OSM geocoding license situation, and I would prefer not to compromise it.

Here are the component datasets that are available under CC-BY compatible terms:

- [FANTOIR](http://www.collectivites-locales.gouv.fr/mise-a-disposition-fichier-fantoir-des-voies-et-lieux-dits) (Open License)
- [Arles Crau Camargue Montagnette](http://opendata.regionpaca.fr/donnees/detail/base-de-donnees-adresses-de-laccm.html) (Open License)
- [City of Montpellier](http://www.data.gouv.fr/fr/dataset/point-adresse-mtn) (Open License)
- [Mulhouse Alsace Agglomeration](http://www.mulhouse.fr/fr/Localisation-et-caracteristiques-des-adresses-postales/Localisation-et-caracteristiques-des-adresses-postales.html) (Open License)
- Greater Lyon (Open License)
- [Urban Community of Strasbourg](http://www.strasbourg.eu/fr/ma-situation/professionnel/open-data/donnees/referentiel-geographique-open-data/bd-adresses) (Open License)
- Urban Community of Lille Métropole (Open License) (can't find link)
- [Nanterre](http://www.nanterre.fr/1409-les-adresses.htm)
- [Brest](https://geo.pays-de-brest.fr/donnees/Pages/Donnees-thematiques.aspx)
- [Nice](http://opendata.regionpaca.fr/donnees/detail/cadastre-de-nice-cote-dazur.html)

I haven't rechecked the licenses of the above recently, but I do have snapshots of all of them.

[Here's the list of BANO sources, including the ODbL ones](http://wiki.openstreetmap.org/wiki/WikiProject_France/WikiProject_Base_Adresses_Nationale_Ouverte_(BANO)/OpenData)

**Comment by migurski** [comment]
Based on the translation, I was under the impression that I had the non-ODbL version of the data downloaded?

**Comment by sbma44** [comment]
Oh! I had no idea! Awesome.

**Comment by migurski** [comment]
:disappointed_relieved: Phew. Charging ahead!

**Comment by migurski** [comment]
I’m going to go ahead and merge this. The CI failure is [actually a bug in machine](https://github.com/openaddresses/machine/issues/158). I don’t believe that the machine batch runner will pick up these subdirectories, but the [process of replacing it](https://github.com/openaddresses/machine/issues/123) is [far-enough along](https://github.com/openaddresses/machine/commits/push-source-tasks-%23123).

**Comment by katossky** [comment]
Is there a reason why the Mayenne département is not included? Should I open a new issue?

From https://openaddresses.io/#map :
2017-03-07-mayenne-missing

**Comment by katossky** [comment]
It actually looks from the pull request itself that @migurski just forgot to add one source file.

**Comment by nvkelso** [comment]
Thanks for the sleuthing!

**Comment by migurski** [comment]
Oops!

**Pull request merged**
