### PR TITLE
Added us/al/pike

### PR DESCRIPTION
**Pull request by davidchiles**

### CODE REVIEW

**Comment by davidchiles** [comment]
Got my Pike counties mixed up.

**Comment by migurski** [comment]
Looks good, thanks David!

**Comment by migurski** [comment]
This source is pretty small, so I’m going to use it to test https://github.com/openaddresses/machine/pull/530:

Re-run this please.

**Comment by migurski** [comment]
Yesss:

screen shot 2017-01-22 at 9 39 29 am

https://s3.amazonaws.com/data.openaddresses.io/runs/150269/slippymap.mbtiles

**Comment by iandees** [comment]
I keep trying to drag this map around and it doesn't do anything! :-P

**Comment by migurski** [comment]
Have you tried turning your computer off and then on?

**Comment by nvkelso** [comment]
Omg, rad!

**Comment by migurski** [comment]
So, it’s just running in a screen and might be dead by the time you look, but I have a live version of a server set up that will display these MBTiles previews if you give it a Run ID.

- http://ec2-54-172-233-64.compute-1.amazonaws.com/150269 — Pike, Alabama
- http://ec2-54-172-233-64.compute-1.amazonaws.com — The front page shows a recent set of California runs

Code is at https://github.com/openaddresses/dotmaps ¯\\\_(ツ)\_/¯

**Pull request merged**
