### PR TITLE
Update countrywide.json Mexico

### PR DESCRIPTION
**Pull request by crebollobr**
added region, district and city 
upload in csv format

### CODE REVIEW

**Comment by ThierryAJean** [comment]
@crebollobr Update the name of the issue mentioning the country Mexico. @iandees can you take a look? we are trying to have this data ready for the early July release in Overture.

**Comment by iandees** [comment]
Yep, thanks for the nudge. I've been looking at it – there was a JSON error in the source that I fixed and was hoping for it to finish fetching data. It looks like there's a case sensitivity problem in here somewhere with the "X" column.

**Comment by crebollobr** [comment]
Do I need resend the data?

**Comment by iandees** [comment]
No, it downloaded and is processing the data now. You can see the "openaddresses/data-pls" line with an orange circle next to it indicating that it's still working. I'm waiting for it to finish or give me an error before merging.

**Comment by crebollobr** [comment]
Thanks for the help on the data

**Comment by iandees** [comment]
Thanks for updating it!

**Pull request merged**
